### ISSUE TITLE
Custow gui

### ISSUE THREAD

**Issue by Kartooofel** [LMBishop/Quests#102]
Hey, is it possible to make your own gui in the quests plugin?

**Comment by LMBishop** [comment]
no, and there isnt any plans of doing that anytime soon either

**Comment by jamesafk** [comment]
Hey. If you want help with this, I know how to make a gui. It isn't particularly complicated and I could send a java class with almost everything you'd need to get started

**Comment by FesterHead** [comment]
FWIW, the [Command Panels](https://www.spigotmc.org/resources/command-panels-custom-guis.67788/) plugin provides a very robust custom GUI experience.  I use it for a SkyBlock menu, store, and a complementary Quest UI.
