### ISSUE TITLE
How is the playing time calculated?

### ISSUE THREAD

**Issue by SnaiilGaming** [LMBishop/Quests#104]
**Description of Error**
There is a problem with the calculation of the task "Playing time". On the plugin wiki it says that the time is calculated in minutes. But I have the impression that it's in minutes or in minecraft ticks. In reality I don't even know because sometimes the time seems to advance in seconds, sometimes it doesn't advance at all ... One thing about the task "Game Time" is completely buggy for me.

**Server :**
 - Minecraft Version: 1.8.8
 - Mod Name: PaperSpigot

**Plugin :**
 - Version: 2.9.5
**Stacktrace**
No error in the console.

Thx for your support

**Comment by LMBishop** [comment]
It advances for every player every 60*20 ticks on the server, so theoretically a player could login just before the tick, get the extra minute, then logout straight after and repeat.

**Comment by SnaiilGaming** [comment]
I didn't quite get the answer.  If I understand the answer, if the quest is 10 minutes of game play. What are the parameters to set? (60*20)*10 ?

**Comment by LMBishop** [comment]
10, as per the [wiki](https://github.com/LMBishop/Quests/wiki/Task-Configuration-Layout#playtime)
