### ISSUE TITLE
Disable the ability to open an empty category

### ISSUE THREAD

**Issue by Tikifirst** [LMBishop/Quests#107]
**Description of Feature**

If you put a category without any quest in the gui (with the config key "categories:"), players will be able to click on it and an empty category will be shown.

It would be cool to cancel the InventoryClickEvent if the targeted category is empty. Thanks to that, we'll be able to make custom & decorated main gui (/q).

I know it's also a bug report, I was kind of disapointed about choosing between a bug report & feature request, sorry :D !

**Comment by nivcoo** [comment]
Good feature
