### ISSUE TITLE
Crop state isn't be taken in count

### ISSUE THREAD

**Issue by Hoknyy** [LMBishop/Quests#110]
**Description of Error** & **To Reproduce**

In quests BLOCK BREAK CERTAIN, if you put block: CROPS, players won't have to wait the crop is grown, and will be able to complete the quest only by destroying baby seeds.

AND if you put  reverse-if-placed: true  --> players won't be able to PLANT before, so the quest will look like broken.
   

**Server (please complete the following information):**
 - Minecraft Version: 1.8
 - Mod Name: PaperSpigot

**Plugin (please complete the following information):**
 - Version: latest one

**Stacktrace**
None

**Comment by codster6789** [comment]
I’d try CROPS-7, if such doesn’t work. It’s due to the fact the plugin doesn’t support age parameters. In which case you’ll have to just use inventory task type.

**Comment by Tikifirst** [comment]
it doesn't work, it would be great to add that

**Comment by codster6789** [comment]
I figured it wouldn’t which overall sucks, I do see the author has plans for a farming task type, who knows when that’ll be completed however.

**Comment by EwansXD** [comment]
Been a while but if you set the data to fully grown cropstate number it should work
