### ISSUE TITLE
Bug quest

### ISSUE THREAD

**Issue by WIBOR2002222** [LMBishop/Quests#115]
Hello, there is a big problem with quests. Players can get the rewards to infinity by breaking and posing the blocks. I put all the security on but the players found a technique to use the bug.

In fact, there is one player who lays the blocks and then the other one who breaks them. Then, the player , having broken the blocks, gives the other player the blocks. This allows to do that infinitely

**Comment by CesarLiesen** [comment]
**pLEASE DONT USE THIS BROKEN PLUGIN caps**

**Comment by WIBOR2002222** [comment]
What plugin do you use ?

**Comment by FesterHead** [comment]
Add an inventory task to the quest to remove the items.

**Comment by WIBOR2002222** [comment]
@FesterHead It's complicated with the big quest (break 1000 diamond ores, ...)

**Comment by FesterHead** [comment]
See my comment in a related issue for a potential to-be-coded solution that could help:  https://github.com/LMBishop/Quests/issues/116#issuecomment-674432290

**Comment by FesterHead** [comment]
I've added CoreProtect compatibility into my fork:  https://github.com/FesterHead/Quests/releases
