### ISSUE TITLE
Lock quests from certain players

### ISSUE THREAD

**Issue by goldenkuky209** [LMBishop/Quests#121]
A permission that can be put in a group to lock certain quests
For ex: quests.command,builder      builder beeing the quest, and that player only has access to the builder quests and nothing else.

**Comment by FesterHead** [comment]
Permissions can be set for a category (group of quests) as well as an individual quest.

For examples, see [config.yml](https://github.com/LMBishop/Quests/blob/master/src/main/resources/config.yml) for categories and [example5.yml](https://github.com/LMBishop/Quests/blob/master/src/main/resources/quests/example5.yml).
