### ISSUE TITLE
Coverter from old config to new one

### ISSUE THREAD

**Issue by divios** [LMBishop/Quests#122]
Hi!

Is there a way to convert all the quest i have on the old config where all the quest and categories where on the config.yml to the new one one where all quest are separated? I mean I have more than 100 quest and is quite a pain to move every single one to a new yml. Also with this system making huge changes is impossible, like replacing some word for another now that they are on separated files...

**Comment by FesterHead** [comment]
No converter that I know of and I'm not familiar with a previous format to provide a clear recommendation.

If you're using Windows try using https://notepad-plus-plus.org/ as a general text editor.  With keyboard shortcuts you can select text, cut it, then open a new file, paste and save.  Has excellent regular expression find/replace in a selection, file, or open files.
