### ISSUE TITLE
Fishing Bug

### ISSUE THREAD

**Issue by KhrysAK47** [LMBishop/Quests#129]
**Description of Error**
Basically when someone throws a fishing rod, a console error pops up. Simple as that.

**To Reproduce**
1) Have Quests v2.5 installed on a Paper 1.8.8 server
2) Use the fishing rod

**Screenshots**
Not applicable

**Server (please complete the following information):**
 - PaperSpigot 1.8.8
- Java 8
- Player Client is 1.16.4

**Plugin (please complete the following information):**
 - Version: v2.5

**Stacktrace**
https://pastebin.com/bKv2bahv

**Comment by LMBishop** [comment]
Your version of Quests is outdated, please update to the latest version of Quests v2.9.5
