### ISSUE TITLE
Spam error when player location is altered by a plugin

### ISSUE THREAD

**Issue by KhrysAK47** [LMBishop/Quests#132]
**Description of Error**
To be short, when a player has a quest and any other plugin modifies player's location, (this can be a fly plugin, a plugin that launches the player or a Jump Pad plugin like in this case, this error appears to be spamming during the ''fly session'').

**To Reproduce**
1. Have any mission started.
2. Use a Jump Pad (I use this https://www.spigotmc.org/resources/epictravel-v1-8-1-16-4-powerful-travel-resource.86543/ but its the same packet type, so really can be any plugin)

**Screenshots**
Not applicable

**Server (please complete the following information):**
 - Minecraft Version: 1.8.8
 - Mod Name: PaperSpigot

**Plugin (please complete the following information):**
 - Version: v2.5

**Stacktrace**
https://pastebin.com/6APKZp8g

**Comment by LMBishop** [comment]
Your version of Quests is outdated, please update to the latest version of Quests v2.9.5
