### ISSUE TITLE
Error when player leaves with pending quest

### ISSUE THREAD

**Issue by KhrysAK47** [LMBishop/Quests#133]
**Description of Error**
When a player has a pending quest (which is not completed), and the player leaves the server, a exception warning appears in console.

**To Reproduce**
1. Start any quest but do not complete it or complete some of it but not completely
2. Leave the server
3. See console

**Screenshots**
Not applicable

**Server (please complete the following information):**
 - Minecraft Version: 1.8.8
 - Mod Name: PaperSpigot

**Plugin (please complete the following information):**
 - Version: v2.5

**Stacktrace**
https://pastebin.com/fJfaNGLn

**Comment by LMBishop** [comment]
Your version of Quests is outdated, please update to the latest version of Quests v2.9.5
