### ISSUE TITLE
Error when using a fishing rod

### ISSUE THREAD

**Issue by KhrysAK47** [LMBishop/Quests#134]
**Description of Error**
Once a player decides to use any fishing rod, a large console error appears. As simple as that.

**To Reproduce**
1. Have Quests 2.5 installed
2. Enter the server
3. Use the fishing rod
4. See console for error

**Screenshots**
Not applicable

**Server (please complete the following information):**
 - Minecraft Version: 1.8.8
 - Mod Name: PaperSpigot

**Plugin (please complete the following information):**
 - Version: v2.5

**Stacktrace**
https://pastebin.com/qjX9Ptwu

**Comment by LMBishop** [comment]
Your version of Quests is outdated, please update to the latest version of Quests v2.9.5
