### ISSUE TITLE
Error when breaking Bed block 

### ISSUE THREAD

**Issue by GamerRukky** [LMBishop/Quests#135]
I made a certain block to mine quest (Block-Bed) and when i broke a bed nothing happened, the counter didn't update and even after breaking all the bed to finish the quest still nothjng happened.
PS:No errors appeared in the console
Plugin-Quests
Server Version-Spigot 1.8.8
Plugin Version-Newest Version

**Comment by KhrysAK47** [comment]
Hey, remember there are two ID's for bed, one for the block state, and the other one of the bed itself.

Bed block ID is 26
And bed item ID is 355
