### ISSUE TITLE
Alternative Blocks

### ISSUE THREAD

**Issue by kokiqn** [LMBishop/Quests#144]
**Description of Feature**
My suggestion is that you add a feature which allows players to either place "block1", "block2" or "block3" or etc... This would be helpful in quests that require players to break or place blocks. This way you can just make a quest which requires you to place 16 of any quartz block type, or wood, stone, wool and etc. (and the given blocks don't have to be similar at all, e.g. - either place oak logs or orange wool). Also, I know you can create as many tasks as you want in a quest, but that's not what I mean. My idea is that upon placing or breaking any of the given blocks it should give you progress for the same task. And you wouldn't have to place/break the same amount of all the blocks.

It could look something like this in the config:
![Screenshot_2](https://user-images.githubusercontent.com/78686129/107146060-6652cc80-694e-11eb-95df-1c3ac407931d.png)
This would mean that if you break any of those blocks, it will count it as progress.
![Screenshot_1](https://user-images.githubusercontent.com/78686129/107146148-fb55c580-694e-11eb-85fb-0ee3ce5dad50.png)

If you have certain questions, as I'm not sure whether I made my explanation clear enough, please ask.

**Comment by LMBishop** [comment]
The current release version of quests currently supports this, documented in the [wiki](https://github.com/LMBishop/Quests/wiki/Task-Configuration-Layout#blockbreakcertain).

If you are on a version pre-1.13 and need datacode support, see this [development build](https://github.com/LMBishop/Quests/actions/runs/545341567)

**Comment by kokiqn** [comment]
Okay, thank you, I really didn't see this last time I checked, turns out its just my poor timing :D
