### ISSUE TITLE
Unlocking quests in more then one category at the same circumstances breaks Quests completely

### ISSUE THREAD

**Issue by KrepelkaCZ** [LMBishop/Quests#145]
**Description of Error**
Upon completion of QuestA which unlocks QuestB in category B and at the same time QuestC in category C, breaks all the quests. (You cant progress in any of the quests anymore)

**To Reproduce**
If you have a "QuestC" in category C and "QuestB" in category B and both quests are locked by requirment: complete quest "QuestA" in category A and you complete the "QuestA" then "QuestC" and "QuestB" (+ all other quests) are not possible to complete. Their progress is simply not growing if you do whatever you want.

So upon completion of QuestA it unlocks QuestB in category B and at the same time QuestC in category C. But it breaks all the quests -> problem is in unlocking quests across multiple categories.

Me personally I have quests: 30 Mining - task type: blockbreakcertain, 20 Killing Mob - task type: mobkillingcertain and 10 Crafting - task type: inventory. All those quests you need to complete in order to unlock Legendary quests in category Legendary and EndGame quest in category EndGame. Once EndGame and Legendary quests are unlocked, it does not count any of its progress if you do any.

**Screenshots**
None

**Server (please complete the following information):**
 - Minecraft Version: 1.16.4
 - Mod Name: Spigot

**Plugin (please complete the following information):**
 - Version: 2.9.5

**Stacktrace**
None

**Comment by LMBishop** [comment]
Could you attach the exact quest files in question? I created three quests, A B and C in seperate categories and had B and C depend on A, but was unable to replicate this bug.

**Comment by KrepelkaCZ** [comment]
Here are all the quests. 
To replicate it complete "Tezeni30" in category "Tezeni" + "Crafting10" in category "Crafting" + "ZabijeniMobu20" in category "ZabijeniMobu". 

Once those 3 quests are done all Legendary quests such as "Legendarni1", "Legendarni2", ... up to "Legendarni10" ("Legendarni9" is an exception for this one you need to complete "Nahranocasu10" in category "Nahranocasu") 
and quest "EndGame" in category "EndGame" will be unlocked.

At this point none of the Legendary quests are gathering progress, same goes for other quests if you have any open.

[quests.zip](https://github.com/LMBishop/Quests/files/5945461/quests.zip)

**Comment by LMBishop** [comment]
I still cannot replicate it after adding your quests, re-creating the categories and marking Tezeni30, Crafting10 and ZabijeniMobu20 as complete. You can see my test below.

https://www.youtube.com/watch?v=Ddc-ItvPAB0

I noticed you mentioned you were running version 2.9.5, this test was done on the latest version of Quests (2.12.1) on a server running Spigot 1.16.5. That could be the probem.

**Comment by KrepelkaCZ** [comment]
I will try out latest version of your plugin + 1.16.5 however I also noticed your quests in the video are started one after another but from my point of view the problem might be that once "Tezeni30" + "Crafting10" + "ZabijeniMobu20" are completed all Legendary quests + that EndGame quest is started so you can progress for all of them at the same time. I have auto-start enabled in the config which you can find also in the zip above. If you want to try again or not. I will try out as I said with the latest version. Thank you very much for your time and effort.

**Comment by LMBishop** [comment]
Ah, enabling auto-start has allowed me to be able to reproduce the bug. Turns out it had nothing to do with auto-start and was just a few simple mistakes. I believe the error is now fixed, you're welcome to try out the devlopment build by downloading it straight from [github](https://github.com/LMBishop/Quests/actions/runs/549536448), or you can wait for the next release version on Spigot.
