### ISSUE TITLE
Repeat-able quests are auto-completed

### ISSUE THREAD

**Issue by KrepelkaCZ** [LMBishop/Quests#147]
**Description of Error**
If you complete a quest that is repeat-able, after the cooldown is off it gets auto-completed

**To Reproduce**
My complete configration of quests, here: [Quests.zip](https://github.com/LMBishop/Quests/files/5975367/Quests.zip)
contains Legendary quests e.g. kill 1 ender dragon. This quest is called "Legendarni1" and has few days cooldown. If you complete it and wait the amount of days and log in again on to the server it auto-completes again.

To unlock any Legendary quests complete "Tezeni30" + "Crafting10" + "ZabijeniMobu20"

**Screenshots**
[if you have any screenshots, show them here]

**Server (please complete the following information):**
 - Minecraft Version: 1.16.4
 - Mod Name: Spigot

**Plugin (please complete the following information):**
 - Version: 2.9.5

**Stacktrace**
None

**Comment by LMBishop** [comment]
That should’ve been fixed in the latest release version of Quests as the progress are now also reset when tasks are completed

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________
