### ISSUE TITLE
Very Strange issue with Edit

### ISSUE THREAD

**Issue by nivcoo** [LMBishop/Quests#148]
https://pics.edensky.fr/2021-02/17/13-19_sRTM.png Hello, can you look the screen the lastest version break brewing, i don't why but maybe because of this edit, so now i need to use the previous version.

**Comment by nivcoo** [comment]
If i analyse the issue, i thing the getOnlinePlayers Contain Entity and not Player instance because look on the top of the screen you can look you put entity here and not player and on the bottom you put player

**Comment by nivcoo** [comment]
https://pics.edensky.fr/2021-02/17/13-27_u2Hz.png Hum it's player, so strange

**Comment by LMBishop** [comment]
I meant to replace that with current.hasMetadata("NPC"), since NPCs from Citizens was firing these events and causing errors within Quests when trying to get the QPlayer

**Comment by nivcoo** [comment]
Same Issue with brewing  :/ in latest version

**Comment by nivcoo** [comment]
https://github.com/LMBishop/Quests/pull/153
