### ISSUE TITLE
I have players that like placing down a ton of emerald ores and then starting the quest. Is it possible to fix this so it doesn't register those ores as natural?

### ISSUE THREAD

**Issue by FourNineRugz** [LMBishop/Quests#149]
**Description of Error**
I have players that like placing down a ton of emerald ores and then starting the quest. Is it possible to fix this so it doesn't register those ores as natural?

I know it works in a sense that if you place down ores AFTER you start the quest, it'll count them negatively. But I hope my initial request is possible.

Purpur version git-Purpur-971 (MC: 1.16.5)

**Comment by LMBishop** [comment]
#78
