### ISSUE TITLE
Shopgui+ purchase task type

### ISSUE THREAD

**Issue by TUCAOEVER** [LMBishop/Quests#150]
**Description of Feature**
Add support for shopgui+
Whenever some player bought specific type of item or items provided from mmoitems(supported by shopgui+)etc.

**Alternative Methods**
As far as i know, none.

**Additional Information**
[anything not listed above, such as screenshots etc.]

**Comment by LMBishop** [comment]
I have added it, although note that I don't have ShopGUI+ to test it so it might not work
