### ISSUE TITLE
Could not pass MythicMobsDeathEvent to Quest

### ISSUE THREAD

**Issue by Texboobcat** [LMBishop/Quests#151]
**Description of Error**
Could not pass event MythicMobDeathEvent to Quests v2.14.1

**To Reproduce**
I was not doing anything it was just spamming the console

**Screenshots**
[if you have any screenshots, show them here]

**Server (please complete the following information):**
 - Minecraft Version: 1.16.5
 - Mod Name: purpur build 980

**Plugin (please complete the following information):**
 - Version: 2.14.1
 - Mystical Mobs Version 4.11

**Stacktrace**
https://paste.md-5.net/sulugabiqi.pl

**Comment by LMBishop** [comment]
Do you have citizens installed?

**Comment by Texboobcat** [comment]
Yes I do have citizens
