### ISSUE TITLE
Random Quests

### ISSUE THREAD

**Issue by JxckH** [LMBishop/Quests#154]
**Description of Feature**
For random quests add a limit where you have to complete that quest given first before given another one as I have had so many people spam the console with it and is not what I want the plugin to do.

**Alternative Methods**
Npc cooldown but that only works for when you run the command so not really what I want.

**Comment by LMBishop** [comment]
Why not just set the limit for the maximum number of started quests in the config?

**Comment by JxckH** [comment]
Don't see that in my config so can you please just add it for me. Thanks Bud

**Comment by LMBishop** [comment]
It's under options called `quest-started-limit`. Direct link: https://github.com/LMBishop/Quests/blob/master/src/main/resources/config.yml#L172

**Comment by JxckH** [comment]
I am still able to spam the random command and get a new quest when I set it to 1 in the config

**Comment by LMBishop** [comment]
Cannot reproduce, ensure you have reloaded the config using /q a reload.

**Comment by JxckH** [comment]
Yes
