### ISSUE TITLE
More GUI customisation

### ISSUE THREAD

**Issue by Akira13345** [LMBishop/Quests#160]
~~1 / Be able to modify the gui of the / q command~~
~~-  For example, add windows as decoration~~
 

 ![annexe1](https://user-images.githubusercontent.com/60575816/114574825-e14fa080-9c79-11eb-8993-8f8a51a0bc20.PNG)

~~-  Modify the row~~
~~-  Put a slot for the quest category~~
-  Add commands to the item (in my case which redirects to /menu)

*  Add this in the quest categories menu 

2/ Be able to modify the name of the gui of each category created
- The quests-menu defined for each category

~~2/ MySQL~~
~~- Add mysql support?~~
~~It would be really convenient~~

**Comment by LMBishop** [comment]
You should see #50 for my response to MySQL.

It is possible to customize the Quests GUI already, see the wiki https://github.com/LMBishop/Quests/wiki/Custom-GUI-Items. I have modified your issue to reflect what is already possible.

**Comment by Akira13345** [comment]
I had not seen this change "for the mistletoe" the same for MySQL support 
Thank you for your understanding

I close the Issue ?

**Comment by LMBishop** [comment]
You can leave it open as there are still a couple of suggestions there
