### ISSUE TITLE
Recent Quests Became Bugged, Won't Load

### ISSUE THREAD

**Issue by Foxersthe** [LMBishop/Quests#161]
**Description of Error**
Most recent quests became bugged and won't show up in quest list even though it's in the quests.yml

**To Reproduce**
The quests I tried worked, but after setting a quest requirement and trying them out later the first quest disappeared from the quest list. I tried to check on the other quests but they disappeared as well. It's still in the quests.yml, but the errors suggest something is wrong with it. I found an error for the lang files and I did as it said which was to regenerate the string file. I also updated the plugin from a previous version but I can't remember what exactly it was. I think it was rather recent though according to the version number. Only the most recently made quests are affected.

**Screenshots**
[if you have any screenshots, show them here]

**Server (please complete the following information):**
 - Minecraft Version: 1.16.5
 - Mod Name: Spigot

**Plugin (please complete the following information):**
 - Version: 4.0.2.

**Stacktrace**
[please see your console if there is a long error when the bug occours, if there is one present, please paste it here]
[04:38:12] [Craft Scheduler Thread - 6/WARN]: [Quests] Unable to load custom objectives because quest for custom7 was null
[04:38:12] [Craft Scheduler Thread - 6/WARN]: [Quests] Unable to load custom objectives because quest for custom12 was null
[04:38:12] [Craft Scheduler Thread - 6/WARN]: [Quests] Unable to load custom objectives because quest for custom13 was null

Here is the quests pastebin for the affected quests:
`https://pastebin.com/fTAjUaNd`
(Still new to pastebin.)

**Comment by LMBishop** [comment]
Wrong plugin 😛
