### ISSUE TITLE
Is check-coreprotect working?

### ISSUE THREAD

**Issue by Disorbs** [LMBishop/Quests#162]
**Description of Error**
It seems core protect check is not working for BlockBreakCertain and still counts newly placed wheat as a unique block.

**To Reproduce**
simply add this and be on a 1.16.5 server with quest and coreprotect and place wheat and then do the quest and break the freshly placed wheat and it will count.

>   harvest:
>     type: "blockbreakcertain"
>     check-coreprotect: true
>     check-coreprotect-time: 3600
>     amount: 50
>     block: "WHEAT"

**Server (please complete the following information):**
 - Minecraft Version: 1.16.5
 - Mod Name: Paper

**Plugin (please complete the following information):**
 - Version: 2.16.3
 - CoreProtect: 19.5

**Stacktrace**
No error or stack trace.

**Comment by LMBishop** [comment]
It seems like there is a delay in which coreprotect logs each change, meaning instant break blocks or actions in gamemode creative may slip through. I'm not sure of a solution to this.

**Comment by IdeaD3** [comment]
> It seems like there is a delay in which coreprotect logs each change, meaning instant break blocks or actions in gamemode creative may slip through. I'm not sure of a solution to this.

Do you know what the delay on coreprotect is? I waited 30 seconds & it still counts it as progression (1.18)

**Comment by LMBishop** [comment]
The delay in my experience is in the millisecond range, if it is over a few seconds then it is safe to say the check failed.
