### ISSUE TITLE
Command for item data & multiple names in mobkillingcertain task

### ISSUE THREAD

**Issue by 4L0N50asd** [LMBishop/Quests#164]
Some ideas:
- Add a command (`/q admin item`) which sends to you a message (or creates a new file) with the necessary data you need to set in a quest file, if it includes something about checking items, for example `inventory` task, npc-interact. So people doesn't need to ask every time for support about how to set an item or which things needs to set up. (I suggested this on Discord but i write here again so it is not forgotten)

~~- Add a customizable config section for `category item display` and `task item display` where it allows to put HideFlags and Enchantments (Reason for HideFlags: It's a bit annoying to see the damage and attack speed for weapons and tools)~~

- Allow to set up more than 1 name for task `mobkillingcertain` so these mobs can count for this task without having to set up different tasks for each different name.*[1]
- Add an option for task `mobkillingcertain` called **ContainsName:** so you can choose between setting up exact `name/list of names`, or a word which is in the name of a mob*[2]

*[1] Example:
  `task: "mobkillingcertain"`
  `amount: 10`
  `name:`
  `- "&6Inferno"`
  `- "&bDalek"`
  `.................`

*[2] Uses: Cases where you have custom creepers named "`&7Big Red &aCreeper Lvl 1`", "`&7Little Red &aCreeper Lvl 2`", "`&7Invisible Red &aCreeper lvl 3`". So you just need to set up this in the task:
  `ContainsName: "Red &aCreeper"`
Then all the Creepers you kill named like that, would count to complete the task, because their names contains "Red Creeper" Obviusly, this option would mean you can't put "`Name`" and "`ContainsName`" in the same task

**Comment by LMBishop** [comment]
> Add a customizable config section for category item display and task item display where it allows to put HideFlags and Enchantments (Reason for HideFlags: It's a bit annoying to see the damage and attack speed for weapons and tools)

As for this, you can add `itemflags:` to the display item which accepts anything [here](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/ItemFlag.html)

e.g
```yaml
display:
  name: "some name"
  lore:
   - "some lore"
  itemflags:
   - "HIDE_ATTRIBUTES"
```
