### ISSUE TITLE
Hello plantations problem

### ISSUE THREAD

**Issue by Chrqmated** [LMBishop/Quests#166]
Hello i have tasks:  
tasks:
  harvest:
    type: "blockbreakcertain"
    amount: 128
    block: "NETHER_STALK"

But the block "nether_stalk" no't working i search block : WHEAT, NETHER_STALK, BEETROOT, CARROT and POTATO (full growht)

**Comment by Chrqmated** [comment]
UP

**Comment by LMBishop** [comment]
NETHER_WART ?

**Comment by Chrqmated** [comment]
> NETHER_WART ?

no't working
