### ISSUE TITLE
Missing world validation in blockbreakcertain task type

### ISSUE THREAD

**Issue by WolverStones** [LMBishop/Quests#169]
If I want the quest to work only in a certain world, how do I do it? 

Because depending on what I have currently set up more gist github it doesn't work

https://gist.github.com/WolverStones/865a1b867a61d404a21c73de78393992

**Comment by LMBishop** [comment]
That should work and only allow the task to progress in a certain world.

**Comment by WolverStones** [comment]
> 
> 
> That should work and only allow the task to progress in a certain world.

Of course, but when I tried. So despite the fact that I have set it there that it should only work in the world, it works in any world.
