### ISSUE TITLE
Task and Reward

### ISSUE THREAD

**Issue by Barriol** [LMBishop/Quests#17]
Hello,

I love your pluggin and I want to use it but there is few features that I will love you to add to be better than a certain "Advanced Achievements" pluggin ;) After that I will use it all alone with no more achievements pluggins !

##  TASK TYPES TO ADD
- Craft X items
- Enchant X items
- Distance travelled with Elytra
- Potions brewed (optionnal)
- items smelt (optionnal)

## REWARD TYPES : 
- Max health
- Max oxygen

What do you think ?
Thanks !

**Comment by Krakenied** [comment]
All these task types has already been implemented, should be closed

`Craft X items` - crafting
`Enchant X items` - enchanting
`Distance travelled with Elytra` - walking with elytra mode
`Potions brewed (optionnal)` - brewing
`items smelt (optionnal)` - smelting

@LMBishop
