### ISSUE TITLE
Command tasks not working for all commands

### ISSUE THREAD

**Issue by ImBas** [LMBishop/Quests#170]
**Description of Error**
Command tasks do not work for DeluxeMenus or BoosCooldowns commands.

**To Reproduce**
Create a DeluxeMenu and assign an open_command to it, for example 'warp'
Create a Quest with the task type 'Command' and require the command 'warp'
Using /warp does not trigger the quest

Same results for BoosCooldowns aliases

**Server:**
Tuinity 1.16.5

**Plugin:**
2.16.5

**Comment by ImBas** [comment]
Any update for this? Hoping to get a fix soon, some of our quests are unavailable if this doesn't work.
If you need any more information please let me know.

**Comment by LMBishop** [comment]
I do not have time to look into it now, but it seems like either plugin does not fire the PlayerCommandPreprocessEvent, or cancels it, so that Quests does not get the event

**Comment by ImBas** [comment]
That is very likely. Is there any alternative method available to check command usage?

**Comment by LMBishop** [comment]
Haven't tested it, but it may work now
