### ISSUE TITLE
Quest track does not work

### ISSUE THREAD

**Issue by LuuckA21** [LMBishop/Quests#173]
Quest track does not work when quest-autostart is true

Running: Paper-721

**Comment by LMBishop** [comment]
Can you elaborate? I can still track quests when that option is enabled

**Comment by LuuckA21** [comment]
I use a scoreboard but when I use auto truck and auto start scoreboard does not update, if I do not use auto start scoreboard works fine

**Comment by LMBishop** [comment]
Auto track only works when the player starts a quest themselves. For auto start quests, the player should choose which quest to track themselves.

**Comment by LuuckA21** [comment]
Ok, because I set quest menu only to show the current quest (auto started) and I create sequential quest, player make quest one per time
