### ISSUE TITLE
Auto Update Check always returns new version

### ISSUE THREAD

**Issue by Whitescan** [LMBishop/Quests#189]
### Description of Bug

I got version 3.1.1 installed (currently the latest version)

Update Checker tells me that v3.1 is out and asks me to downgrade. 

### Steps to Reproduce

1. Install version 3.1.1 (currently latest)
2. Login with notification permission
3. Check the chat

### Environment

```markdown
- Minecraft version: 1.16.5
- Server software: Tunity
- Quests version: 3.1.1
```

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other
Screenshot: https://prnt.sc/16nqmej
_No response_

**Comment by LMBishop** [comment]
This is a problem with Spigot caching the version string and won't clear for about 12 hours past an update. The message will eventually go away, there's nothing I can do about it.

**Comment by LMBishop** [comment]
Resolved in latest version
