### ISSUE TITLE
Inventory task currently not functional (or not implemented in beta?)

### ISSUE THREAD

**Issue by huangrkul** [LMBishop/Quests#19]
**Description of Error**
Having quest items in inventory does not show up in progression.  Having more than enough quest items does not complete quest objective.  (the quest in general won't register the items I have in inventory)
**To Reproduce**
The specific setting I used is this:

      novicestep1:
        type: "inventory"
        item: 388
        amount: 32
        remove-items-when-complete: true

The 388(emeralds) are not registered when I have them in the inventory.

**Screenshots**
[if you have any screenshots, show them here]

**Server (please complete the following information):**
 - Minecraft Version: 1.12.2
 - Mod Name: Spigot 
CraftBukkit version git-Spigot-2086bb0-d0a3620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Plugin (please complete the following information):**
 - Version: Quests v2.0.10-beta

**Stacktrace**
There is no error in console.

**Comment by fatpigsarefat** [comment]
Try the name 'EMERALD' instead.

**Comment by huangrkul** [comment]
Yep tried that.  Didn't register.  In fact, I tried various items (both ID # and bukkit ID Names in uppercase) and none of them is registering.

Thanks for looking into it.

**Comment by Barriol** [comment]
It's a bug. You have to drop an item then take it and it will "refresh" the quest and it will be complete. But it's not triggered when you take items from a chest.

**Comment by PixilChic** [comment]
Hi, I have the same issue. And yes I have tried your solution you mentioned above, to drop the item and then take it. It still doesn't register in the inventory. I have tried this with cooked fish, and tried both the ID cooked_fish, COOKED_FISH,  and the number ID. I have tried different gamemodes too to see if that makes a difference. Nothing is working for inventory quests.
