### ISSUE TITLE
Toggleable cancel menu

### ISSUE THREAD

**Issue by mattisadev** [LMBishop/Quests#199]
### Reason for Addition

I think other server owners would benefit from being able to toggle the cancel menu because it allows players to have a more convenient experience.

### Description of Feature

I would like the cancel menu to be toggleable through the config.

### Alternative Solutions

Unless this option is added, there is no other way to achieve the same outcome.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
Not entirely sure what is meant by "toggleable cancel menu". Quests already provides a way to disable it altogether 

https://github.com/LMBishop/Quests/blob/master/bukkit/src/main/resources/resources/bukkit/config.yml#L192

**Comment by mattisadev** [comment]
> Not entirely sure what is meant by "toggleable cancel menu". Quests already provides a way to disable it altogether
> 
> https://github.com/LMBishop/Quests/blob/master/bukkit/src/main/resources/resources/bukkit/config.yml#L192

I mean that the player can still cancel the quest but when they right-click, the menu that comes up would be toggleable.
