### ISSUE TITLE
Suggestion: Bossbar

### ISSUE THREAD

**Issue by AlternativeSoap** [LMBishop/Quests#206]
### Description of Feature

It could be nice with bossbar, actionbar, title progression instead of scoreboard.
Whenever I want to track a quest it should show a bossbar or an actionbar for that quest. 

### Alternative Solutions

I don't know which others solutions I should use.

### Agreements

- [x] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
Doesn't seem within the scope of quests, considering Quests doesn't offer a scoreboard either, rather placeholders for other plugins to use

I am sure there are bossbar plugins which can utilize the [placeholders](https://github.com/LMBishop/Quests/wiki/PlaceholderAPI) which Quests offers

**Comment by AlternativeSoap** [comment]
I don't think so.

It should only show whenever I start a Quest. Every plugin I see is constant. Like scoreboard. But every other Quest plugin can do that. Quests is just better to use therefore I'm asking for that feature.
But if you got ideas show me :)

**Comment by yraliya** [comment]
I also lack the built-in bossbar function, I have configured the display of the current quest via the TAB plugin, but I want the highest priority quest to be displayed in the location where the player is located.

**Comment by TizoCraft** [comment]
adding a bossbar to quests would be great!

**Comment by mitchngwen** [comment]
Yes, Please add it and I would be willing to pay for the plugin.
