### ISSUE TITLE
Big bug for crop type quest

### ISSUE THREAD

**Issue by zReport02** [LMBishop/Quests#207]
### Description of Bug

I encountered a big problem in the plugin!
The farm type quests, where for example it is required to destroy 50 pieces of wheat .. can be easily bypassed ..
Can you add the ability to select a block age?
Blocks of like wheat, carrots, potatoes etc. have an age, it would be useful to be able to control it

### Steps to Reproduce

Create a quest like this:

miningstone:
  type: "blockbreakcertain"
  amount: 10
  block: WHEAT
  
  
  Start this quest and place/break the wheat...

### Environment

- Minecraft version: 1.17.1
- Server software: Paper 1.17.1
- Quests version: 3.4

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

Pls, fix this problem!
It's a big big big problem for survival servers

**Comment by LMBishop** [comment]
This isn't necessarily a bug as the task is working as intended, though it is true that Quests has no way to differentiate between crop states at the minute
