### ISSUE TITLE
WHEAT cant complete

### ISSUE THREAD

**Issue by blank826** [LMBishop/Quests#209]
### Description of Bug

When i break the WHEAT ,the quest cant complete.

miningstone:
    type: "blockbreakcertain"
    amount: 6                          
    block: WHEAT                      
    worlds:                              
     - "world"

### Steps to Reproduce

When i break 6 WHEAT,the quest not complete.
But i change WHEAT to carrot,i can complete it.

### Environment

- Minecraft version: 1.12.2
- Server software: 
- Quests version: 3.5

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Please use the correct item names for your version. https://helpch.at/docs/1.12.2/index.html?org/bukkit/Material.html

**Comment by blank826** [comment]
I use the right item name.The WHEAT is right.I want use farm task type.But my mc version is 1.12.2.So i use blockbreakcertain type.

**Comment by LMBishop** [comment]
the block is called CROPS in 1.12
