### ISSUE TITLE
Dup of extracted resources

### ISSUE THREAD

**Issue by widify-test** [LMBishop/Quests#210]
### Reason for Addition

It is impossible to constantly monitor the players as they spend resources by breaking the same block

### Description of Feature

For example: A player can dig up one block of gold ore and put and break it with a pickaxe, thereby there is a dup of Quests. I think it is necessary to add a check for the delivered block, if he put it, then the broken block is not counted

### Alternative Solutions

I don't see an alternative solution :)

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
Quests already offers solutions to this. See the countermeasures described in the wiki https://github.com/LMBishop/Quests/wiki/Task-Configuration-Layout#blockbreakcertain

`reverse-if-broken`  
`check-coreprotect`
