### ISSUE TITLE
check-core-protect doesn't work

### ISSUE THREAD

**Issue by FourNineRugz** [LMBishop/Quests#211]
### Description of Bug

I placed a bunch of emerald blocks prior to doing a quest but it still registers it as part of the mined blocks

![image](https://user-images.githubusercontent.com/17154368/126249845-5922793f-55f7-4396-a697-6b877831c5af.png)

![image](https://user-images.githubusercontent.com/17154368/126249875-ad0c9f9c-64eb-467d-98e3-3c9e8f1450be.png)

![image](https://user-images.githubusercontent.com/17154368/126249901-88cfc8c6-132a-4b7d-9955-941a7d75512a.png)

### Steps to Reproduce

I placed a bunch of emerald blocks prior to doing a quest but it still registers it as part of the mined blocks

![image](https://user-images.githubusercontent.com/17154368/126249845-5922793f-55f7-4396-a697-6b877831c5af.png)

![image](https://user-images.githubusercontent.com/17154368/126249875-ad0c9f9c-64eb-467d-98e3-3c9e8f1450be.png)

![image](https://user-images.githubusercontent.com/17154368/126249901-88cfc8c6-132a-4b7d-9955-941a7d75512a.png)

### Environment

- Minecraft version:
- Server software:
- Quests version:

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Ensure that you have coreprotect installed, also there is a slight delay with coreprotect logging, so instabreaking blocks right after being placed might cause unexpected behaviour

**Comment by FourNineRugz** [comment]
> Ensure that you have coreprotect installed, also there is a slight delay with coreprotect logging, so instabreaking blocks right after being placed might cause unexpected behaviour

I waited a few minutes before starting the quest and mining. It still registers the emerald ore blocks. Even when I do /co i and inspect the block it'll say i've placed the block

**Comment by LMBishop** [comment]
I still can't seem to replicate it using CoreProtect version 20, it usually only takes a few hundred milliseconds for CoreProtect to finish logging block changes
