### ISSUE TITLE
PAPI Expansion not working

### ISSUE THREAD

**Issue by PapaWulf-Lunar** [LMBishop/Quests#213]
### Description of Bug

No clue, but as long as I have the quests expansions installed with /papi ecloud. It will cause my entire PAPI plugin to break until it's be reloaded without the "expansion-quests"

### Steps to Reproduce

have my life
https://mclo.gs/sAd4v2I

### Environment

- Minecraft version: 1.8.9
- Server software: Ubuntu, java 8
- Quests version: 3.5.2

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

my console log
https://mclo.gs/4BOZeW8

**Comment by LMBishop** [comment]
Please read the wiki, do NOT install the ecloud expansion, it is for a different plugin.
