### ISSUE TITLE
GPS API Hook

### ISSUE THREAD

**Issue by lucian929** [LMBishop/Quests#214]
### Reason for Addition

I think that a hook with the GPS API would be great because for many players, quests are confusing. This hook would let players see where they need to go.

### Description of Feature

https://www.spigotmc.org/resources/gps-1-9-1-17-global-positioning-system-for-your-server.53672/ Very simple. Just needs to have a hook with this API so that it can get the locations set in the quests config. I'm sorry I don't have a better example for this, but I think it's pretty simple, just scroll to the bottom of that spigot page.

### Alternative Solutions

Asking my developer to do it

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
Do you have the correct plugin? Quests don't generally have locations

**Comment by lucian929** [comment]
Ah yeah, sorry. Should provide some more context:

Could be used for:

- Citizens Deliver / Interact task

- Position task

Likely more at some point, assuming more tasks are implemented in the future.

I guess it might not make sense to implement for only 1-2 tasks, so if not I'll let my dev take care of it for my server :)

**Comment by qwer2415wy** [comment]
Maybe check out my idea (https://github.com/LMBishop/Quests/issues/216#issuecomment-886390375)
This will be highly customized.
