### ISSUE TITLE
PlaceholderAPI doesn't work

### ISSUE THREAD

**Issue by qwer2415wy** [LMBishop/Quests#217]
### Description of Bug

I am already turn on quests-use-placeholderapi in config.yml.
Then I use
```
"rewardstring:
  - "&a小波&7» &f%player_name% 你好! 我現在要帶你認識伺服器."
```
This is what happen in game:
![image](https://user-images.githubusercontent.com/70427269/127093705-86a02c73-8769-47cf-b0d6-58067c581b9b.png)
Doesn't change it

I had use command check my placeholder
![image](https://user-images.githubusercontent.com/70427269/127093785-1a10ce4e-ccd2-4d4a-af13-e8ad43cdce7e.png)

### Steps to Reproduce

1. Use %player_name% in quest rewardstring.
2. Set "quests-use-placeholderapi: true"
3. Restart server
4. Check the result

### Environment

- Minecraft version: 1.16.5
- Server software: Paper
- Quests version: 3.6.1

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by TUCAOEVER** [comment]
+1

**Comment by DuneSciFye** [comment]
I can confirm as well
