### ISSUE TITLE
Suggestion: About Delay message

### ISSUE THREAD

**Issue by Lewis2333** [LMBishop/Quests#218]
### Description of Feature

Hello! Can you add an NPC conversation function? Just like right clicking NPC to send a message (it is better to support delay message). Thank you!

### Alternative Solutions

Suggestion: About Delay message

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
Duplicate of #35
