### ISSUE TITLE
MMOItems compatibility.

### ISSUE THREAD

**Issue by Keopsfenks** [LMBishop/Quests#221]
### Reason for Addition

There are nearly 3,000 users through Spigot.

I think by bringing compatibility to this plugin, you can make many users prefer you.

Why I want it: The "item-certain" system works, but when we change the item name, the line, sometimes it's forgotten through quest, and I want to avoid it.

### Description of Feature

Mmoitems compatibility for the plug-in task system. 

Example: Citizens_Deliver

Original:

```
beef:
  type: "citizens_deliver"
  npc-name: "Gerald"                    # name of NPC
  item:                                 # SPECIFIC item with name and lore
    name: "&cSpecial Beef"
    type: "RAW_BEEF"
    lore:
     - "&7This is a special type of beef"
  amount: 8                             # amount of item needed
  remove-items-when-complete: false     # (OPTIONAL) take the items away from the player on completion - default: false
  worlds:                               # (OPTIONAL) restrict to certain worlds
   - "world"

```
MMOItems
```
beef:
  type: "citizens_deliver"
  npc-name: "Gerald"                    # name of NPC
  mmoitem:                                 # SPECIFIC item with name and lore
    type: MATERIAL
    id: "BLOOD"
  amount: 8                             # amount of item needed
  remove-items-when-complete: false     # (OPTIONAL) take the items away from the player on completion - default: false
  worlds:                               # (OPTIONAL) restrict to certain worlds
   - "world"

```

### Alternative Solutions

Why I want it: The "item-certain" system works, but when we change the item name, the line, sometimes it's forgotten through quest, and I want to avoid it.

### Agreements

- [X] I am running the latest version of Quests
- [x] I am certain this issue is unique and a similar issue is not currently open

**Comment by Keopsfenks** [comment]
Will mmoitems and random category command come in the next update?

**Comment by LMBishop** [comment]
The random category has already been implemented

**Comment by Keopsfenks** [comment]
> The random category has already been implemented
Yes, I've noticed that I hope mmoitems support will come as soon as possible.
You're loved.

**Comment by LMBishop** [comment]
An alternative to this problem is to use the new item importing system, detailed [here](https://github.com/LMBishop/Quests/wiki/Defining-items#quest-items)

**Comment by Keopsfenks** [comment]
> An alternative to this problem is to use the new item importing system, detailed [here](https://github.com/LMBishop/Quests/wiki/Defining-items#quest-items)

Yes, I've noticed. I'm going to use this until Mmoitems backup arrives.

**Comment by LMBishop** [comment]
This has been updated to `stats: blocked` because MMOItems does not provide a public repository for their plugin. The minimum thing needed to be included in Quests is to at least have API wrappers public, however as it stands MMOItems does not do this. 

I do not know when this can be implemented.

**Comment by Keopsfenks** [comment]
https://git.lumine.io/mythiccraft/mmoitems/-/wikis/Stat%20API

https://git.lumine.io/mythiccraft/mmoitems/-/wikis/Main%20API%20Features

I understood. I thought it could be done with the apis here.
