### ISSUE TITLE
Error with Tasks and PLAYER_HEAD in 1.16

### ISSUE THREAD

**Issue by FrancescoJacovo** [LMBishop/Quests#225]
### Description of Bug

Hello, Using it I noticed that the "inventory" feature does not detect "PLAYER_HEAD" with a custom skin, but only the default one with name or lore changed.

Ex .:
if I set the mission as follows
tasks:
forge:
type: "inventory"
item:
name: "&aHello"
type: "PLAYER_HEAD"
amount: 1

If I'll rename the head "&aHello" without changing its skin the plugn will detect the object in the inventory, but if I'll set the skin it will not be detected. (Also it not works adding with owner-name/uuid/base64)

Could you fix this with an upcoming update? I really love this plugin, it's super useful for our network. Thanks in advance!

### Steps to Reproduce

Hello, Using it I noticed that the "inventory" feature does not detect "PLAYER_HEAD" with a custom skin, but only the default one with name or lore changed.

Ex .:
if I set the mission as follows
tasks:
forge:
type: "inventory"
item:
name: "&aHello"
type: "PLAYER_HEAD"
amount: 1

If I'll rename the head "&aHello" without changing its skin the plugn will detect the object in the inventory, but if I'll set the skin it will not be detected. (Also it not works adding with owner-name/uuid/base64)

Could you fix this with an upcoming update? I really love this plugin, it's super useful for our network. Thanks in advance!

### Environment

- Minecraft version: 1.16.3
- Server software: PaperSpigot
- Quests version: 3.5.2

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Are you not adding a name? I think the plugin is requiring a name from you and that might be causing the issue

**Comment by FrancescoJacovo** [comment]
i tried with name, uuid and base64. nothing!

**Comment by LMBishop** [comment]
I gathered but are you also specifying a display name or not

**Comment by FrancescoJacovo** [comment]
I renamed an Head with "&aHello" and set my Skin "PabloTN"

this is the current configuration:

tasks:
  forge:
    type: "inventory"
    item: 
     name: "&aHello"
     type: "PLAYER_HEAD"
     owner-username: "PabloTN"
    amount: 1
display:
  name: "Quest 1"
  lore-normal:
    - "not working"
  lore-started:
  type: "CRAFTING_TABLE"
rewards:
  - "give {player} diamond 10"
options:
  category: "impossible"
  repeatable: true
  cooldown:
    enabled: false
    time: 0
  sort-order: 42


When i pickup the head from the ground the quest doesn't complete. But if i set a generic player head (without name, skin etc) it will work.

**Comment by FrancescoJacovo** [comment]
when i set a skin to a skull the plugin doesn't detect as a head
