### ISSUE TITLE
LAVA_BUCKET placement quest?

### ISSUE THREAD

**Issue by ClickErrorxD** [LMBishop/Quests#226]
### Description of Bug

Lava bucket isn't considered a block, but when used for a build such as a **cobblestone generator**, it's considered placing it.
I'm trying to use this in the _blockplacecertain_ task, but it's not counting it as a placement.

### Steps to Reproduce

Setup the _blockplacecertain_ task, enter LAVA_BUCKET. Reload the plugin, start the quest to place a lava bucket, it won't register, not even in the progress update spot of the lore.

### Environment

- Minecraft version: paper spigot 1.16.5
- Server software: Uhm, paper spigot?
- Quests version: 3.6.2

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
I don't think this counts as placing blocks under bukkit thus might need a new type of task

**Comment by ClickErrorxD** [comment]
> I don't think this counts as placing blocks under bukkit thus might need a new type of task

That'd be amazing!
