### ISSUE TITLE
PlaceholderAPI support

### ISSUE THREAD

**Issue by LMBishop** [LMBishop/Quests#23]
**Description of Feature**
PlaceholderAPI support.
For example: %quest_current%

**Alternative Methods**
n/a

**Additional Information**
n/a

**Comment by AbelMG** [comment]
Example: %quests_completedtasks_(quest id)%
If you have 1 or more than 1 tasks, it's going to tell you how much tasks had you completed.
%quests_completedtasks_(quest id)%/5 = 2/5 (for example) if you've completed 2 tasks of that quest

Example: %quests_(task name)_progress_(quest id)% will tell you your progress in a task in a quest, for example: 13/25 blocks of dirt

**Comment by snakeeEyesEC** [comment]
when will you add it?

**Comment by snakeeEyesEC** [comment]
When will you add it?
