### ISSUE TITLE
Placeholder API not working in quest GUI

### ISSUE THREAD

**Issue by LuluxClient** [LMBishop/Quests#230]
### Description of Bug

The placeholders from papi in the quest GUI is not working https://i.imgur.com/3eMCRWe.png

### Steps to Reproduce

Add this in GUI creation: 
    40:   
      display:
        name: " "
        lore: 
        - "&6Nombre de quêtes: &d%quests_all%"
        - "&eTest: &d%quests_category:examples_all%"
        - "%quests_all_cache%"
        type: "REDSTONE_TORCH_ON"
      repeat: 0  
      
      

### Environment

- Minecraft version: 1.8.8
- Server software: TacoSpigot
- Quests version: 3.6.2

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

I'm using the placeholders from the plugin and not from another one and doing /papi parse me %quests_all% is giving me the correct answer

**Comment by DuneSciFye** [comment]
I'm also having this issue, previously it was with a the GamePoints plugin, the placeholder wasn't working in the quests special elements item, but the Quests plugin updated saying they fixed it. The problem still occurred so I thought it was the GamePoints plugin. I asked for a while and everyone told me GamePoints did indeed have placeholder support, leaving me to think something was just broken with GamePoints. So I switched to Tokens, but the same issue occurred, placeholder isn't working

**Comment by LMBishop** [comment]
Did you turn placeholder support on?

**Comment by DuneSciFye** [comment]
Yes

**Comment by DuneSciFye** [comment]
![image](https://user-images.githubusercontent.com/65089425/128385343-20e7ba8b-68ce-4e0e-abae-bce220cdf833.png)

**Comment by LMBishop** [comment]
Still unable to replicate on a fresh install, testing with both the Player and Server placeholder expansions in both the GUI and in reward strings.

**Comment by LuluxClient** [comment]
> Still unable to replicate on a fresh install, testing with both the Player and Server placeholder expansions in both the GUI and in reward strings.

I'm using 1.8.8 and i'm using latest papi.

**Comment by DuneSciFye** [comment]
I'm using 1.17 and latest version of purpur, papi, and Quests

**Comment by LuluxClient** [comment]
Still not fixed on latest update
