### ISSUE TITLE
add placeholder support math

### ISSUE THREAD

**Issue by bithuc** [LMBishop/Quests#231]
### Reason for Addition

.

### Description of Feature

Suggestions:
-add placeholder support https://api.extendedclip.com/expansions/math/ to Task Configuration
... then I can increase the number of items required when you level up or a certain condition. I can reduce 1000 quests of increasing difficulty with this placeholderapi alone.
ex:
building:
type: "blockplace"
amount: '%math_20+2*{player_exp}%'
worlds:
- "world"

### Alternative Solutions

.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

### Other

.

**Comment by LMBishop** [comment]
This seems rather resource intensive to continously evaluate placeholders. I could make it an option at some point in the future however I'm not certain this would work as well as you would hope it would.
