### ISSUE TITLE
Not counting when breaking wheat in server 1.8

### ISSUE THREAD

**Issue by marc099** [LMBishop/Quests#238]
### Description of Bug

my config:
tasks:
  blockbreakcertain:
    type: "blockbreakcertain"
    amount: 64
    block: WHEAT
display:
   name: "&c&lAgricultura: &f#1"
   lore-normal:
   - "&8Misiones Agrarias"
   - ""
   - "&2● &cObjetivo: &fRecoge x64 de Trigo&f."
   - "&2● &cRecompensa: &a2,450 ⛃"
   - "&2● &cProgreso: &f{blockbreakcertain:progress}/64 de Trigo&f."
   - ""
   lore-started:
   - "&aHas comenzado el reto."
   type: "WHEAT"
rewards:
  - "eco give {player} 2450"
options:
  category: "farming"
  # Unlike the previous quest, this quest has "example1" as a required quest. You cannot start this quest without "example1" quest complete.
  requires: []
  repeatable: false
  cooldown:
    enabled: true
    time: 1440
  # The sort order has been changed so this quest will appear after in the GUI
  sort-order: 1

### Steps to Reproduce

Not counting when breaking wheat in server 1.8

### Environment

- Minecraft version: 1.8
- Server software: 1.8
- Quests version: 3.8

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Please use the correct material list for your server version: https://github.com/LMBishop/Quests/wiki/Task-configuration-layout#blockbreakcertain

**Comment by marc099** [comment]
Wheat ID comes out there and if I put the ID 59 it doesn't take it either

**Comment by LMBishop** [comment]
Wheat is the held item, CROPS is the actual block in 1.8

**Comment by marc099** [comment]
What id do I put on?

**Comment by marc099** [comment]
bad support

**Comment by LMBishop** [comment]
It's literally been 2 hours and I already told you what the issue is. If you can read then you would not be having this problem. 

![](https://i.imgur.com/9hNpJh5.png)

Please get a grip rather than getting mad at voulenteers who maintain an open source project for free.
