### ISSUE TITLE
[Bug] Saplings `reverse-if-broken` not working

### ISSUE THREAD

**Issue by MrPranklez** [LMBishop/Quests#239]
### Description of Bug

When adding the `reverse-if-broken` flag to a blockplacecertain task with some type of sapling, it will not reverse any progress if the specified sapling is broken while the quest is active.

### Steps to Reproduce

Create a quest with a blockplacecertain with any type of sapling. Place a sapling and destroy it again, progress should be 0, but it will remain at 1.

### Environment

- Minecraft version: 1.17.1
- Server software: Purpur (latest build)
- Quests version: latest (3.9)

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by MrPranklez** [comment]
The saplings dont appear to reg8ster correctly. If you define oak sapling specifically and have another quest with birch sapling, both quests will progress no matter what sapling you place

**Comment by Krakenied** [comment]
Fixed in https://github.com/LMBishop/Quests/commit/ad8cbad7cc90531922f5d68b8be621d18b2b1b3b

**Comment by Krakenied** [comment]
@LMBishop can be closed ^
