### ISSUE TITLE
PlaceholderAPI evaluation Quests not updating their progress

### ISSUE THREAD

**Issue by KhrysAK47** [LMBishop/Quests#240]
### Description of Bug

The bug consists of the following, in the PAPI eval Quest types, if you progress in them (gain a value as a example), the progress does not update, this happens with numeric placeholders.

### Steps to Reproduce

1) Create a quest that requires you to have 10 of specific placeholder, (I tried it with Vault - %vault_eco_balance_fixed%, and yes I am aware that there is a specific task type for money, it's just that is easier for me to test the placeholder values since I can modify my balance easier), but the point is the same, it happens with any integer/numeric placeholders.
2) Define a progress for the Quest like you would do with other task types.
3) Check your progress for the Quest.
4) Earn the currency or progress into the quest.
5) Check your progress for the Quest again.

Result should be same, the progress for the quest staying the same until completed.

### Environment

- Minecraft version: 1.16.5
- Server software: PaperSpigot 1.16.5
- Quests version: Latest available to date

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

My quest config is this one: https://pastebin.com/7Edha8zU

**Comment by LMBishop** [comment]
What's the output of `%vault_eco_balance_fixed%` when using papi parse?

**Comment by KhrysAK47** [comment]
> What's the output of `%vault_eco_balance_fixed%` when using papi parse?

At first 0, then I gave myself 1 and by parsing it it says 1, but the progress still didn't update.

**Comment by KhrysAK47** [comment]
But this doesn't only happen with Vault, I used vault as a example, the same thing happens to all the numeric placeholders.

**Comment by LMBishop** [comment]
I remember now, the placeholder tasks did not set any task progress originally because numeric comparisons was only a feature later added to Quests (and it wouldn't have made sense to set task progress if it wasn't numeric). I can make it so if a placeholder is numeric then it will set the task progress in the next update.

**Comment by KhrysAK47** [comment]
Would be very useful, thank you very much!

**Comment by KhrysAK47** [comment]
> I remember now, the placeholder tasks did not set any task progress originally because numeric comparisons was only a feature later added to Quests (and it wouldn't have made sense to set task progress if it wasn't numeric). I can make it so if a placeholder is numeric then it will set the task progress in the next update.

I would like to reopen this issue with another error, in this case this was fixed in the latest update, but now it seems that unconditionally of what numeric placeholder you use, it always uses decimals, for example: 0.0/10, instead of 0/10.

**Comment by LMBishop** [comment]
Should be opened as a new issue
