### ISSUE TITLE
Players can cheat

### ISSUE THREAD

**Issue by Foxiar** [LMBishop/Quests#245]
### Description of Bug

Players can easily cheat. They just can block and break the same block and they get points for it.

For example, the Player has a quest to break and place 10 grass blocks. He will break the grass block and place it again and again and again until he completes the quest.

### Steps to Reproduce

Check for every broken a placed block and do not count them for the second time.

### Environment

- Minecraft version: Newest (1.17.1)
- Server software: PaperMC
- Quests version: Newest (at 24.8)

### Agreements

- [x] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Not a bug. Please read the wiki.
