### ISSUE TITLE
Allow the use of placeholder for custom GUI items.

### ISSUE THREAD

**Issue by dm1lk** [LMBishop/Quests#246]
### Reason for Addition

Useful for statistics, etc.

### Description of Feature

Allow the use of placeholder api placeholders within the custom GUI items, as currently using placeholders does not work.

### Alternative Solutions

I cannot use placeholders, I tried multiple ways of defining the placeholder.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by dm1lk** [comment]
## Example Below
![Screenshot 2021-08-28 001913](https://user-images.githubusercontent.com/77703500/131197460-f0d8304d-f26b-4e3a-ad34-c777a69ba6f6.png)

**Comment by LMBishop** [comment]
Should work as long as it is turned on in the config
