### ISSUE TITLE
Accurate Farming tracking

### ISSUE THREAD

**Issue by Tombspyder** [LMBishop/Quests#247]
### Reason for Addition

Currently the farming and blockbreak task types do not allow for accurate tracking of sugar cane and presumably (untested) cactus, whilst the inventory can be used quests that require large amounts of sugar-cane can not be processed this way.

This addition would allow farming style quests to be more accura

### Description of Feature

Add a task-type or update the farming-certain type to include sugar cane and cactus that is broken via the block underneath being destroyed.

An integration with aureliumskills or other skill plugins that add extra farming drops would also be a nice addition to the farming-certain task.

### Alternative Solutions

I have tried using inventory, farming, farming-certain and blockbreakcertain 

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by Disorbs** [comment]
i will see if more are bugged but also
`sugar_cane
cactus
bamboo`

**Comment by Tombspyder** [comment]
> i will see if more are bugged but also
> `sugar_cane cactus bamboo`

Any of the crops that aren't directly broken by a player cause this:

Sugar_cane, Cactus, bamboo, kelp and even glowberries i'm pretty sure
