### ISSUE TITLE
Lored items not being recognized as part of inventory quest.

### ISSUE THREAD

**Issue by KhrysAK47** [LMBishop/Quests#249]
### Description of Bug

Lored items not being recognized as part of inventory quest.

### Steps to Reproduce

1) Have a quest related to crafting or inventory set up, here is my config: https://pastebin.com/YiAcAABS
2) Start the quest
3) Give yourself a workbench lored &f&lCOMMON (if you have essentials: /i crafting_table 1 lore:&f&lCOMMON)
4) You will see it doesn't work.

### Environment

- Minecraft version: 1.16.5 
- Server software: PaperSpigot
- Quests version: Latest available up to date

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Try importing it as a quest item, this is likely because it doesn't have a display name

**Comment by KhrysAK47** [comment]
> Try importing it as a quest item, this is likely because it doesn't have a display name

The wiki regarding this is unclear, https://github.com/LMBishop/Quests/wiki/Defining-items, do you mind giving me a example of a inventory quest type that requires for example the custom item with name of 'test'? Because when I do it using the wiki it always has errors.

**Comment by KhrysAK47** [comment]
https://pastebin.com/qt9gUhdk
