### ISSUE TITLE
If no lore set up, apply to all lored items (inventory type quest)

### ISSUE THREAD

**Issue by KhrysAK47** [LMBishop/Quests#250]
### Reason for Addition

Since there are issues with the plugin recognizing lores properly on quest / task types such as inventory or crafting, add so if we don't have a lore option set up in them, it applies to all (included lored items), so its easier, for example:

 quest:
  type: "inventory"
  item: CRAFTING_TABLE
  amount: 1

This would apply to ALL crafting tables, including lored ones.

### Description of Feature

Listed above.

### Alternative Solutions

Fix the recognition of the task types and lored items.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
This should already be the case if only a material is defined
