### ISSUE TITLE
Player head with Base64 skin in the quest type

### ISSUE THREAD

**Issue by exzolink** [LMBishop/Quests#252]
### Description of Feature

Possibility to set player head with base64 code in the quest type

### Alternative Solutions

-

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
Should already work, see the wiki https://github.com/LMBishop/Quests/wiki/Defining-items#defining-items

**Comment by exzolink** [comment]
> 
> 
> Should already work, see the wiki https://github.com/LMBishop/Quests/wiki/Defining-items#defining-items

I mean use custom heads like quest icon

**Comment by LMBishop** [comment]
Still not sure what you mean, you can have custom heads as a quest icon as Quests uses the same format for defining items everywhere

**Comment by exzolink** [comment]
How i can define custom quest icon? There is only for quest items (https://github.com/LMBishop/Quests/wiki/Defining-items#defining-items)

**Comment by LMBishop** [comment]
It applies everywhere in Quests
> Every configured ItemStack in Quests is parsed the exact same way.

**Comment by exzolink** [comment]
I tried different options, but a stone is always shown instead of an icon

**Comment by LMBishop** [comment]
STONE is only shown if you write an invalid material

**Comment by exzolink** [comment]
Can you write example, please? I using from wiki, but its not working

**Comment by LMBishop** [comment]
something like

```yaml
display:
  name: "Quest 1"
  type: "PLAYER_HEAD"
  owner-base64: "..."
  lore-normal:
    ...
```
or "SKULL_ITEM" pre-1.13

**Comment by exzolink** [comment]
Oh, thank you
