### ISSUE TITLE
Placeholder request.

### ISSUE THREAD

**Issue by Keopsfenks** [LMBishop/Quests#253]
### Reason for Addition

Hi, I'd like to add one placeholder, and I hope it comes.

%quests_tracked_CATEGORY%

Applies to all track placeholders.

The other one is. 

![image](https://user-images.githubusercontent.com/51726168/132009378-076d65a6-84d4-406f-ad82-aeba24e23d35.png)
I'd like to edit this article.

Some missions have two or three placeholders, some have one. With 300 close missions, it's boring to create guis for them one by one. I did it using a tracked placeholder, but when I add a placeholder that doesn't exist, it gives me an error.

### Description of Feature

.

### Alternative Solutions

.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by Keopsfenks** [comment]
Applies to all track placeholders.

**Comment by LMBishop** [comment]
what should `%quests_tracked_CATEGORY%` return?

also that invalid placeholder message is customisable
