### ISSUE TITLE
[Suggestion] Ability to hide attributes in display items in the GUI and allow multiline quests description

### ISSUE THREAD

**Issue by Catches** [LMBishop/Quests#256]
### Reason for Addition

Basically what the title says. I have asked on Discord, and apparently it's not possible to use hide attributes in display items in the Quests GUI. Also multiline would be appreciated, so it doesn't fill up the scoreboard. For example using "/n"

### Description of Feature

Basically what the title says. I have asked on Discord, and apparently it's not possible to use hide attributes in display items in the Quests GUI. Also multiline would be appreciated, so it doesn't fill up the scoreboard. For example using "/n"

### Alternative Solutions

None

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
Not sure what you mean by the following
> Also multiline would be appreciated, so it doesn't fill up the scoreboard. For example using "/n"

but I can make the item flags customisable

**Comment by Catches** [comment]
@LMBishop
![image](https://user-images.githubusercontent.com/81335077/132612116-9bcee1d0-dbc6-4480-8cac-f07bd00b8efb.png)
The usage of /n

**Comment by LMBishop** [comment]
This isn't really a quests issue to solve, whatever is in that string will be exported as the placeholder, meaning the onus is on your scoreboard plugin to parse the newline and split the scoreboard line up.

**Comment by Catches** [comment]
@LMBishop
Sorry, I'm a bit confused. So are you saying that you support the use of multilines or \n in here
![image](https://user-images.githubusercontent.com/81335077/132789759-8f61cc50-4bd7-43a3-b6c1-343df291665c.png)
Could you test it to make sure? Like specifically on whatever scoreboard plugin you're using.

**Comment by LMBishop** [comment]
Essentially, Quests cannot solve this problem, your scoreboard plugin has to.

Placeholders return only a `String`, you can include a newline character in your config but that won't mean anything unless your scoreboard plugin actually parses that and inserts a new scoreboard line. It is impossible for Quests to return anything other than a single string, so your scoreboard plugin must interpret the newline.
