### ISSUE TITLE
autostart: true not working correctly

### ISSUE THREAD

**Issue by Nesseley** [LMBishop/Quests#260]
### Description of Bug

It seems autostart doesn't start it correctly/completely. 
The player will autostart the quest like you would assume, and the stats starts getting tracked.

Problem is:
1) You can rightclick to cancel, and it will tell you "You have not started this quest."

2) You can leftclick and start it again, which resets your progression.

Then you can right and left click to stop and start the quest as many times you want.

3) It also doesnt send the titlemessage with quest started when it starts the quest

### Steps to Reproduce

set autostart: true on the quest and it should do as stated above

### Environment

- Minecraft version: 1.17.1
- Server software:  Paper version git-Paper-135 (MC: 1.17.1)
- Quests version: Quests version 3.9

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

Maybe autostarted quests also shouldn't be able to be cancelled?

**Comment by LMBishop** [comment]
Is this the quest-specific autostart or the global autostart?

**Comment by Nesseley** [comment]
It's the one you put in each quest file, under options:
