### ISSUE TITLE
list of quests that do not seem to work

### ISSUE THREAD

**Issue by Devillion** [LMBishop/Quests#27]
**Description of Error**
These quests do not seem to work, does not show progress when trying to complete them.

**To Reproduce**
Just paste the quests into your config and try them: https://pastebin.com/ft9kyiW3

**Screenshots**
none

**Server (please complete the following information):**
 - Spigot 1.12.2
 - Spigot

**Plugin (please complete the following information):**
 - I downloaded the quest jar on 8-22-2018 from spigot website

**Stacktrace**
There are no errors in the config when trying to complete them

**Comment by xion87** [comment]
having the same issue, paperspigot 1.12.2, when it gonna to be fixed? :|
