### ISSUE TITLE
Quests 4.0.7 Deliver to NPC 

### ISSUE THREAD

**Issue by comradeflats** [LMBishop/Quests#273]
### Description of Bug

I set up my quest and when it came to deliver the item to the NPC, I get the message "CodX3 is not required item for this quest! The difference is 'display name or lore'. 

I tried it again in 4.0.6 and it worked fine, so I'm assuming there's something wrong in 4.0.7. Hope to see it fixed soon! 

![Uploading Screen Shot 2021-09-12 at 7.56.00 PM.png…]()

### Steps to Reproduce

As stated, I recreated the same steps in 4.0.6 and it worked fine. I also tried different items in 4.0.7 and those also saw the deliver function not working. 

### Environment

- Minecraft version: 1.17.1
- Server software: PaperMC #259
- Quests version: 4.0.7

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Wrong plugin
