### ISSUE TITLE
expearn decimal issue

### ISSUE THREAD

**Issue by Nesseley** [LMBishop/Quests#276]
### Description of Bug

When using expearn as a task, it shows way to many decimals.

https://gyazo.com/a53e47d29e46e216b4aea45b477b590d

### Steps to Reproduce

Set EXPearn, earn exp, see decimals deluxe

### Environment

- Minecraft version: 1.17.1
- Server software: Paper version git-Paper-135 (MC: 1.17.1)
- Quests version: Quests version 3.9

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Will add rounding option for display
