### ISSUE TITLE
2 citizen interact tasks in 1 quest doesn't work

### ISSUE THREAD

**Issue by WitherVictor** [LMBishop/Quests#277]
### Description of Bug

I try to make a quest that need players to interact with all the NPCs in the town to finish the quest, but it doesn't work.
Though it works fine when only has 1 citizen interact task.
I tried to put 2 npc-name in 1 task but it will become OR condition which means interact with one of the NPCs in the list will complete the quest. That's not what I want to design.

### Steps to Reproduce

copy the code blocks from wiki and paste them in the .yml, 1 works fine but 2 can't.

### Environment

- Minecraft version: 1.16.5
- Server software: paper spigot
- Quests version: 3.9.1

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
you need to set up multiple tasks

**Comment by LMBishop** [comment]
Was fixed in df222745d02e26a0605fcf6191a0d16001d15c69
