### ISSUE TITLE
EntityDeathEvent Error

### ISSUE THREAD

**Issue by Iamlivvv** [LMBishop/Quests#279]
### Description of Bug

[DsR3ESMZ.txt](https://github.com/LMBishop/Quests/files/7184856/DsR3ESMZ.txt)

### Steps to Reproduce

You just need to have a Mythic Mobs Mission. If you kill any Boss, the error will appear.

### Environment

- Minecraft version: 1.16.5
- Server software: Paper
- Quests version: v4.0.7

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Wrong plugin
