### ISSUE TITLE
Quest tracking removes after rejoining

### ISSUE THREAD

**Issue by KhrysAK47** [LMBishop/Quests#281]
### Description of Bug

The bug / issue is simple, if you start a quest, and rejoin the server, it will display as you have no quest tracked whatsoever even if it's the only quest you have started / tracking.

### Steps to Reproduce

Start any quest (even default ones)
See the placeholder for tracked quest.
Rejoin.
See the placeholder for tracked quest once again.

### Environment

- Minecraft version: 1.16.5
- Server software: PaperSpigot
- Quests version: Latest

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

A temporary solution would be to add a /q a moddata randomtrack (player) so console can track a random active quest of the player.

**Comment by KhrysAK47** [comment]
Any news?

**Comment by SalomonPicos** [comment]
I have the same problem... It's so annoying
