### ISSUE TITLE
"location" task type doesn't work

### ISSUE THREAD

**Issue by HysteriaMC** [LMBishop/Quests#284]
### Description of Bug

the "location" task type doesn't work at all, it's impossible to complete the quest

### Steps to Reproduce

1. Add a "location" quest task
2. Attempt to travel to said location

### Environment

- Minecraft version: 1.16.5
- Server software: Bungeecord-Bootstrap:1.17-R0.1-SNAPSHOT
- Quests version: Latest (3.9.1)

### Agreements

- [x] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Did you include a padding? If not then you have to be at the exact co-ordinates, which is effectively impossible
