### ISSUE TITLE
name for mobkillingcertain doesnt work

### ISSUE THREAD

**Issue by Nesseley** [LMBishop/Quests#285]
### Description of Bug

I used the https://github.com/LMBishop/Quests/wiki/Task-Configuration-Layout#mobkillingcertain and tried to define name "Zombert" for a zombie, didn't have to name the mob at all to get the kill. 

### Steps to Reproduce

- Set quest to mobkillingcertain with name defined.
- Kill mob without name
- Still gets the kill in the quest

### Environment

Minecraft version: 1.17.1
Server software: Paper version git-Paper-135 (MC: 1.17.1)
Quests version: Quests version 3.9

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by 4L0N50asd** [comment]
Happened to me too

**Comment by LMBishop** [comment]
https://github.com/LMBishop/Quests/blob/f74bd0802c0d3be754995b5cb785dad8169d01a3/bukkit/src/main/java/com/leonardobishop/quests/bukkit/tasktype/type/MobkillingCertainTaskType.java#L106

it would appear that this should be `&&`

**Comment by Nesseley** [comment]
I'm not sure what you mean by that
