### ISSUE TITLE
 iridiumskyblock_value - not work

### ISSUE THREAD

**Issue by Eur0x** [LMBishop/Quests#286]
### Description of Bug

 for "iridiumskyblock_value" everything can be seen in the picture, even in the files it does not detect the task because there is an error

### Steps to Reproduce

iridiumskyblock:
  type: "iridiumskyblock_value"
  value: 20  
  
  
![image](https://user-images.githubusercontent.com/64858671/135573748-71c7b4f2-c26e-42e3-a1fd-1ad6e11368bd.png)

### Environment

- Minecraft version: 1.17.1
- Server software: Paper-236
- Quests version:  3.9.1

### Agreements

- [X] I am running the latest version of Quests
- [x] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Eur0x** [comment]
> What version or IridiumSkyblock are you using?

Iridium Skyblock [1.13-1.17] 3.1.1 (latest)

**Comment by LMBishop** [comment]
See #181 - waiting for the IridiumSkyblock API to make this possible

The `iridiumskyblock_value` won't enable if you're not using 2.x
