### ISSUE TITLE
Task type: Consume doesn't work

### ISSUE THREAD

**Issue by fra130701** [LMBishop/Quests#287]
### Description of Bug

title

### Steps to Reproduce

https://hastebin.com/fefocetona.less
This is my configuration

### Environment

- Minecraft version: 1.12.2
- Server software: Linux
- Quests version: 3.9.1

### Agreements

- [X] I am running the latest version of Quests
- [x] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Nesseley** [comment]
Remove the " in front and back of GOLDEN_APPLE, does it work then?
