### ISSUE TITLE
Cancelcommands

### ISSUE THREAD

**Issue by Existqq** [LMBishop/Quests#288]
### Description of Feature

I want you to add cancelcommands! I need to change the scoreboard with permission, I can do this with the command at starting the quest and the command at reward, but when a person cancels the quest, his permission does not change, and the scoreboard does not look the way I want. Thanks in advance.

startcommands:
  - "broadcast {player} has started a quest"
  
I need:
cancelcommands:
  - "broadcast {player} has started a quest"

### Alternative Solutions

Ive wrote all above

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by Krakenied** [comment]
@LMBishop can be closed - added in 3.15
