### ISSUE TITLE
Permission Task Type not working!

### ISSUE THREAD

**Issue by Nesseley** [LMBishop/Quests#289]
### Description of Bug

I cannot get the permission task type to work, I really need it!

### Steps to Reproduce

Set task type to permission and it doesn't recognize that I have the perm. 

### Environment

- Minecraft version: 1.17.1 
- Server software: Paper version git-Paper-257 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8a2b23a)
- Quests version:  3.9.1

Ekstra:
- Luckperms:  5.3.47

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Is this issue still ongoing? The code looks fine
