### ISSUE TITLE
(Nu)Votifier vote task type

### ISSUE THREAD

**Issue by Nesseley** [LMBishop/Quests#299]
### Description of Bug

![image](https://user-images.githubusercontent.com/11998470/142759946-f1c6e021-61ce-49f5-a810-59843fb2090d.png)
```
tasks:
  vote:
    type: "votingplugin_vote"
    amount: 3
```

### Steps to Reproduce

Try to use voting task, doesn't work at all.

### Environment

Minecraft version: 1.17.1
Server software: Paper version git-Paper-257 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8a2b23a)
Quests version: 3.9.1

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Can you check `/q a types` for `votingplugin_vote`? The plugin searches for another plugin called `"VotingPlugin"` before registering that task type

**Comment by Nesseley** [comment]
Tells me Task type 'votingplugin_vote' does not exist.

I am using Votifier and CMI as my voting plugins.

**Comment by LMBishop** [comment]
Changed to enchancement, this task type is specific to the "VotingPlugin" plugin requested in #228.

**Comment by Nesseley** [comment]
Did you forget to add the "nuvotifier_vote" to https://github.com/LMBishop/Quests/wiki/Task-types ? It seems to me that you added the task type, but forgot to update the wiki? :)

**Comment by Nesseley** [comment]
however, using the tasktype `nuvotifier_vote` doesn't work, so I guess not? Gives error "Task type `nuvotifier_vote` does not exist"
