### ISSUE TITLE
Mmoitems items do not work

### ISSUE THREAD

**Issue by Leonardo-shitp** [LMBishop/Quests#304]
### Description of Bug

I wanted to create a 'crafting' type mission that requires crafting a certain MMOITEMS item but every time I crafting the required item it doesn't count.

quest:

mmoitem1:
  type: "crafting"
  item:
    quest-item: "mmoitem-carrot"
  amount: 5

### Steps to Reproduce

I do not have error tests since the plugin itself does not throw an error in the console, simply when I craft the item it does not tell me about it in the target

### Environment

- Minecraft version: 1.17.1
- Server software: Paper
- Quests version: 3.9.2

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
How have you defined the mmo item?
