### ISSUE TITLE
Custom Guis 

### ISSUE THREAD

**Issue by Canecorso00** [LMBishop/Quests#305]
### Description of Feature

Can you add possibility to create CustomGuis per pages? Now I can only make custom gui on every category but on only first page, I can't make it on second page. You can add option like page: 1/2/3/4 etc per category to create customguis.

### Alternative Solutions

Can you add possibility to create CustomGuis per pages? Now I can only make custom gui on every category but on only first page, I can't make it on second page. You can add option like page: 1/2/3/4 etc per category to create customguis.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
You should be able to. The slots on other pages should be offset by 45 (since the navbar takes up the bottom row), so for example to put an item on the fifth slot of the second page the slot is 49.
