### ISSUE TITLE
Permission-required: true line doesnt seem to work?

### ISSUE THREAD

**Issue by FourNineRugz** [LMBishop/Quests#306]
### Description of Bug

  brewing:
    display:
      name: '&e&lBrewing Quests'
      lore:
        - "&7Click to view this category"
        - "&r"
        - "&eDescription:"
        - "&e&l* &7In this category you can find"
        - "&e&l* &7quests related to &ebrewing&7 in which you"
        - '&e&l* &7have to &7&nbrew&7 certain potions.'
        - "&r"
        - "&eOptions:"
        - "&e&l* &7There are currently &a&n%quests_category:brewing_all% quests&7 in this category."
        - "&e&l* &7The level of difficulty its ranged from: &aEasy &7to &eMedium"
        - "&e&l* &7Number of quests completed in this category: &e%quests_category:brewing_completed%"        
        - "&r"
        - "&eRewards:"
        - "&e&l* &7Reward type: &a&nMoney"
        - "&e&l* &7Rewards between: &a&l$&a250 &7to &e&l$&e1500"
        - ""
        - "&e&l* &7Started quests from this category: &7&n%quests_category:brewing_started%"        
      type: "BREWING_STAND"
      permission-required: false 

Not sure if I have this correct but i'm still able to access categories even if i have permissions on them.

### Steps to Reproduce

See above.

### Environment

- Minecraft version:
- Server software:
- Quests version:

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by FourNineRugz** [comment]
I used LuckPerms

**Comment by LMBishop** [comment]
>  permission-required: false
This has no effect
