### ISSUE TITLE
ShopGUI task type 

### ISSUE THREAD

**Issue by 0liverGMC** [LMBishop/Quests#307]
### Description of Bug

Using the sell more GUI of ShopGUI when a player does not even have the correct amount of the items to sell i.e 0 wheat for this case it will add it to the quest progress, GUI Link - https://i.mineadia.com/bPQJtAHfqY.png. 

### Steps to Reproduce

ShopGUI+, anything sellable, clicking on the sell more option in the ShopGUI+ with an inventory that does not contain the item selling.

### Environment

- Minecraft version: 1.17.1
- Server software: Pufferfish version git-Pufferfish-19 (MC: 1.17.1)
- Quests version: v3.9.2

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
Fixed in https://github.com/LMBishop/Quests/pull/498
