### ISSUE TITLE
Excusme developer

### ISSUE THREAD

**Issue by Fumio-26** [LMBishop/Quests#309]
### Type of Change

Add new information

### Description of Change

Hi Developer, you can add some spesification of taming animals?
i need for quests

### Page Markup

```true
Please :)
```

**Comment by LMBishop** [comment]
What information is missing?

**Comment by Fumio-26** [comment]
I want to make some new quest, but the quest is spesification taming animals

**Comment by LMBishop** [comment]
The information for that is available here: https://github.com/LMBishop/Quests/wiki/Task-configuration-layout#taming
