### ISSUE TITLE
THİS PLUGİN NOT SUPPORT SLABS

### ISSUE THREAD

**Issue by kurkinsnetwork** [LMBishop/Quests#314]
### Reason for Addition

https://prnt.sc/26wi473

### Description of Feature

s

### Alternative Solutions

s

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
Please open a new issue with the form correctly filled out.
