### ISSUE TITLE
Dupe bug on number of item craft

### ISSUE THREAD

**Issue by amarcais53** [LMBishop/Quests#317]
### Description of Bug

As you can see one the video i can finish a quest where i need to craft 100 anvil with only crafting 2 anvil if i want , check the video until the end since im showing how the bug is hapenning
https://www.youtube.com/watch?v=Wf98jD7U3Mk&feature=youtu.be

### Steps to Reproduce

take 64 irons and 64 iron block , create a anvil crafting quests , add everything on the crafting table and instead of clicking to craft the item do CTRL + your drop key on the item

### Environment

- Minecraft version:
- Server software:
- Quests version:
pufferfish 1.17.1 with a 1.18 client using viaversion
Quests v3.9.2

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by amarcais53** [comment]
@LMBishop when did the update will come out

**Comment by LMBishop** [comment]
It will be released to Spigot when it's all tested and other features are ready, but you can download the development builds from GitHub

**Comment by Krakenied** [comment]
It does not event need to press ctrl lmao

**Comment by Krakenied** [comment]
Apparently they changed it in 1.21.2 lol
