### ISSUE TITLE
Support mythicmobs

### ISSUE THREAD

**Issue by izimen** [LMBishop/Quests#318]
### Description of Bug

When I kill a monster, there is an error with the mythicmobs plugin, most likely it is the fault of the old version of the mythicmobs plugin I am using, but I have to use it because I am use version 1.12.2 and it is the most compatible with that version.

https://pastebin.com/6w4JkzjH

I wonder if you would be able to do something about it?

### Steps to Reproduce

Just kill the monster spawn by the mythicmobs plugin

### Environment

- Minecraft version: 1.12.2
- Server software: PaperSpigot
- Quests version: 3.9.2
- MythicMobs version: 4.5.8-2586

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by izimen** [comment]
I understand that low priority, but well already 2 weeks pass and I would even be satisfied with the option to disable in the configuration mythicmobs support as you can not fix this bug, with every killed mob I have an error on the console, this is a very big spam, so you should understand me that I need this

**Comment by LMBishop** [comment]
You can already disable task types. Please see the wiki.

https://github.com/LMBishop/Quests/wiki/Basic-options#Task-type-exclusions
