### ISSUE TITLE
PlaceholderApi not working correctly

### ISSUE THREAD

**Issue by JohnnyX071** [LMBishop/Quests#323]
### Description of Bug

I tried to use the PlaceholderApi: %quests_started_list% on my scoreboard while quest auto start was on and it didn't work but when it is false it does.

### Steps to Reproduce

- Go to config and enable quest auto start
- Use the %quests_started_list% on any scoreboard plugin
- Nothing will be disabled while If I disable quest auto start it works correctly

### Environment

- Minecraft version: 1.18.1
- Server software: purpur 1.18.1 latest
- Quests version: 3.10

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by JohnnyX071** [comment]
Why was this closed. Is this getting fixed?

**Comment by LMBishop** [comment]
> Why was this closed. Is this getting fixed?

https://github.com/LMBishop/Quests/commit/f61b8a7343f0dac47a4b93e185c0e05053ee4eb2
