### ISSUE TITLE
HOW TO ADD CUSTOM MİNECRAFT PLAYER HEADS İN QUESTS FİLE

### ISSUE THREAD

**Issue by kurkinsnetwork** [LMBishop/Quests#325]
### Type of Change

Add new information

### Description of Change

https://prnt.sc/xuNMrZDpXSsO how to add custom player heads

### Page Markup

```true
https://prnt.sc/xuNMrZDpXSsO how to add custom player heads
```

**Comment by LMBishop** [comment]
This is not a documentation request.
