### ISSUE TITLE
Cancel all pending quests in 1 command

### ISSUE THREAD

**Issue by Monjiigames** [LMBishop/Quests#329]
### Description of Bug

Hello,

Is there a command to cancel all pending quests in one go? This is to support players playing on the bedrock client

### Steps to Reproduce

N/A

### Environment

- Minecraft version: 1.17
- Server software: 1.17
- Quests version: Latest

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

N/A

**Comment by LMBishop** [comment]
Changed to feature request

**Comment by LMBishop** [comment]
(was already fixed in c38c4218fda2dc4f05107b1ce6f0f458dc988530)
