### ISSUE TITLE
Add an option to use custom command with Categories section

### ISSUE THREAD

**Issue by iskandarluqman** [LMBishop/Quests#33]
**Description of Feature**
Each time you do /quest , it will shows you the categories. I would like an option to add a back button which will open a DM menu. So if I would like to be able to add custom command so I can achieve this. Example as below.

**Additional Information**
https://imgur.com/a/crIJ6bD

**Comment by fatpigsarefat** [comment]
While I don't think this would fit the nature of Quests, I will still leave it open.
