### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by Strahilchu** [LMBishop/Quests#332]
### Reason for Addition

Players would like a Quests leaderboard as they compete to have the most quests completed.

### Description of Feature

There is a placeholder for seeing how many quests a player has completed, and how many there are total.
But there is no leaderboard.

This feature would add /QTop or /Quests Leaderboard or /Quests Top (doesn't matter which)
and display a list of at least the top 10 players with the most quests completed.

I have 1,300 Quests on my server and I'm sure many others have a lot too and this would be a very good feature to have.

### Alternative Solutions

I could not find a solution but I know it's possible to pull the "quests completed" number and display it.
This feature would just need to store and order said numbers and update when player joins or completes a quest, whichever works best.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

### Other

I had a plugin made for Vanilla Advancements Leaderboard and it worked.
There are placeholders that show how many a player has completed and it was relatively simple to implement a leaderboard for it.

When player joins, pull "Quests completed" and add it to database, /qTop to display leaderboard.

**Comment by LMBishop** [comment]
A similar issue is already open: #204
