### ISSUE TITLE
Better visibility on quest-locked-display

### ISSUE THREAD

**Issue by Nesseley** [LMBishop/Quests#334]
### Reason for Addition

Make things easier and more visible for players.

### Description of Feature

Right now it will only display you need to complete Quest1 + 1 other quest. It makes more sense to display all of them so they can choose what order they want to complete them in.

### Alternative Solutions

"You need to complete Quest1, Quest2, Quest3 to unlock this quest" or something alike. Could also do a list, but that would become very long if you have many quests you need to complete to unlock it.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
This is already a configurable option, since another person wanted the exact opposite of what you wanted.

https://github.com/LMBishop/Quests/wiki/Basic-options#GUI-truncate-requirements

**Comment by Nesseley** [comment]
> This is already a configurable option, since another person wanted the exact opposite of what you wanted.
> 
> https://github.com/LMBishop/Quests/wiki/Basic-options#GUI-truncate-requirements

ah! Amazing! I tried finding it on the wiki for 10 minutes but couldn't! Thanks :)
