### ISSUE TITLE
completing the number of tasks  and playtime and return the item

### ISSUE THREAD

**Issue by SzlugPL** [LMBishop/Quests#335]
### Type of Change

Add new information

### Description of Change

Hello. Can you create categories "completed tasks?"
#
Can I add hours or days to the Game Time quest? because I can see that it is only in minutes.
#
Is it possible to create the task "return the item" takes from the inventory

sorry for typos, translated by translator

**Comment by LMBishop** [comment]
I'm not sure what you want. Please open an issue with the correct template (you have used a documentation template which is invalid) and describe the feature you want added in detail.
