### ISSUE TITLE
Add placeholder how many people how completed the quest

### ISSUE THREAD

**Issue by UnitedCraft** [LMBishop/Quests#338]
### Reason for Addition

It would be good if players could see how many players have already done this quest in a given quest in a placeholder.

### Description of Feature

It will show how many players completed certain quest

### Alternative Solutions

Dont have

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
Comes under #204
