### ISSUE TITLE
Console spam error

### ISSUE THREAD

**Issue by Mick43** [LMBishop/Quests#34]
**Description of Error**
Hello, I just noticed that last night the console was spam error but I do not know what caused it ... an idea?
Thank you

**Server (please complete the following information):**
 - Minecraft Version: 1.13.1
 - Spigot MC: 1.13.1

**Plugin (please complete the following information):**
 - Version: 2.0.14-beta

**Stacktrace**
https://pastebin.com/9UmiMEc8

**Comment by fatpigsarefat** [comment]
Do you know if any of your players try to join the server before it has fully initialized? If you do, knowing this would be great. Thanks!

**Comment by Mick43** [comment]
No, the server had been online for some time before the console started to repeat the errors.
