### ISSUE TITLE
CrazyCrates Plugin Support

### ISSUE THREAD

**Issue by Bossimal** [LMBishop/Quests#342]
### Reason for Addition

CrazyCrates doesn't have a placeholder that stores/returns the amount of crates the player has opened so there is no way to use the "placeholderapi_evaluate" 

### Description of Feature

Hi, I was wondering if you could add support for the plugin CrazyCrates so we can make quests for opening crates. 

**Example Quests:**
Open X amount of crates - Open a certain amount of crate keys (With a modifier to make opening certain crates not count towards progression)
Open X amount of Y crates - Open a certain amount of <Crate Name> Keys

### Alternative Solutions

I wasn't able to come up with any alternatives solutions except for asking the CrazyCrates dev to add a placeholder that stores the amount of crates a player has opened

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

### Other

**CrazyCrates Info**
Spigot - https://www.spigotmc.org/resources/crazy-crates.17599/
Source Code / Wiki - https://github.com/Crazy-Crew/Crazy-Crates

**Comment by LMBishop** [comment]
CrazyCrates repo is broken

**Comment by Bossimal** [comment]
Oh okay, its all good. I appreciate you trying
