### ISSUE TITLE
"Glide" Task Request

### ISSUE THREAD

**Issue by Bossimal** [LMBishop/Quests#345]
### Reason for Addition

Im trying to create a Quest that will track how many blocks a player has glided with an Elytra (In a specific world)

### Description of Feature

A Quest for how many blocks a player has glided with an Elytra (In a certain world)

### Alternative Solutions

N/A

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by Nesseley** [comment]
I've already reported this here: https://github.com/LMBishop/Quests/issues/340

**Comment by Bossimal** [comment]
My bad. I didn't see it when I was looking through to make sure I didn't post a duplicate request. Do you want me to remove this one?

**Comment by Nesseley** [comment]
No worries :)
