### ISSUE TITLE
Support the new MythicMobs API

### ISSUE THREAD

**Issue by Momshroom** [LMBishop/Quests#350]
### Description of Bug

On load, the plugin gives this error: `[16:14:23 ERROR]: [Quests] Plugin Quests v3.10.1 has failed to register events for class com.leonardobishop.quests.bukkit.tasktype.type.dependent.MythicMobsKi
llingType because io/lumine/xikage/mythicmobs/api/bukkit/events/MythicMobDeathEvent does not exist.`

### Steps to Reproduce

Start the server with Quests v3.10.1 and a recent mythic mobs version.

### Environment

- Minecraft version: 1.18.2
- Server software: Paper version git-Paper-268 
- Quests version: 3.10.1

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

I'm using MythicMobs-5.0.3-SNAPSHOT (build 4073)

MythicMobs recently made major changes to their API, which is what I am assuming is causing this issue.   
I know it's new and am not expecting an immediate change, I just wanted to make sure you were aware and I didn't see another issue for it.  

Thanks for all your work on this plugin!

**Comment by Keopsfenks** [comment]
I agree, but the mm v5 version is still in beta. He might be fine if he comes now, but you can wait for him to come out of beta. Maybe then he'll bring support.

**Comment by LMBishop** [comment]
Will implement whenever it's out of beta. Supporting this early version will probably break it for those not using the early build of MythicMobs.
