### ISSUE TITLE
PLACEHOLDER API NOT WORK

### ISSUE THREAD

**Issue by kurkinsnetwork** [LMBishop/Quests#353]
### Description of Bug

expansion-quest not good work 1.17.1 pls fix it

### Steps to Reproduce

expansion-quest not good work 1.17.1 pls fix it

### Environment

- Minecraft version: 1.17.1
- Server software: airplane
- Quests version: 3.10.1

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Azakaturan** [comment]
I also had to get rid of the Quests expansion placeholders as it was causing PAPI to not load any expansions automatically.

![image](https://user-images.githubusercontent.com/79327162/161402173-dd19d9f2-ef23-42c2-bc42-6ef0d72436ef.png)

**Comment by LMBishop** [comment]
Please read the wiki before opening issues. More specifically the bit in bold at the very top, written that way so it should be impossible to miss.

https://github.com/LMBishop/Quests/wiki/PlaceholderAPI
