### ISSUE TITLE
Break Block

### ISSUE THREAD

**Issue by benzkungx10** [LMBishop/Quests#356]
### Description of Bug

Place blocks before accepting block mining quests

### Steps to Reproduce

1.Placeblock
2.Accept quest
3.Break Block
4.Quest Finish

### Environment

- Minecraft version: 1.18.2
- Server software: Linux
- Quests version: 3.10.1

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Nesseley** [comment]
Can't you use the check-coreprotect option to fix this?

**Comment by benzkungx10** [comment]
Thank You i'm trying coreprotect <3
