### ISSUE TITLE
Quests GUI issue

### ISSUE THREAD

**Issue by Halfhand1** [lmbishop/Quests#36]
**Description of Error**
Whenever I try to cancel a quest the GUI shows up but it looks like the blocks are messed up and the permissions show.

**To Reproduce**
I was trying to cancel a quest.

**Screenshots**
https://prnt.sc/la4y4i

**Server (please complete the following information):**
 - Minecraft Version: 1.13.2
 - Mod Name: Spigot

**Plugin (please complete the following information):**
 - Version: Quests v2.0.14-beta

**Stacktrace**
No error pops up

**Comment by lmbishop** [comment]
Send me your config please. Those aren't permissions by the way, that is the path to the item.

**Comment by Halfhand1** [comment]
https://pastebin.com/T6b9QnVa I hope this works

**Comment by Halfhand1** [comment]
Not sure how I could just send the file

**Comment by Halfhand1** [comment]
It did, thanks alot! really nice plugin. By far one of the best ones I've used. My playerbase loves it ^^
