### ISSUE TITLE
Citizen deliver more than 2304 items

### ISSUE THREAD

**Issue by UnitedCraft** [LMBishop/Quests#360]
### Reason for Addition

I would like the player to be able to deliver more items to the NPCs for the quest

### Description of Feature

Quest for npc deliver 5000 stone.

1. Player bring 2000 stones to npc - npc takes it from inventory and update the progress from 0 to 2000
2. in 2 hours the player brings another batch of stone again and the NPC takes again and update progress
3. And so every time the player delivers the stone, the npc takes it and update progress until the end of the quest

### Alternative Solutions

-

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by Nesseley** [comment]
This should apply for all "deliver" quests. Included "inventory" quests.
