### ISSUE TITLE
Placeholder for Showing progress of currently tracked quest

### ISSUE THREAD

**Issue by PalmTamino** [LMBishop/Quests#361]
### Reason for Addition

My players really loved that feature, as it worked.

### Description of Feature

For example: 10/100 Stone mined

This was already a feature, but got removed without any reason ig. Maybe it is just broken due to an update. If so, please tell me the new placeholder.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by PalmTamino** [comment]
@LMBishop

**Comment by LMBishop** [comment]
The placeholders are on the wiki page https://github.com/LMBishop/Quests/wiki/PlaceholderAPI#quest-details

**Comment by PalmTamino** [comment]
> The placeholders are on the wiki page https://github.com/LMBishop/Quests/wiki/PlaceholderAPI#quest-details

I know, but i think the placeholder for showing progress of currently tracked quest is disabled or remoed because it worked back then…

**Comment by LMBishop** [comment]
It should be working, which one is broken?
