### ISSUE TITLE
edit /quests help message

### ISSUE THREAD

**Issue by Manfruity** [LMBishop/Quests#386]
### Reason for Addition

So you can customize it and remove certain commands that you don't want players to see such as /quests admin and add more info there

### Description of Feature

Edit/change the message of /quests help in the config.yml like other messages

### Alternative Solutions

None

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
(Duplicate of #331.) Though, the /quests admin line isn't shown to players who don't have admin permission. The same goes for other commands if the player does not have the respective permission for it.
