### ISSUE TITLE
Issue with Farming Certain task type

### ISSUE THREAD

**Issue by Sixsoul** [LMBishop/Quests#388]
### Description of Bug

Farming certain is not working.

    type: "farmingcertain" 
    block: POTATO
    amount: 15000

Here is an example. With the quest active, it does not progress when I break a potato.

### Steps to Reproduce

Input quest config above. Break potato. Realize it doesn't work.

### Environment

    Minecraft version: 1.18.2
    Server software: Paper 1.18.2
    Quests version: Latest - 3.11

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
`POTATO` is an item id, you ought to use `POTATOES` instead

**Comment by LMBishop** [comment]
Perhaps try with `POTATOES`
