### ISSUE TITLE
placeholderapi dont work

### ISSUE THREAD

**Issue by Tamanegy** [LMBishop/Quests#399]
### Description of Bug

when putting %player_name% in the lore of an item it wont work (placeholderapi properly downloaded and Player ecloud too)

### Steps to Reproduce

in config.yml and categories:
in lore: type "anexemple %player_name%"

### Environment

- Minecraft version: 1.18.2
- Server software: Paper
- Quests version: 3.12

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by SkirmiLTU** [comment]
same thing for me. And this does not need investigation, this needs fix. Thank you.

**Comment by AlternativeSoap** [comment]
I think it also connect to the mythicmobs placeholder, that doesn't work either

**Comment by LMBishop** [comment]
Are the respective features enabled in config.yml?

https://github.com/LMBishop/Quests/wiki/Basic-options#gui-use-placeholderapi
