### ISSUE TITLE
new task types

### ISSUE THREAD

**Issue by xOpasik** [LMBishop/Quests#401]
### Reason for Addition

I had an idea while preparing quests for my own use

### Description of Feature

I propose to add 3 ticks:

- Reproduction of a specific type of mob,
- Throw / use it with an item like ender pearl, eggs, snowballs, fireworks (on the block)
- Spend a specific type of mob e.g. cow, goat etc.
- Plant / plant individual crops -> wheat / beet / b

### Alternative Solutions

Basically no, I can show you about it if you are willing

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by xOpasik** [comment]
And breed a certain type of mob

**Comment by xOpasik** [comment]
So with the current version of the plugin, the mob tag is not allowed

tasks:
  farming:
    type: "breeding"
    amount: 6
    mob: "CHICKEN" # <-- This line is not allowed
  farming1:
    type: "inventory"
    item:
      quest-item: "EGG"
    amount: 48
    
    
    Please add the option to choose what type of mob you want to multiply

**Comment by xOpasik** [comment]
Listen, can I send you a file with tasks? And you will check what is missing (Some type of task is missing), have I set it up correctly in the config? I will pay or something, because cramp is trying to ask someone for help on the support and nothing, and I do not know how to do it

**Comment by xOpasik** [comment]
Please add the possibility of a task like:

Heal the settler's zombie -> he has to become a settler

Similarly with other animals, for example, to heal

**Comment by xOpasik** [comment]
Please also add:

Possibility of reproducing a specific type of mob, e.g.

   farming1:
     type: "breeding"
     amount: 4
     mob: "TURTLE"
     
     And that you can "collect honeycombs" with the scissors from the hives

**Comment by xOpasik** [comment]
It is now possible to create a kill with the requirement of a specific type of mob, and proposes to introduce the possibility of requiring a specific type of item from a mob, e.g .:

Kill 10 zombies, get 20 rotten meat and zombie heads


Sorry to write this in a few messages

**Comment by LMBishop** [comment]
Could you make a separate issues for all these requests so it's easier to keep track
