### ISSUE TITLE
A bug related to mythicmobs_killing task type

### ISSUE THREAD

**Issue by AllayBreeze** [LMBishop/Quests#409]
### Description of Bug

When a quest's tasks include two or above mythicmobs_killing tasks, the latter kill counter won't work until the former mythicmobs_killing task is completed. Here are my quest YAML file that has this problem: 

tasks:
  ghostkills:
    type: "mythicmobs_killing"
    amount: 60
    name: "MutantDead"
  devilkills:
    type: "mythicmobs_killing"
    amount: 1
    name: "HellDevil"

When this quest starts, killing HellDevils won't increase the number of the killing amount, until "ghostkills" task is finished.
No matter how I change the amount, or the mythicmob name, this problem seems always exists.

Even though I made two different quests, one called quest1 including "ghostkills" task; and another called quest2 including "devilkills", if I start quest1 and then start quest2, killing HellDevils didn't count kill times until quest1 is completed.

By the way, mythicmobs_killing seems to affect the citizens_interact task, too. When a quest has only one citizens_interact task, it works correctly; but if it has both citizens_interact and mythicmobs_killing tasks, the citizens_interact task can never be completed.

### Steps to Reproduce

Create a new quest YAML file and give it two mythicmobs_killing type tasks (with different mythicmob names), or give it a mythicmobs_killing type task and a citizens_interact task. When this quest is started, these problems will occur.

### Environment

- Minecraft version: 1.18.1
- Server software: Paper
- Quests version: 3.12
- Mythicmobs version: 5.1.0 SNAPSHOT

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
> By the way, mythicmobs_killing seems to affect the citizens_interact task, too. When a quest has only one citizens_interact task, it works correctly; but if it has both citizens_interact and mythicmobs_killing tasks, the citizens_interact task can never be completed.

About this, I can't really replicate it. But the other issue should be solved.
