### ISSUE TITLE
New task type - breeding a specific type of mob

### ISSUE THREAD

**Issue by xOpasik** [LMBishop/Quests#414]
### Description of Feature

Please introduce the possibility of reproducing a specific type of mob:
farming:
type: "breeding"
amount: 4
mob: "TURTLE"

### Alternative Solutions

It would work practically the same as it does now, with the difference that instead of including all mobs, it would count the selected specific type of mob

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by Krakenied** [comment]
It exists https://github.com/LMBishop/Quests/commit/b0f75f4f0ea645abc2bda5d589627b341b540c54

**Comment by Tobiczek** [comment]
farming:
    type: "breeding"
    amount: 6
    mob: CHICKEN
    
    Niestety nie dziala na najnowszej wersji
