### ISSUE TITLE
The type of task to use / throw an item

### ISSUE THREAD

**Issue by xOpasik** [LMBishop/Quests#415]
### Description of Feature

Please introduce the possibility of creating a task consisting in:

Throw a certain amount of eggs (do not drop with e.g. Q)
Drop a certain amount of pearls
Use (during the flight) a certain number of fireworks etc.

### Alternative Solutions

This would work on the principle that the player has to use this item and not throw it away, for example, by pressing the Q key

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by xOpasik** [comment]
And I forgot to mention bone meal and other items as well, for example use bone meal x times or use a certain number of times on grass / fungus / tree seedling etc.

**Comment by Krakenied** [comment]
Already possible with `projectilelaunching` task type
