### ISSUE TITLE
Heal / heal creatures

### ISSUE THREAD

**Issue by xOpasik** [LMBishop/Quests#418]
### Description of Feature

Heal / turn a villager zombie into an ordinary villager

Heal the wolf

### Alternative Solutions

It would be like the player would have a specific goal, heal for example 5 zombies villagers into ordinary villagers or heal his wolf with potions or meat etc.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by Krakenied** [comment]
There is no sensible option of detecting healing the wolf

**Comment by Krakenied** [comment]
Added in https://github.com/LMBishop/Quests/pull/642
