### ISSUE TITLE
Support for specific plugins

### ISSUE THREAD

**Issue by xOpasik** [LMBishop/Quests#419]
### Description of Feature

There is actually more of a question here, because I wonder if it would be possible to support new plugins in order to perform quests? For example:

Win 50 duels / 1v1

Kill 3 dual server bosses

Get a server wedding

For now, I am asking, because it is a bit to write about how it could work, but the question is whether it makes sense, generally, do you have time / will

### Alternative Solutions

-

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
You need to tell me which plugins you want task types for, unfortunately, I haven't quite developed the skill of mind reading yet
