### ISSUE TITLE
ConcurrentModificationException when player quits

### ISSUE THREAD

**Issue by Rukes** [LMBishop/Quests#42]
Getting [this error](https://pastebin.com/u2VsbEt5) when player leaves server.
Versions:
Quests: 2.1.1
Paper version git-Paper-498 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by LMBishop** [comment]
Does this happen every time the player quits?

**Comment by Rukes** [comment]
Not every time, but quite frequently.
