### ISSUE TITLE
MythicMobs bug

### ISSUE THREAD

**Issue by elkoyofficial** [LMBishop/Quests#423]
### Description of Bug

[22:32:21 ERROR]: [Quests] Plugin Quests v3.10 has failed to register events for class com.leonardobishop.quests.bukkit.tasktype.type.dependent.MythicMobsKillingType because io/lumine/xikage/mythicmobs/api/bukkit/events/MythicMobDeathEvent does not exist.

### Steps to Reproduce

Try to make a mythicmob quest.

### Environment

- Minecraft version: 1.18.2
- Server software: java 18
- Quests version: Quests-3.13.1-77ab390.jar
 

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Please update quests, your log clearly shows you using a different one to the one you're claiming to use:

> [22:32:21 ERROR]: [Quests] Plugin Quests **v3.10** has failed

**Comment by elkoyofficial** [comment]
Still doesn't register the mythicmobs task on Quests-3.13.1-77ab390. All good though don't need it now.
