### ISSUE TITLE
Inventory tasktype doesnt accept "GOAT_HORN"

### ISSUE THREAD

**Issue by adelando** [LMBishop/Quests#424]
### Description of Bug

After setting task type to inventory and item to "GOAT_HORN" the quest will not complete when obtaining any item.

Will only complete task when given directly from a command

/give <player> goat_horn 1

### Steps to Reproduce

**Task 1**
Create a quest with inventory type set to GOAT_HORN
Drop any goat horn from creative inventory
start quest and pick up items
Does not complete

**Task 2**
Create a quest with inventory type set to GOAT_HORN
Run command /give {player} goat_horn 1
Drop that item
Start quest and pick up item
Quest completes

[quest7.txt](https://github.com/LMBishop/Quests/files/9140469/quest7.txt)

### Environment

- Minecraft version: 1.19
- Server software: git-Purpur-1719 (MC: 1.19)*
- Quests version: 3.13.1-77ab390

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
https://minecraft.fandom.com/wiki/Goat_Horn#Item_data
https://github.com/LMBishop/Quests/wiki/Defining-items#Importing-items
Try importing this item
