### ISSUE TITLE
optimize queries with placeholderapi

### ISSUE THREAD

**Issue by MisterGranti67** [LMBishop/Quests#425]
### Description of Bug

Hello,
would there be a way to optimize queries with placeholderapi?
Because if I activate quests with placeholders on jobreborn, I take a 15 tps and 70 mspt for over 100 players.

If this is not available, would it be possible to update quickly enough to be able to set a refresh time for each placeholderapi request?

Thank you.

### Steps to Reproduce

it is enough to put a jobs quest with all the jobs, then to have 100 players who how the quest, we lose a lot of tps.

### Environment

- Minecraft version: 1.18.2
- Server software: PUFFERFISH
- Quests version: Latest

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Which placeholders exactly? Quests own placeholders allows you to cache them for any amount of time

**Comment by Krakenied** [comment]
I guess that the Jobs placeholders aren't cached and doing database stuff on the main thread :kekw:
