### ISSUE TITLE
Hidden item category

### ISSUE THREAD

**Issue by SrT3ddy** [LMBishop/Quests#426]
### Reason for Addition

The system can be used for both quest and special event missions. 

### Description of Feature

I like to use the plugin for various systems, not just for missions but for event and I would like to hide some category of events, I tried to put the AIR stuff, but it seems that it does not accept this type of item, also tried to remove the item, but the item turned to stone.

### Alternative Solutions

none

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
If I am not mistaken this is already possible: https://github.com/LMBishop/Quests/wiki/Creating-a-category#hidden

**Comment by SrT3ddy** [comment]
> If I am not mistaken this is already possible: https://github.com/LMBishop/Quests/wiki/Creating-a-category#hidden

Oh I hadn't found this on the wiki I'm sorry and thanks for the help and congratulations for the plugin it is very good
