### ISSUE TITLE
Type crafting not working firework

### ISSUE THREAD

**Issue by SrT3ddy** [LMBishop/Quests#427]
### Description of Bug

For some reason the craft mission is not working with firework

### Steps to Reproduce

Craft a firework

### Environment

- Minecraft version: 1.18.2
- Server software: purpur-1.18.2-1632
- Quests version: Quests-3.13.1-77ab390

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Can you try using the [debugger](https://github.com/LMBishop/Quests/wiki/Quest-debugger) and sending what it outputs

**Comment by SrT3ddy** [comment]
I did exactly the debug configuration and it still didn't work, it only works with gamemode firework

**Comment by LMBishop** [comment]
I mean turn it on, attempt the task, and send here what it logs

**Comment by SrT3ddy** [comment]
![image](https://user-images.githubusercontent.com/82233732/182485312-ad6c4e1c-2d0f-48be-ad3d-f00898d7dfd2.png)

**Comment by Krakenied** [comment]
https://github.com/LMBishop/Quests/wiki/Defining-items#Importing-items
Try importing this item
