### ISSUE TITLE
Could not pass event ShopPostTransactionEvent to Quests

### ISSUE THREAD

**Issue by ofunny** [LMBishop/Quests#429]
### Description of Bug

Whenever anybody buys an item in ShopGui+ it will trigger an Java exception – this happens since the latest update of ShopGui+ (https://www.spigotmc.org/resources/shopgui-1-8-1-19.6515/updates) what also describes "breaking changes" to its API.

So quests is listening for that event of ShopGui and now needs an update to work with the latest version.
(Unrelated to quest types, for example I do not use any ShopGui+ quests)

### Steps to Reproduce

1. Install latest Quests plugin and at least ShopGui version 1.78.0+.
2. Buy any item in a ShopGui shop
3. Exception will be triggered in console

NOTE: I did not test custom ShopGUI quests, the API changes in the latest update may also affect those special quest integrations.

### Environment

- Minecraft version: 1.19
- Server software: Paper 1.19
- Quests version: 3.13.1
- ShopGUI+: 1.78.0

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

https://pastebin.com/bftVaKh4

**Comment by LMBishop** [comment]
For now if you don't actually have any ShopGUI+ task types you can [disable the task type](https://github.com/LMBishop/Quests/wiki/Basic-options#task-type-exclusions) to suppress the errors

**Comment by Strahilchu** [comment]
> For now if you don't actually have any ShopGUI+ task types you can [disable the task type](https://github.com/LMBishop/Quests/wiki/Basic-options#task-type-exclusions) to suppress the errors

I'm trying to do this but it's unclear what I need to change or add, I don't see the option to disable that task type
