### ISSUE TITLE
Quest dupe bug AGAIN

### ISSUE THREAD

**Issue by amarcais53** [LMBishop/Quests#430]
### Description of Bug

when you do a craft quest if u hold the item that you need to craft on crafting table and then press drop key on it it will count as crafted but not actualy crafting

### Steps to Reproduce

do exactly like on the video 
https://www.youtube.com/watch?v=b10169EUGsE
so crate a quest of craft
start it
and then use an already crafted item and press drop key with the mouse on it it will count as crafted

### Environment

- Minecraft version: 1.17.1
- Server software: pufferfish
- Quests version: 3.13.1-43c204c

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by amarcais53** [comment]
@LMBishop

**Comment by amarcais53** [comment]
@LMBishop please this is an economy breaker

**Comment by Krakenied** [comment]
It needs fixing dropping with ctrl too lmao
