### ISSUE TITLE
Add more task type options to brewing, shearing and taming

### ISSUE THREAD

**Issue by doitliketyler** [LMBishop/Quests#434]
### Reason for Addition

Currently you can't specify the potion to be brewed, color of sheep to be sheared or type of mob to be tamed.

### Description of Feature

Please add these options to the following task types

brew:
  type: "brewing"
  amount: 10
  potion: JUMP
  level: 1

shear:
  type: "shearing"
  amount: 10
  color: blue

tame:
  type: "taming"
  amount: 10
  mob: wolf

### Alternative Solutions

n/a

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by Krakenied** [comment]
1. not yet
2. soon:tm: https://github.com/Krakenied/Quests/commit/17f4d48d98304ef1fbe8732352cc5c71f12a1faa
3. It already exists lol https://github.com/LMBishop/Quests/commit/0f428e2f3588d631e13e2698e46499a3ffaf2196

**Comment by doitliketyler** [comment]
1. Cool
2. Cool
3. Cool if it already exists but if it's not documented then why exactly are you lol'ing?

**Comment by Krakenied** [comment]
btw that feature works exactly as you specified
```
tame:
type: "taming"
amount: 10
mob: wolf
