### ISSUE TITLE
badly tracked quests

### ISSUE THREAD

**Issue by nikiasek** [LMBishop/Quests#439]
### Description of Bug

I have quest on mining 640 stones. but like 80% of time it doesnt count into progress. It doesnt even cound on others quests like farming or woodcutting.

### Steps to Reproduce

I used  /q admin debug quest mining1stone all and this is what i get:
(https://imgur.com/yHUjwy4)

### Environment

- Minecraft version: 1.19
- Server software: PaperMC
- Quests version: 3.13.1-77ab390

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

Plugins i use:
AuctionMaster, BKCommonLib, CMI, CMILib, Citizens, CoreProtect, CrazyCrates, DeluxeMenus, DeluxeTags, IridiumSkyblock, Jobs, LPC, LiteBans, LuckPerms, MythicLib, NBTAPI, PlaceholderAPI, PreventPortBypass, ProtocolLib, Quests, ServerUtils, ShopGUIPlus, ShopGUIPlusSilkSpawnersBridge, SilkSpawners, SkQuery, SkinsRestorer, Skript, TAB, Vault, ViaBackwards, ViaVersion, VoidGen, Votifier, WorldEdit, WorldGuard, skRayFall and spark

**Comment by LMBishop** [comment]
"CoreProtect indicates block was recently placed, continuing..." means it is not counting due to CoreProtect. Do you have check-coreprotect enabled?

**Comment by nikiasek** [comment]
Like where?

**Comment by nikiasek** [comment]
Sorry for late respond. i downloaded  dev version where was  coreprotect check bug fixed. it works now so thank you so much
