### ISSUE TITLE
BOSS BAR

### ISSUE THREAD

**Issue by mitchngwen** [LMBishop/Quests#442]
### Description of Feature

Boss Bar to track active quests.

### Reason for Addition

Because it is necessary. 

### Alternative Solutions

None

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

### Other

I saw this was requested before, you said you would add but never did. It's is well worth your time and I would pay for a version with this features and so would others.

**Comment by jurienhamaker** [comment]
Adding a 50$ bounty to the first one to create a PR that gets merged.
