### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by uploadx10** [LMBishop/Quests#444]
### Description of Bug

multiserver
error log https://pastebin.com/jcLWwBdx

### Steps to Reproduce

start server

### Environment

- Minecraft version: 1.18.1
- Server software: paper
- Quests version: 3.13.1-77ab390

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by uploadx10** [comment]
Server software: paper

**Comment by LMBishop** [comment]
`Failed to initialize pool: Communications link failure`

This is most likely not an issue with the plugin but your database

Please also fill out the issue form properly

**Comment by uploadx10** [comment]
I connect mysql quest 6 server has server 5 can't connect

**Comment by uploadx10** [comment]
How to fix ? 
database don’t have errors

**Comment by LMBishop** [comment]
> I connect mysql quest 6 server has server 5 can't connect

er, what

**Comment by uploadx10** [comment]
i'm using multi servers 6 servers Server Survival 1-5 can connect database but Survival 6 can’t connect database

**Comment by LMBishop** [comment]
Then this is an issue with your database only allowing a certain number of connections, consult your database manual on how to fix it

**Comment by uploadx10** [comment]
Do you have a solution? I set max connection 100000 can't fix it

**Comment by LMBishop** [comment]
I'm not sure, but whatever is causing the issue it's causing new connections to time out: `Caused by: java.net.SocketTimeoutException: Read timed out`
