### ISSUE TITLE
Quest currently not working?

### ISSUE THREAD

**Issue by ClickErrorxD** [LMBishop/Quests#445]
### Description of Bug

I have a quest to harvest/"farm" carrots. However, player's begin the quest, but the quest doesn't take into account for the farmed carrots that they do.

### Steps to Reproduce

I am unsure: Here is my file for it!
https://paste.helpch.at/noxetamiji.makefile

### Environment

![image](https://user-images.githubusercontent.com/87890013/185523023-b96c5671-eeb1-406b-b9c5-006b00c8f1b3.png)
- Server software: Paperspigot 1.18.2
![image](https://user-images.githubusercontent.com/87890013/185523043-97223fa9-e130-4fd1-b6b6-5b63a7fb3672.png)

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
Your paste is broken
