### ISSUE TITLE
Incorect quests arrangement on linux hosted servers

### ISSUE THREAD

**Issue by EmilPetrakiev** [LMBishop/Quests#449]
### Description of Bug

Hello, I used quests for my server, and when the time came to upload it to a Linux host (with Linux host I mean every Minecraft hosting service)

The problem is that they are incorrectly arranged when I select a category and view the quests in that category.
There is no problem when the server runs on Windows operating system.

I assume that the problem is that the plugin is using the Windows file system to arrange the quests. When the server is running on Linux/Minecraft Hosting Company the plugin does not know how to arrange the quests.

While the server is running on Linux/Minecraft Hosting Company there are no errors in the console that indicate that something is wrong.

I hope I described the problem good enough

### Steps to Reproduce

Use Linux/Minecraft Hosting Company

### Environment

- Minecraft version: 1.18.2 - 1.19.2 (maybe older or newer I didn't test it on other versions)
- Server software: Paper
- Quests version: 3.13.2
- Operating System: Linux/Minecraft Hosting Company

### Agreements

- [x] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Quests provides an option to sort each quest yourself: https://github.com/LMBishop/Quests/wiki/Creating-a-quest#Sort-order
