### ISSUE TITLE
The last version not work on 1.8.8

### ISSUE THREAD

**Issue by Nymphk** [LMBishop/Quests#454]
### Description of Bug

The last version not work more in 1.8.8? ;(

![unknown](https://user-images.githubusercontent.com/21961606/188250464-dd8fb368-9432-48cb-8e98-ee0ccc4b1e6b.png)

### Steps to Reproduce

For me just run the version 3.12.0

### Environment

- Minecraft version: 1.8.8
- Server software: TacoSpigot (Java 8)
- Quests version: 3.13.2

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

...

**Comment by Krakenied** [comment]
Latest version requires Java 17+.

**Comment by Nymphk** [comment]
> The latest version requires Java 17+.

But don't have suport for Java 17 in any 1.8.8 resources... ;(
Can you give suport again for Java 8 please?

**Comment by Krakenied** [comment]
You can always try starting the server with `-DPaper.IgnoreJavaVersion=true` flag  (it's only supported on Paper)
