### ISSUE TITLE
To be able to specific a mob in the Breeding task.

### ISSUE THREAD

**Issue by ClickErrorxD** [LMBishop/Quests#455]
### Description of Feature

Please make it so we can SPECIFY mobs in the breeding task.

### Reason for Addition

Because, it allows for more quest options, rather than just "breed X mob"! You can do "Breed X Sheep!"!

### Alternative Solutions

None. Because you either need to setup your quest to breed X amount, rather than X amount of Y mob.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

**Comment by Krakenied** [comment]
There are `mob` and `mobs` options but they're not documented yet.

**Comment by Krakenied** [comment]
@ClickErrorxD, @Nesseley

```
  breediiiiiiiing:
    type: breeding
    amount: 10
    mobs:
    - SHEEP
    - COW
```


https://github.com/LMBishop/Quests/assets/46192742/6f4ea7ef-3e4c-4ba1-ac97-9dbab4670ad9

@LMBishop can be closed
