### ISSUE TITLE
Travel a certain number of blocks on the horse

### ISSUE THREAD

**Issue by xOpasik** [LMBishop/Quests#456]
### Description of Bug

It does not count the distance traveled on a donkey, a zombie, and a skeleton on a horse

### Steps to Reproduce

-

### Environment

- Minecraft version: 1.19 purpur
- Server software: - 
- Quests version: Quests-3.13.2-d709ab4

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

-

**Comment by Krakenied** [comment]
Already fixed by https://github.com/LMBishop/Quests/commit/a37bb726e6e26b98f6a2326476d79d111279551b
