### ISSUE TITLE
Feature Request: Mobkilling not counting mobs from spawners

### ISSUE THREAD

**Issue by Nesseley** [LMBishop/Quests#460]
### Description of Feature

I would love to be able to not count monsters that spawn from spawners towards the mobkilling task.

### Reason for Addition

I have a repetative task where players must kill 100 zombies to get money, and this gets really easy when you can just do it in a grinder in about 1 minute.

### Alternative Solutions

-

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

**Comment by Krakenied** [comment]
Mobkilling rework soon:tm:
