### ISSUE TITLE
Can this bug be fixed FOR REAL Please.

### ISSUE THREAD

**Issue by amarcais53** [LMBishop/Quests#462]
### Description of Bug

as i reported this bug already 2 times and it got fixed 2 times there is still a bug with crafting quests.
if you use the shift and drop key without clicking on the result of the craft it will count for the quest but way more that you craft

### Steps to Reproduce

create a crafting quest for exemple like fishing rod on the video 
press shift and drop key on the result and then check the count, you will see

https://www.youtube.com/watch?v=d2LPxQYOwrQ

### Environment

- Minecraft version: 1.17.1 
- Server software: puffrefish
- Quests version: Quests-3.13.2-95add2e (which have the fix for another similar bug  )

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

@LMBishop @Krakenied 
the fix that was made before for that got removed here https://github.com/LMBishop/Quests/pull/447/commits/8b3e881c87e5ff539915b9dbd930b8fd1fc79b27

**Comment by amarcais53** [comment]
@LMBishop

**Comment by Krakenied** [comment]
Can't reproduce using latest Quests build

**Comment by Krakenied** [comment]
Probably fixed in https://github.com/LMBishop/Quests/commit/8ed5f8c564138a7eb84864eeb4ebcf8929f21102

**Comment by Krakenied** [comment]
With many other crafting fixes too

**Comment by amarcais53** [comment]
fixed ty
