### ISSUE TITLE
Rename the plugin to be unique

### ISSUE THREAD

**Issue by redshift-s** [LMBishop/Quests#465]
### Description of Feature

It would be nice if this can be loaded at the same time as other quests plugin. We are using another one, but want to add this to make a "leveling" gui. Both plugins is called Quests, and both uses the same plugin folder. I tried to change some minor things and recompile, but I got errors that I don't know how to debug.

### Alternative Solutions

Recompiling myself. But a guide on what things needs to be changed would be nice.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
If you need to change the name of the plugin, you'll have to recompile this yourself. Make sure to change the name in plugin.yml and optionally all the commands as well otherwise the server will refuse to load it if there's a conflict.
