### ISSUE TITLE
Fishing Bug

### ISSUE THREAD

**Issue by Tom18314** [LMBishop/Quests#474]
### Description of Bug

tasks:
  bow:
    amount: 1
    item: BOW
    type: fishingcertain

When the player fishes an enchanted bow it doesn't trigger the quest.

### Steps to Reproduce

Start quest with task as above

Fish a enchanted bow (quest now working)

### Environment

- Minecraft version: 1.19.2
- Server software: 1.19.2 (paper)
- Quests version: 3.13.2

### Agreements

- [x] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by AveValiant** [comment]
I am having the same issue, but with any bow. Does not complete when a player fishes up a bow of any durability.  Does anyone know the fix?

**Comment by Krakenied** [comment]
use the new exact-match option

**Comment by Krakenied** [comment]
@Tom18314, @DevPGSV, @AveValiant

```
  fishiiiiiiiiiing:
    type: "fishing"
    amount: 1000000
    item: BOW
    exact-match: false
```

https://github.com/LMBishop/Quests/assets/46192742/9c35988e-3d82-4f9c-9969-41bddfb02221

@LMBishop can be closed
