### ISSUE TITLE
Dependency

### ISSUE THREAD

**Issue by dom1s** [LMBishop/Quests#476]
### Description of Bug

I have no clue why the dependency is not working. I wrote everything as it was said in the docs.

### Steps to Reproduce

I have no clue why the dependency is not working. I wrote everything as it was said in the docs.
![questdepo](https://user-images.githubusercontent.com/50181423/208773153-b6e24d40-0bac-4d1a-80ab-5fb165e09793.png)

### Environment

- Minecraft version: 1.19.2
- Server software: Spigot
- Quests version: Latest

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Please use `3.12` as the version string for now
