### ISSUE TITLE
Quests journal error

### ISSUE THREAD

**Issue by dmitriJ2101** [LMBishop/Quests#477]
### Description of Bug

![Скриншот 23-12-2022 043747](https://user-images.githubusercontent.com/45642357/209253696-1b587a04-62ef-4503-8755-9930e3e6223b.png)

### Steps to Reproduce

I'am user command /quests journal

### Environment

- Minecraft version: 1.12.2
- Server software: spigot 1.12.2.
- Quests version: 4.6.1

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
You're using another Quests plugin.
