### ISSUE TITLE
[Bug for bedrock]Bedrock cloud not cancel quest if quest name is Chinese

### ISSUE THREAD

**Issue by addpromax** [LMBishop/Quests#492]
### Description of Bug

Bedrock cloud not cancel quest if quest name is Chinese

### Steps to Reproduce

1.Bedrock get more than 1 quest
2.Quest name is Chinese and Have special numeric

### Environment

- Minecraft version: 1.19.3
- Server software: Purpur1.19.3
- Quests version: 3.12.3

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
I don't think this is a Quests issue
