### ISSUE TITLE
i need help, how can i get this quest board .. 

### ISSUE THREAD

**Issue by Masoxiss** [LMBishop/Quests#493]
### Type of Change

Fix typo

### Description of Change

![questshelp](https://user-images.githubusercontent.com/125094588/218217679-cb1fee9e-98ec-4303-b8e4-acea3cebf8ca.png)

### Page Markup

```true
i dont know how to get it in server ..
```

**Comment by Krakenied** [comment]
https://github.com/LMBishop/Quests/wiki/Quest-progress-in-scoreboard
