### ISSUE TITLE
Smithing an enchanted diamond armor to netherite doesnt complete quest

### ISSUE THREAD

**Issue by Kaap0** [LMBishop/Quests#495]
### Description of Bug

Smithing an enchanted diamond armor to netherite doesnt complete quest

tasks:
  smithing:
    type: "smithing"
    amount: 1
    item: NETHERITE_LEGGINGS

### Steps to Reproduce

title

### Environment

- Minecraft version: 1.19.3
- Server software: Purpur 1.19.3
- Quests version: 3.13.3-5a28efa

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
Fixed in https://github.com/LMBishop/Quests/pull/509
