### ISSUE TITLE
Can't do /q or /quest

### ISSUE THREAD

**Issue by SkyWaves123** [LMBishop/Quests#497]
### Description of Bug

The plugin doesnt let me use /q or /quest and it shows an error in the console when I use the commands. 

### Steps to Reproduce

I just installed the plugin and I get this error.
03.03 19:32:32 [Server] [INFO] org.bukkit.command.CommandException: Unhandled exception executing command 'q' in plugin Quests v3.13.3-5a28efa
03.03 19:32:32 [Server] [INFO] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.8.8.jar:git-PaperSpigot-445]
03.03 19:32:32 [Server] [INFO] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.8.8.jar:git-PaperSpigot-445]
03.03 19:32:32 [Server] [INFO] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched_1.8.8.jar:git-PaperSpigot-445]
03.03 19:32:32 [Server] [INFO] at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched_1.8.8.jar:git-PaperSpigot-445]
03.03 19:32:32 [Server] [INFO] at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched_1.8.8.jar:git-PaperSpigot-445]
03.03 19:32:32 [Server] [INFO] at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.8.8.jar:git-PaperSpigot-445]
03.03 19:32:32 [Server] [INFO] at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched_1.8.8.jar:git-PaperSpigot-445]
03.03 19:32:32 [Server] [INFO] at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.8.8.jar:git-PaperSpigot-445]
03.03 19:32:32 [Server] [INFO] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
03.03 19:32:32 [Server] [INFO] at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
03.03 19:32:32 [Server] [INFO] at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched_1.8.8.jar:git-PaperSpigot-445]
03.03 19:32:32 [Server] [INFO] at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched_1.8.8.jar:git-PaperSpigot-445]
03.03 19:32:32 [Server] [INFO] at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
03.03 19:32:32 [Server] [INFO] at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
03.03 19:32:32 [Server] [INFO] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
03.03 19:32:32 [Server] [INFO] at java.lang.Thread.run(Thread.java:831) [?:?]
03.03 19:32:32 [Server] [INFO] Caused by: java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/ints/Int2ObjectOpenHashMap
03.03 19:32:32 [Server] [INFO] at com.leonardobishop.quests.bukkit.menu.QMenu.<init>(QMenu.java:12) ~[?:?]
03.03 19:32:35 [Server] [INFO] at com.leonardobishop.quests.bukkit.menu.PaginatedQMenu.<init>(PaginatedQMenu.java:29) ~[?:?]
03.03 19:32:35 [Server] [INFO] at com.leonardobishop.quests.bukkit.menu.CategoryQMenu.<init>(CategoryQMenu.java:25) ~[?:?]
03.03 19:32:35 [Server] [INFO] at com.leonardobishop.quests.bukkit.util.MenuUtils.openMainMenu(MenuUtils.java:69) ~[?:?]
03.03 19:32:35 [Server] [INFO] at com.leonardobishop.quests.bukkit.command.QuestsCommandSwitcher.onCommand(QuestsCommandSwitcher.java:65) ~[?:?]
03.03 19:32:35 [Server] [INFO] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.8.8.jar:git-PaperSpigot-445]
03.03 19:32:35 [Server] [INFO] ... 15 more
03.03 19:32:35 [Server] [INFO] Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap
03.03 19:32:35 [Server] [INFO] at com.leonardobishop.quests.bukkit.menu.QMenu.<init>(QMenu.java:12) ~[?:?]
03.03 19:32:35 [Server] [INFO] at com.leonardobishop.quests.bukkit.menu.PaginatedQMenu.<init>(PaginatedQMenu.java:29) ~[?:?]
03.03 19:32:35 [Server] [INFO] at com.leonardobishop.quests.bukkit.menu.CategoryQMenu.<init>(CategoryQMenu.java:25) ~[?:?]
03.03 19:32:35 [Server] [INFO] at com.leonardobishop.quests.bukkit.util.MenuUtils.openMainMenu(MenuUtils.java:69) ~[?:?]
03.03 19:32:35 [Server] [INFO] at com.leonardobishop.quests.bukkit.command.QuestsCommandSwitcher.onCommand(QuestsCommandSwitcher.java:65) ~[?:?]
03.03 19:32:35 [Server] [INFO] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.8.8.jar:git-PaperSpigot-445]
03.03 19:32:35 [Server] [INFO] ... 15 more

### Environment

- Minecraft version: 1.8.9
- Server software: paperspigot 1.8.8
- Quests version: latest 

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
I'll fix it today

**Comment by Krakenied** [comment]
Probably there were no FastUtil on 1.8.8
