### ISSUE TITLE
BrewEvent

### ISSUE THREAD

**Issue by SkyWaves123** [LMBishop/Quests#503]
### Description of Bug

I get this error every time someone brews potions
25.03 22:00:37 [Server] [ERROR] Could not pass event BrewEvent to Quests v3.13.3-5a28efa
25.03 22:00:37 [Server] [INFO] org.bukkit.event.EventException: null
25.03 22:00:37 [Server] [INFO] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched_1.8.8.jar:git-PaperSpigot-445]
25.03 22:00:37 [Server] [INFO] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.8.8.jar:git-PaperSpigot-445]
25.03 22:00:37 [Server] [INFO] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-PaperSpigot-445]
25.03 22:00:37 [Server] [INFO] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.8.8.jar:git-PaperSpigot-445]
25.03 22:00:37 [Server] [INFO] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.8.8.jar:git-PaperSpigot-445]
25.03 22:00:37 [Server] [INFO] at net.minecraft.server.v1_8_R3.TileEntityBrewingStand.o(TileEntityBrewingStand.java:153) [patched_1.8.8.jar:git-PaperSpigot-445]
25.03 22:00:37 [Server] [INFO] at net.minecraft.server.v1_8_R3.TileEntityBrewingStand.c(TileEntityBrewingStand.java:75) [patched_1.8.8.jar:git-PaperSpigot-445]
25.03 22:00:37 [Server] [INFO] at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1516) [patched_1.8.8.jar:git-PaperSpigot-445]
25.03 22:00:37 [Server] [INFO] at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:600) [patched_1.8.8.jar:git-PaperSpigot-445]
25.03 22:00:37 [Server] [INFO] at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:846) [patched_1.8.8.jar:git-PaperSpigot-445]
25.03 22:00:37 [Server] [INFO] at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
25.03 22:00:37 [Server] [INFO] at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
25.03 22:00:41 [Server] [INFO] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
25.03 22:00:41 [Server] [INFO] at java.lang.Thread.run(Thread.java:831) [?:?]
25.03 22:00:41 [Server] [INFO] Caused by: java.lang.NoSuchMethodError: 'java.util.List org.bukkit.event.inventory.BrewEvent.getResults()'
25.03 22:00:41 [Server] [INFO] at com.leonardobishop.quests.bukkit.tasktype.type.BrewingTaskType.onBrew(BrewingTaskType.java:76) ~[?:?]
25.03 22:00:41 [Server] [INFO] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
25.03 22:00:41 [Server] [INFO] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
25.03 22:00:41 [Server] [INFO] at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
25.03 22:00:41 [Server] [INFO] at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
25.03 22:00:41 [Server] [INFO] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PaperSpigot-445]
25.03 22:00:41 [Server] [INFO] ... 13 more

### Steps to Reproduce

Just brew any potion on 1.8.8

### Environment

- Minecraft version: 1.8.8
- Server software: PaperSpigot-445
- Quests version: 3.13.3-5a28efa

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
Unfortunately, handling that task type in versions older than 1.17.1 properly isn't actually possible because of lack of the [BrewEvent#getResults](https://helpch.at/docs/1.17.1/org/bukkit/event/inventory/BrewEvent.html#getResults()) method.
