### ISSUE TITLE
Mythicmobs doesn't work

### ISSUE THREAD

**Issue by AlternativeSoap** [LMBishop/Quests#504]
### Description of Bug

Latest version of Mythicmobs Premium does not work with Quests in 1.19.4.

### Steps to Reproduce

Use
Mythicmobs Premium
Paper 1.19.4
Task: mythicmobs_killing

### Environment

- Minecraft version: 1.19.4
- Server software: Paper 1.19.4 490
- Quests version: 3.13.3
- Mythicmobs Premium 5.2.5

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
wdym "doesn't work"

**Comment by AlternativeSoap** [comment]
All of my MythicMobs Quests doesn't show anymore since 1.19.4, and since I've updated to Premium Mythicmobs 1.19.4

It worked fine before but now it doesn't show anything.

**Comment by Krakenied** [comment]
> All of my MythicMobs Quests doesn't show anymore since 1.19.4, and since I've updated to Premium Mythicmobs 1.19.4
> 
> It worked fine before but now it doesn't show anything.

Show `/ver MythicMobs` output
