### ISSUE TITLE
q started not updated after cancel quest confirm

### ISSUE THREAD

**Issue by matipoirierg** [LMBishop/Quests#505]
### Description of Bug

If you cancel a quest using /q started, after the confirmation gui, q started gui is not updated so still shows the cancelled quests.

### Steps to Reproduce

If you cancel a quest using /q started, after the confirmation gui, q started gui is not updated so still shows the cancelled quests.

### Environment

- Minecraft version: 1.19.4
- Server software: Purpur 
- Quests version: 3.13.3

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
This was intentional so the player has the option to start it again if it was accidental.
