### ISSUE TITLE
Need Help ASAP:  Could not pass event UserBalanceUpdateEvent to Quests v3.13.3-5a28efa

### ISSUE THREAD

**Issue by ClickErrorxD** [LMBishop/Quests#506]
### Description of Bug

https://mcpaste.io/15c47a88da50fcee
https://mcpaste.io/ca06e734c8c944e7

### Steps to Reproduce

I am using the quest type: `essentials_moneyearn`

### Environment

![image](https://user-images.githubusercontent.com/87890013/231502201-d0fd4139-75c8-4b4e-a297-41dae9ee2433.png)
![image](https://user-images.githubusercontent.com/87890013/231502257-e29ef3fd-c2c5-42f6-82c7-af755c6aa360.png)

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

mcpaste.io/15c47a88da50fcee https://mcpaste.io/ca06e734c8c944e7

**Comment by Krakenied** [comment]
Try with latest build
https://github.com/LMBishop/Quests/actions/runs/4588417378

**Comment by ClickErrorxD** [comment]
> Try with latest build https://github.com/LMBishop/Quests/actions/runs/4588417378

![image](https://user-images.githubusercontent.com/87890013/232259772-4279c2f6-6f5c-412f-a39a-f0dacff425ca.png)
This?

**Comment by Krakenied** [comment]
Yes
