### ISSUE TITLE
FARMING ERROR /  beetroot, potato and carrot 

### ISSUE THREAD

**Issue by kurkinsnetwork** [LMBishop/Quests#507]
### Description of Bug

https://prnt.sc/D7OeNEZ6gTVo

it shows error even though it is error free

### Steps to Reproduce

tasks:
  farming:
    type: "farmingcertain"
    amount: 100
    block: CARROT
    reverse-if-broken: false
    check-coreprotect: false
    check-coreprotect-time: 3600
    worlds:
      - "SuperiorWorld"
      - "SuperiorWorld_nether"
      
display:
  name: "&eÇiftçi Görevi &7(Havuç II)"
  lore-normal:
    - ""
    - "&eAçıklama&7:"
    - " &8▐ &7Adanda &aHavuç &7Hasadı Yaparak"
    - " &8▐ &7Görevde İlerleme Kaydedip"
    - " &8▐ &7Ödülleri Toplayabilirsin"
    - ""
    - "&eGörevin&7:"
    - " &8▐ &7Bu Görev için senden Istenilen:"
    - " &8▐ &7 - &a100 Havuç&7 Hasadı Yap."
    - ""
    - "&eÖdülün:"
    - " &8▐ &a250 &7Dinar"
  lore-started:
    - ""
    - "&7Görevdeki Ilerlemen:"
    - "&7 - &f{farmingmultiple:progress}&7/100 Havuç Hasadı Yapıldı."
  type: "CARROT"

rewards:
  - "eco give {player} 250"
placeholders:
  description: "&f100 Havuç &7Hasadı Yap."
  progress: " &8- &f{farmingmultiple:progress}&7/100"

options:
  category: "ciftci"
  requires:
    - "ciftcicarrot1"
  repeatable: false
  cooldown:
    enabled: false
    time: 1440
  sort-order: 38

### Environment

- Minecraft version: 1.16.5
- Server software: paper
- Quests version: 3.13.3

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

discord: Kurkins#7019

**Comment by Krakenied** [comment]
It's unsuitable

**Comment by Krakenied** [comment]
You should use CARROTS, POTATOES and BEETROOTS materials (ones with Ageable BlockData)
