### ISSUE TITLE
Placeholderapi not working in GUI title

### ISSUE THREAD

**Issue by LuluxClient** [LMBishop/Quests#508]
### Description of Bug

title says it all

### Steps to Reproduce

use a placeholder from placeholderapi in a menu title

### Environment

- Minecraft version: This server is running Pufferfish version git-Pufferfish-65 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: c09a154 on HEAD)
You are running 2 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Pufferfish-59 (MC: 1.19.3)
- Server software: pufferfish
- Quests version: 3.13.3

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by AfkF24** [comment]
Looks like papi support for gui titles wasn't implemented in the first place, just for items inside guis
