### ISSUE TITLE
PLACEHOLDER NOT WORK

### ISSUE THREAD

**Issue by kurkinsnetwork** [LMBishop/Quests#510]
### Description of Bug

Bamboo farmer misssion placeholder not work

### Steps to Reproduce

https://prnt.sc/EuF-2ivv6CGi Look this placeholder always show 0.
my config:

tasks:
  farming:
    type: "farming"
    amount: 100
    block: BAMBOO
    reverse-if-broken: false
    check-coreprotect: false
    check-coreprotect-time: 3600
    worlds:
      - "SuperiorWorld"
      - "SuperiorWorld_nether"
display:
  name: "&eÇiftçi Görevi &7(Bambu I)"
  lore-normal:
    - ""
    - "&eAçıklama&7:"
    - " &8▐ &7Adanda &aBambu &7Hasadı Yaparak"
    - " &8▐ &7Görevde İlerleme Kaydedip"
    - " &8▐ &7Ödülleri Toplayabilirsin"
    - ""
    - "&eGörevin&7:"
    - " &8▐ &7Bu Görev için senden Istenilen:"
    - " &8▐ &7 - &a100 Bambu&7 Hasadı Yap."
    - ""
    - "&eÖdülün:"
    - " &8▐ &a100 &7Dinar"
  lore-started:
    - ""
    - "&7Görevdeki Ilerlemen:"
    - "&7 - &f{farming:progress}&7/100 Bambu Hasadı Yapıldı."
  type: "BAMBOO"

rewards:
  - "eco give {player} 100"
placeholders:
  description: "&f100 Bambu &7Hasadı Yap."
  progress: " &8- &f{farming:progress}&7/100"

options:
  category: "ciftci"
  repeatable: false
  cooldown:
    enabled: false
    time: 1440
  sort-order: 1

### Environment

- Minecraft version: 1.17.1
- Server software: pufferfish
- Quests version: latest version

### Agreements

- [x] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by kurkinsnetwork** [comment]
this problem not placeholder api.
quest dont work.

**Comment by TUCAOEVER** [comment]
Use blockbreak quest type instead of farming

**Comment by kurkinsnetwork** [comment]
hi can you send example config for bamboo

**Comment by LMBishop** [comment]
Superseded by #519
