### ISSUE TITLE
plugind doesnt work (

### ISSUE THREAD

**Issue by bentosss1** [LMBishop/Quests#511]
### Description of Bug

I write /quests and get the error 'an internal error occurred...'

### Steps to Reproduce

1. open chat
2. write /quests
3. open console
4. ask for help

### Environment

- Minecraft version:
- Server software:
- Quests version:
1.19.2
spigot
last

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

[latest.log](https://github.com/LMBishop/Quests/files/11424251/latest.log)
my logs

**Comment by Krakenied** [comment]
Your Quests config is broken
