### ISSUE TITLE
Quests Actionbar

### ISSUE THREAD

**Issue by NoltoxGit** [LMBishop/Quests#517]
### Description of Feature

Hello !
Would it be possible to add the actionbar feature when a quest is in progress?

Exemple : https://prnt.sc/1IeYQVvzSLGG

### Reason for Addition

I'm proposing this suggestion because I think it's useful for players to know where they stand in their quest. And having an actiobar message constantly displayed is a good solution for that!

### Alternative Solutions

I have no alternative solution.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
A plan for Quests to provide its own way of displaying progress through titles / scoreboards / action bars is somewhere in the to-do list, but for now the suggested action is to use an external plugin with placeholders.
