### ISSUE TITLE
FARMING QUEST NOT WORK

### ISSUE THREAD

**Issue by kurkinsnetwork** [LMBishop/Quests#519]
### Description of Bug

Hello BAMBOO block not work in farming quest type.
can you send correct example config ?
thanks

### Steps to Reproduce

add farming type Bamboo block

### Environment

- Minecraft version: 1.19.4
- Server software: pufferfish
- Quests version: 3.13.3

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Can you say what you've tried?

**Comment by kurkinsnetwork** [comment]
tasks:
  blockbreak:
    type: "blockbreakcertain"
    amount: 100
    block: BAMBOO
    worlds:
      - "SuperiorWorld"
      - "SuperiorWorld_nether"
display:
  name: "&eÇiftçi Görevi &7(Bambu I)"
  lore-normal:
    - ""
    - "&eAçıklama&7:"
    - " &8▐ &7Adanda &aBambu &7Hasadı Yaparak"
    - " &8▐ &7Görevde İlerleme Kaydedip"
    - " &8▐ &7Ödülleri Toplayabilirsin"
    - ""
    - "&eGörevin&7:"
    - " &8▐ &7Bu Görev için senden Istenilen:"
    - " &8▐ &7 - &a100 Bambu&7 Hasadı Yap."
    - ""
    - "&eÖdülün:"
    - " &8▐ &a200 &7Dinar"
  lore-started:
    - ""
    - "&7Görevdeki Ilerlemen:"
    - "&7 - &f{blockbreak:progress}&7/100 Bambu Hasadı Yapıldı."
  type: "BAMBOO"


rewards:
  - "eco give {player} 200"
placeholders:
  description: "&f100 Bambu &7Hasadı Yap."
  progress: " &8- &f{blockbreak:progress}&7/100"

options:
  category: "ciftci"
  repeatable: false
  cooldown:
    enabled: false
    time: 1440
  sort-order: 1

This is my Farming quest but its not work can you send correct settings.

**Comment by LMBishop** [comment]
Try `BAMBOO_BLOCK`

**Comment by kurkinsnetwork** [comment]
its not work

**Comment by kurkinsnetwork** [comment]
can you fast respond please

**Comment by 6u5t4v** [comment]
blockbreak insteadof blockbreakcertain

**Comment by 6u5t4v** [comment]
https://quests.leonardobishop.com/task-types/built-in-task-types.html, you might be able to use the farming tasktype instead

**Comment by kurkinsnetwork** [comment]
its not work
tasks:
  farming:
    type: "farming"
    amount: 100
    block: BAMBOO
    worlds:
      - "SuperiorWorld"
      - "SuperiorWorld_nether"
display:
  name: "&eÇiftçi Görevi &7(Bambu I)"
  lore-normal:
    - ""
    - "&eAçıklama&7:"
    - " &8▐ &7Adanda &aBambu &7Hasadı Yaparak"
    - " &8▐ &7Görevde İlerleme Kaydedip"
    - " &8▐ &7Ödülleri Toplayabilirsin"
    - ""
    - "&eGörevin&7:"
    - " &8▐ &7Bu Görev için senden Istenilen:"
    - " &8▐ &7 - &a100 Bambu&7 Hasadı Yap."
    - ""
    - "&eÖdülün:"
    - " &8▐ &a200 &7Dinar"
  lore-started:
    - ""
    - "&7Görevdeki Ilerlemen:"
    - "&7 - &f{farming:progress}&7/100 Bambu Hasadı Yapıldı."
  type: "BAMBOO"


rewards:
  - "eco give {player} 200"
placeholders:
  description: "&f100 Bambu &7Hasadı Yap."
  progress: " &8- &f{farming:progress}&7/100"

BAMBOO or BAMBOO_BLOCK not work.
Blockbreak or farming not work

**Comment by 6u5t4v** [comment]
any errors? and are you in the correct world

**Comment by 6u5t4v** [comment]
you can type /q a config to see if theres errors

**Comment by kurkinsnetwork** [comment]
HELLOOO ANYONE CAN HELP ME ?
