### ISSUE TITLE
Crash with an offline player (BUG)

### ISSUE THREAD

**Issue by FunSkelet** [LMBishop/Quests#520]
### Description of Feature

Hi, I have a plugin connected with clans, but there is such a problem that when a player is excluded offline, his quest date is not loaded, and therefore the server crashes. Is there any way to enable the ability to download offline player data?

### Alternative Solutions

There are no such

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

**Comment by FunSkelet** [comment]
In addition. The connection with another plugin has nothing to do with it, it crashes when the player as a whole is offline (the command used is /quests admin moddata reset nick quest)

**Comment by LMBishop** [comment]
The plugin should automatically load data when trying to modify an offline players data. Can you send your crash logs?

**Comment by FunSkelet** [comment]
> The plugin should automatically load data when trying to modify an offline players data. Can you send your crash logs?

![image](https://github.com/LMBishop/Quests/assets/68019106/71618ba8-1beb-4ff6-a1c6-f77644f4a867)

**Comment by FunSkelet** [comment]
And when entering the usual command

![image](https://github.com/LMBishop/Quests/assets/68019106/41690b8d-f2aa-460a-a33e-7439e8df2e78)

**Comment by FunSkelet** [comment]
@LMBishop ?

**Comment by LMBishop** [comment]
I see. Do you know if this issue occurs using `/q a moddata random` and `/q a moddata complete`? It seems that `reset` and `start` load the player synchronously (which hangs until they're loaded), differently from the other two which loads async (and shouldn't hang), for reasons I don't quite remember yet.

**Comment by FunSkelet** [comment]
/q a moddata start
![image](https://github.com/LMBishop/Quests/assets/68019106/fe52f75f-69fb-462f-8f7f-476a896ce7af)

**Comment by FunSkelet** [comment]
/q a moddata complete 
![image](https://github.com/LMBishop/Quests/assets/68019106/658ad52a-c1b3-44d0-a9db-e8882da54784)

Everything is fine here

**Comment by FunSkelet** [comment]
And /q a moddata fullreset
![image](https://github.com/LMBishop/Quests/assets/68019106/154ca6a6-0d96-40b6-9daa-2327eb7a853b)
