### ISSUE TITLE
Follow up on EcoBosses task type

### ISSUE THREAD

**Issue by TheKalien** [LMBishop/Quests#522]
### Description of Bug

Hi! 
Thank you very much for adding this task type 🙏
I've tested it now but when I kill the boss the quest doesn't progress/complete.
I see nothing in console either 🤔
No errors are given from this quest, so I don't know what the issue could be!

### Steps to Reproduce

I've followed the YML example on this page exactly: https://quests.leonardobishop.com/task-types/ecobosses_killing-(task-type).html

My boss name did initially have an _ in it so I tried without, that didn't seem to affect anything. 
Here's how it looks in console when you kill the boss if that's any help:
![c10f9ae5e74b9daf55f88e2cd1f99d08](https://github.com/LMBishop/Quests/assets/49004198/2de70298-632f-4a8c-a98c-4ac9b04b8631)

### Environment

- Minecraft version: 1.20
- Server software: Pufferfish version git-Pufferfish-15 (MC: 1.20.1) 
- Quests version: 3.14.1

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Could you try the version compiled from this commit and see if the issue persists?

https://github.com/LMBishop/Quests/actions/runs/5500951383

**Comment by TheKalien** [comment]
I've tested now with several bosses and it seems to be working perfectly!!

Thank you very much for quick implementation and fix! 🙏
