### ISSUE TITLE
Negative value when the reverse-if-placed parameter is enabled

### ISSUE THREAD

**Issue by FunSkelet** [LMBishop/Quests#530]
### Description of Feature

When this parameter is enabled and the player puts blocks, they are taken away, but then it goes to a negative value

### Alternative Solutions

Make it so that it does not go into a negative value, or add a parameter of the format "negative-value: true|false"

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
The value going negative is an intended feature. I can add an option to prevent it though.

**Comment by FunSkelet** [comment]
> The value going negative is an intended feature. I can add an option to prevent it though.

It would be good
