### ISSUE TITLE
Issue with the permission-required variable.

### ISSUE THREAD

**Issue by umvrr** [LMBishop/Quests#533]
### Description of Bug

I have enabled the permission-required variable for all of my quest categories. Moreover, I've removed all of my permissions such as server operator and full permissions with the Quests plugin. I'm practically any server member. Now, when I do /quests to access the menu to see whether I can still access the category & start new quests I see that I still can. 

### Steps to Reproduce

Here are the steps to reproduce the issue.

- Choose a category, and set the "permission-required" variable to true.
- Save the changes, and reload the plugin.
- Remove all of your permissions that may bypass the change.
- Run the /quests command, and you'll see you still have access even with the "permission-required" variable being set to true.

### Environment

- Minecraft version: 1.20.1
- Server software: Pufferfish fork of Paper.
- Quests version :3.14.2-3345d07

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
I'm not able to reproduce this, using the default configuration which includes an example of categories requiring permissions
