### ISSUE TITLE
Bamboo quests not working with coreprotect

### ISSUE THREAD

**Issue by Tizooo** [LMBishop/Quests#542]
### Description of Bug

if coreprotect check is enabled for bamboo it doesent count if you break a grown bamboo you placed. (so u dont break the same block u placed u break a block from the grown bamboo u placed and it still doesent count)

### Steps to Reproduce

use this config and try to break a grown part from a bamboo u placed:

tasks:
  harvest:
    check-coreprotect: true
    check-coreprotect-time: 86400
    type: "blockbreakcertain"
    amount: 192
    block: "BAMBOO"
    reverse-if-placed: true
display:
  name: "payed_recource_content"
  lore-normal:
  - "payed_recource_content"
  - "payed_recource_content"
  - ""
  - "&dOptions:"
  - "payed_recource_content"
  - "payed_recource_content"
  - ""
  - "&dRewards:"
  - "payed_recource_content."
  - ""
  lore-started:
  - "&e▲payed_recource_content."
  type: "BAMBOO"
# Here you can list messages which will be sent to the player (if they are online) upon the quest starting.
startstring:
- "&7payed_recource_contenth"
- " payed_recource_content"
rewards:
- "eco give {player} 250"
# Here you can list messages which will be sent to the player (if they are online) upon completion.
rewardstring:
- " payed_recource_contente."

options:
  category: "farming"
  requires: []
  repeatable: false
  cooldown:
    enabled: true
    time: 82600
  sort-order: 33
placeholders:
  description: payed_recource_content.
  progress: '{harvest:progress}'
  max: '192'

### Environment

purpur 1.20.1
quests 3.14.2

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
You need to use farming task type
