### ISSUE TITLE
PlaceholderAPI check time

### ISSUE THREAD

**Issue by WarnDa** [LMBishop/Quests#547]
### Description of Feature

For quests checking for placeholderAPI, add a config option to set a cooldown between two check of the placeholders, because we'll got ~8 quests for all players checking for placeholderAPI, and no need to check them every 1s, every 30s would be enough for us

### Reason for Addition

It can be heavy, especially with plugins getting heavy placeholderAPI check

### Alternative Solutions

Don't use placeholderAPI quests ? (lol)

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

**Comment by Krakenied** [comment]
Tbh the correct approach to this would be calculating async and caching the placeholder value on the expansion side but we can add such an option
