### ISSUE TITLE
Count all blocks above on farming quests

### ISSUE THREAD

**Issue by WarnDa** [LMBishop/Quests#548]
### Description of Feature

I'm using quests about "block sugar cane" or "cactus" "bamboo" "kelp""chorus" and if player break the base block, it only counts the base block and not the one above.

So the goal is to add an option to counts all blocks above the one you break of farming quests

### Reason for Addition

Players are frustrated by this and complain that it doesn't count all blocks above

### Alternative Solutions

Tell players "no it won't change" and start to see them leaving my server :( 

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
This is slightly challenging as there is no event (that I know of) for this

**Comment by WarnDa** [comment]
> This is slightly challenging as there is no event (that I know of) for this

I know JobsReborn have a feature for this (can be enabled in config), and QuestCreator also has this feature
https://github.com/Zrips/Jobs
`# When enabled we will try to pay player for blocks above broken ones. This only applies to sugarcane, bamboo, kelp and weeping_vines
pay-for-above: true`
