### ISSUE TITLE
Tasks that start automatically are not automatically tracked

### ISSUE THREAD

**Issue by tsingyayin** [LMBishop/Quests#570]
### Description of Bug

I now have a Category consisting of a series of Quests to help players understand the structure and facilities of our Spawn. I have set the Requirements for each Quest as the previous Quest and used AutoStart. I hope the plugin's performance is that after the player arrives at a location (i.e. completes Quest), AutoStart config can automatically gives the next Quest to the player to guide them step by step through the Spawn. However, I found that the second Quest (i.e. Quest with AutoStart ) can be automatically started, but AutoTrack is not enabled, which means that what I see in the AnimatedScoreboard is "no Quest being tracked", And the GUI prompts me to use the middle of the mouse to track the automatically launched Quest.

Please forgive my offense, but I believe this should be a bug because AutoTrack's work does not meet the expectations described in WIKI, which is to automatically track every already started Quest. Automatic tracking is very important. If this feature does not work properly, the prompts in the Scoreboard will be inconsistent, and new players joining the server may soon lose their direction.

I have posted what I have done below. If there is a problem with my configuration or operation, please kindly correct my mistake. If my understanding of WIKI is incorrect, please help me achieve the "step-by-step guidance" task I hope to achieve.

### Steps to Reproduce

1. Establish a Quest B
2. Set Requirements to any other Quest A
3. Configure Quest B as AutoStart
4. Reload plugin config
5. Complete Quest A
6. You will find that Quest B is not automatically tracked

### Environment

- Minecraft version: Purpur-1.20.2-2082
- Server software: Windows Server 2022 / JDK 19.0
- Quests version: 3.14.2-3345d07

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
https://github.com/LMBishop/Quests/blob/9206827fc24a05812609394a8810b2a02d11d60b/bukkit/src/main/resources/resources/bukkit/config.yml#L103-L104C24

Make sure you have `quest-autotrack` set to `true`

**Comment by tsingyayin** [comment]
This option has always been true

**Comment by Krakenied** [comment]
Do you have autostart set for specific quests or globally

**Comment by tsingyayin** [comment]
I have already set it up. As I mentioned earlier, automatic start is normal (as reflected in the GUI), but automatic tracking is not normal. It becomes non tracking after the previous Quest is completed

**Comment by Krakenied** [comment]
But is your autostart enabled [globally](https://quests.leonardobishop.com/configuration/basic-options.html#quest-autostart) or [for specific quests](https://quests.leonardobishop.com/configuration/creating-a-quest.html#autostart)?

**Comment by tsingyayin** [comment]
Do you mean the `options.autostart` of each Quest?  I am sure they are all set to `true`.
The `options.quest-autostart` in `config. yml` is indeed `false`, as some Quest players may not want to do it.

Sorry, I am puzzled by your inquiry because as I described, there are no issues with automatic startup.
Players can immediately run to the second location after reaching the first location to complete the entire Category correctly, but they cannot see the tracking prompt for the second Quest. Normally, after the first Quest is completed, the second Quest is automatically started and should be automatically tracked, right?
