### ISSUE TITLE
pyrofishingpro support

### ISSUE THREAD

**Issue by dinobossytnew** [LMBishop/Quests#571]
### Description of Feature

Add the possibility of custom fishing or pyrofishingpro support.
because there are fish that are not even taken for material.
the pyro dev is very tikismiquis so it's hard to try to get him to support any plugin, 

### Reason for Addition

https://vimeo.com/884867353

### Alternative Solutions

but I know that LMB always tries to have the best compromise with everyone, it is not always possible to make everyone happy, but at least we should ask him if it is possible to put this function.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

### Other

Have a nice day =)

**Comment by Krakenied** [comment]
There is PR for that lol
https://github.com/LMBishop/Quests/pull/562
