### ISSUE TITLE
Quests " Custom heads give problems in console"

### ISSUE THREAD

**Issue by VentureStudios** [LMBishop/Quests#572]
### Description of Bug

Hi, with version 1.20.2 we need to update the heads with the new formats.

Update skulls format:
https://github.com/Angeschossen/PluginFrameworkAPI/wiki/New-Head-Textures

### Steps to Reproduce

![image](https://github.com/LMBishop/Quests/assets/70705179/e9698b79-d482-4347-81c5-fd04398da7c6)

### Environment

- Minecraft version: 1.20.2
- Server software: Pupperfish
- Quests version: 3.14.2

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
will look at it today

**Comment by VentureStudios** [comment]
Hey news?
