### ISSUE TITLE
Fabledskyblock 

### ISSUE THREAD

**Issue by payidarcraft** [LMBishop/Quests#580]
### Description of Bug

[Server thread/ERROR]: [Quests] Plugin Quests v3.14.2-3345d07 has failed to register events for class com.leonardobishop.quests.bukkit.tasktype.type.dependent.FabledSkyblockLevelTaskType because com/songoda/skyblock/api/event/island/IslandLevelChangeEvent does not exist.

### Steps to Reproduce

[Server thread/ERROR]: [Quests] Plugin Quests v3.14.2-3345d07 has failed to register events for class com.leonardobishop.quests.bukkit.tasktype.type.dependent.FabledSkyblockLevelTaskType because com/songoda/skyblock/api/event/island/IslandLevelChangeEvent does not exist.

### Environment

- Minecraft version: 1.16.5
- Server software: Paper Java
- Quests version: Quests 3.14.2 Spigot
Fabled version: 3.0.0 b7 snapshot

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by khacctin746** [comment]
i encourage you to use SuperiorSkyblock instead of FabledSkyblock.

**Comment by Krakenied** [comment]
Try with this build
https://github.com/LMBishop/Quests/actions/runs/7371538008/artifacts/1141146534
