### ISSUE TITLE
Update the %ecobosses_killing% to %ecomobs_killing%

### ISSUE THREAD

**Issue by KingCueio** [LMBishop/Quests#581]
### Description of Feature

%ecobosses_killing% is not functioning due to the new update from the EcoMobs (previously known as EcoBosses)

I would like to follow up if there's any update about the placeholder of EcoMobs.

### Reason for Addition

This is to fix the placeholder for EcoMobs

### Alternative Solutions

N/A

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

**Comment by Krakenied** [comment]
Based on my understanding from the reported issue, it seems that the problem is not caused by the Quests project

**Comment by KingCueio** [comment]
should the quests project adapt the external task type if a plugin of that external task type were to be updated?

Since the author of the quest itself made the integration to the Ecobosses: https://github.com/LMBishop/Quests/issues/521

Otherwise, if not. Then the external task type of https://quests.leonardobishop.com/task-types/ecobosses_killing-(task-type).html should only say that it will only accept before 9.50.1 version of EcoBosses.

**Comment by Krakenied** [comment]
Try using this build https://github.com/LMBishop/Quests/actions/runs/7371679436/artifacts/1141162745

**Comment by KingCueio** [comment]
Thank you! I'll be closing this issue now <3
