### ISSUE TITLE
error type quest

### ISSUE THREAD

**Issue by NixsSa2d** [LMBishop/Quests#583]
### Description of Bug

![image](https://github.com/LMBishop/Quests/assets/150930296/8bee578d-99e9-450b-8799-1985754f7397)
![image](https://github.com/LMBishop/Quests/assets/150930296/9bb444ee-5859-4074-8db4-0782e835d835)

### Steps to Reproduce

.

### Environment

- Minecraft version: 1.19.3
- Server software:Paper
- Quests version:3.14.2-3345d07

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

.

**Comment by Krakenied** [comment]
Make sure your quest is actually valid

**Comment by NixsSa2d** [comment]
YES
![image](https://github.com/LMBishop/Quests/assets/150930296/7e12ba9d-599a-402d-b705-6f20c55518fc)

**Comment by Krakenied** [comment]
Upload your quest file here or using https://pastes.dev/

**Comment by NixsSa2d** [comment]
https://pastes.dev/0d9y9bgaJR

**Comment by Krakenied** [comment]
The problem is that you're trying to use a Citizens task type while not having Citizens installed on the server

**Comment by NixsSa2d** [comment]
I got it
![image](https://github.com/LMBishop/Quests/assets/150930296/76918a96-ef09-46b2-8c2a-412a623b3a4c)

**Comment by Krakenied** [comment]
But the task type isn't somehow enabled on the server

**Comment by Krakenied** [comment]
I tested it and the quest was registered successfully after installing Citizens
