### ISSUE TITLE
Custom namespace sound support

### ISSUE THREAD

**Issue by Tuchan** [LMBishop/Quests#585]
### Description of Feature

Support for 
```
sounds:
    quest-start: "namespace:custom.sound:2:3"
    (...)
````

### Reason for Addition

When using a custom namespace in a resource pack, you must provide the full name such as `namespace:custom.sound`. Since it uses a colon, it breaks the current implementation of how the plugin parses values from the config.
https://github.com/LMBishop/Quests/blob/98e55ac17ce1d433ca0ba45ac2c03f370fcc7251/bukkit/src/main/java/com/leonardobishop/quests/bukkit/util/SoundUtils.java#L18-L28

### Alternative Solutions

Swapping colon `:` for some alternative character like vertical bar `|` might be a better idea. 
`quest-start: "namespace:quest.start|2|3"`
Although it would require everyone to change their configs...

Unfortunately, I have no idea how maintainers want to tackle this issue, so it's better to ask before making a PR.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

**Comment by Krakenied** [comment]
i think it can be easily fixed without breaking current behavior

**Comment by Krakenied** [comment]
https://github.com/LMBishop/Quests/actions/runs/7428188182
the new format for namespaced sounds is (namespace:key):pitch:volume, the old one is still supported

**Comment by Tuchan** [comment]
Works as intended, thank you!
