### ISSUE TITLE
Add all buckets for "bucketfill" & "bucketempty" tasks

### ISSUE THREAD

**Issue by NoltoxGit** [LMBishop/Quests#591]
### Description of Feature

Hello,
Would it be possible to add bucket filling/emptying for the different buckets available in the game?
- Cod in a bucket
- Salmon in a bucket
- Tropical fish in a bucket
- Pufferfish in a bucket
- Axolotl in a bucket
- Tadpole in bucket

### Reason for Addition

Add more quest diversity

### Alternative Solutions

There's no alternative.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

**Comment by Krakenied** [comment]
Will look into it today

**Comment by Krakenied** [comment]
Already in dev builds
https://quests.leonardobishop.com/task-types/bucketentity-(task-type).html

**Comment by Krakenied** [comment]
(forgot to mention the issue in the commit message lol)
