### ISSUE TITLE
Add support for ZNPCPlus

### ISSUE THREAD

**Issue by WarnDa** [LMBishop/Quests#593]
### Description of Feature

Currently plugin only support citizens for quests type citizens_deliver. But citizens isn't good in performances, and doesn't allow to do all we want (or it takes huge amount of performances)

So I'm now using zNPCsPlus, but Quests is the only plugin in my server that do not support it : 
https://www.spigotmc.org/resources/znpcsplus.109380/

I'm using the dev build on their discord, and it works very great for all other things, and consume 0.00% in spark

### Reason for Addition

Other plugins (quests plugin or not) already added support for this plugin, as it helps using NPC without having to worry about performances
Also, citizens remove support for older versions, so if they fix an issue but you aren't up to date, you can't get the fix. ZNPCsPlus support all versions without issue
### Alternative Solutions

Still use citizens, but citizens won't really fix the performances issues and just fix bugs

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

### Other
Their jenkins : https://ci.pyr.lol/job/ZNPCsPlus/
Source code : https://github.com/Pyrbu/ZNPCsPlus

**Comment by Krakenied** [comment]
Will look into it today

**Comment by NoltoxGit** [comment]
> Will look into it today

Hello,
Do you have any news about this ? It will be a verry good idea :D
