### ISSUE TITLE
Task that should work

### ISSUE THREAD

**Issue by Tobiczek** [LMBishop/Quests#607]
### Description of Bug

  stridertravel:
    type: "walking"
    distance: 1000
    mode: strider 

### Steps to Reproduce

ss

### Environment

- Minecraft version:
- Server software:
- Quests version:

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

.ssss

**Comment by Tobiczek** [comment]
Mainly, there are a few tasks that don't work (I wrote about them on discord, I made tickets on github, other people also wrote)

And I wonder if I write them out again, would there be an option to fix them?

**Comment by Krakenied** [comment]
Tested it and it works even on craftbukkit lol

**Comment by Krakenied** [comment]
https://github.com/LMBishop/Quests/assets/46192742/bf2af0ae-7832-4539-941e-f904e34ed819

Please provide reproduction steps in case you're still sure the issue exists

**Comment by Tobiczek** [comment]
Okay, it actually works now

**Comment by Tobiczek** [comment]
tasks:
  farming:
    type: "breeding"
    amount: 2
    mob: GOAT
  farming1:
    type: "milking"
    amount: 1
    mob: GOAT
    
    
Would it be possible to add options so that you can also milk goats, and not just cows?

**Comment by Tobiczek** [comment]
tasks:
  enchanting:
    type: "brewing"
    amount: 30"
    
    
In general, it works in a specific way, you put 3 bottles (turn them into cloudy) - It counts 1 amount for each action

It's best if you check it yourself, but you can do something so that it is counted only when it is taken out, so that, for example, the player finally gets 3 amounts instead of 6-9


+ To avoid the action that the player only takes out potions prepared from the wart (I can't send the video because the internet is too weak, unfortunately)

**Comment by Tobiczek** [comment]
tasks:
  enchanting:
    type: "taming"
    mob: "VILLAGER"
    amount: 4
    
I'm wondering, is it currently possible to do a quest to transform a zombie villager into a villager?
    
     It's the same process, you throw a weakening potion, give him a golden apple, etc. (In general, it would be a very nice, interesting task)

**Comment by Krakenied** [comment]
> tasks: farming: type: "breeding" amount: 2 mob: GOAT farming1: type: "milking" amount: 1 mob: GOAT
> 
> Would it be possible to add options so that you can also milk goats, and not just cows?

The feature can be added but the fact that there is no "milkable" interface in the API makes me not want to implement it lol



> tasks: enchanting: type: "brewing" amount: 30"
> 
> In general, it works in a specific way, you put 3 bottles (turn them into cloudy) - It counts 1 amount for each action
> 
> It's best if you check it yourself, but you can do something so that it is counted only when it is taken out, so that, for example, the player finally gets 3 amounts instead of 6-9
> 
> * To avoid the action that the player only takes out potions prepared from the wart (I can't send the video because the internet is too weak, unfortunately)

The best way to prevent abusing the quest by players is specifying the brewing ingredient



> tasks: enchanting: type: "taming" mob: "VILLAGER" amount: 4
> 
> I'm wondering, is it currently possible to do a quest to transform a zombie villager into a villager?
> 
> ```
>  It's the same process, you throw a weakening potion, give him a golden apple, etc. (In general, it would be a very nice, interesting task)
> ```

There is no such a thing as taming villagers - you can breed them but villagers breed kinda automagically so we cant really check who bred the villagers

Transforming zombie villagers has an event in the API but it doesn't let us detect who cured the villager. Also, there is already a feature request for that (https://github.com/LMBishop/Quests/issues/545)

**Comment by Tobiczek** [comment]
![image](https://github.com/LMBishop/Quests/assets/114435370/84813e64-c4ac-4abf-afab-b6429439d1b8)
![image](https://github.com/LMBishop/Quests/assets/114435370/0b68e897-ebe8-4722-b972-fb82f9e43d55)

**Comment by Krakenied** [comment]
PyroFishingPro doesn't have events for these things. Also, I think killing crabs can be done with a mobkilling task
![image](https://github.com/LMBishop/Quests/assets/46192742/0fbacb4a-511d-49de-8e61-183ef7e58d42)

**Comment by Tobiczek** [comment]
![image](https://github.com/LMBishop/Quests/assets/114435370/2a11833e-c891-4198-b080-ab80a6702ea0)
![image](https://github.com/LMBishop/Quests/assets/114435370/6f669204-4ef9-45ea-b78a-53b8c50deb78)

**Comment by Krakenied** [comment]
> ![image](https://private-user-images.githubusercontent.com/114435370/306258354-2a11833e-c891-4198-b080-ab80a6702ea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzM5MTQsIm5iZiI6MTcwODQzMzYxNCwicGF0aCI6Ii8xMTQ0MzUzNzAvMzA2MjU4MzU0LTJhMTE4MzNlLWM4OTEtNDE5OC1iMDgwLWFiODBhNjcwMmVhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxMjUzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzQwNzI5YjA1N2VkNDYyMDE3OGRjZGJiNmQ2ZDUwZjJkZDUzZmY1MDkzMDQwMzQ0MGQ0NGQ1MTM1OWFiZDc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U0Iqf9N-MNzFgOF0OIhC9IeNUXyNh2xyQ6sMk41jXxE) ![image](https://private-user-images.githubusercontent.com/114435370/306258373-6f669204-4ef9-45ea-b78a-53b8c50deb78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzM5MTQsIm5iZiI6MTcwODQzMzYxNCwicGF0aCI6Ii8xMTQ0MzUzNzAvMzA2MjU4MzczLTZmNjY5MjA0LTRlZjktNDVlYS1iNzhhLTUzYjhjNTBkZWI3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxMjUzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTJjNzM2MTg1ZGU4NjQ3ZTU0MDJiNTNlZjExZTRlYjE5MTQ4ZmI4Y2E3ZGNkNjVlZWU3NmQxNzJmMDRhMTMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2kJiOUWw1u-ze4-xoDQzZK69cDp7bKhRGtZlNx0RVB4)

just a mistake in the docs
