### ISSUE TITLE
Quest progress still resetting after user logs off

### ISSUE THREAD

**Issue by FourNineRugz** [LMBishop/Quests#61]
**Description of Error**
If a user has more than one quest active, and they complete one quests, it resets the others, but only after they log off.

**To Reproduce**
https://i.imgur.com/KiAfGNZ.png

**Screenshots**
https://i.imgur.com/KiAfGNZ.png

**Server (please complete the following information):**
- Paper 1.15.1

**Plugin (please complete the following information):**
- Quests 2.6.3

**Comment by VorteXNation** [comment]
Actually this is kinda weird...

![image](https://user-images.githubusercontent.com/57765841/71864458-1d539780-3100-11ea-92de-231c14fab5a3.png)

They are suposed to be in order (Red = Not avaiable; Green = Completed)

Anyways... Bug confirmed, if it's possible can you give this bug major priority? I think this is a critical error that needs to be fixed as soon as possible.

By "it resets the others" at least on my case it resets ALL player data (Happened like 6 times) the only exception was the image above that happened a few minutes ago.

**Comment by LMBishop** [comment]
I cannot seem to reproduce any of the errors given, here's the steps I've tried:

- starting 2 quests
- getting progress on one quest
- completing the other quest
- relogging

when I connect back, my progress remains unaffected.

Could you possibly elaborate on what conditions you have? Is 'quest-autostart' enabled?

**Comment by nicuch** [comment]
The data resets after a few certain time (sometimes like 5 minutes). Fixed in #63
