### ISSUE TITLE
Bug with the latest build

### ISSUE THREAD

**Issue by NoltoxGit** [LMBishop/Quests#619]
### Description of Bug

Hello,
I just noticed that with the latest version of the plugin in actions ([currently this one](https://github.com/LMBishop/Quests/actions/runs/8022981776)), the "0" are replaced by "null" in the internal placeholders of quests, for example in this one: `{questtttt:progress}`.

### Steps to Reproduce

Try with this quest and see :
https://gist.github.com/NoltoxGit/376c9ef5beb41c0eae7b12ac43e5ecc9

### Environment

- Minecraft version: `git-Purpur-2149 (MC: 1.20.4)*`
- Server software: `Purpur 1.20.4`
- Quests version: `3.15-486b3d6`

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
It's not latest build

These are latest ones
![image](https://github.com/LMBishop/Quests/assets/46192742/e3b0885e-8a6b-47a3-b456-1a6090fa09af)

This one is a build from PR that hasn't been merged yet
