### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by vxkShelby** [LMBishop/Quests#626]
### Description of Bug

04.03 12:52:51 [Server] INFO [Quests] Enabling Quests v3.15-b636bef
04.03 12:52:51 [Server] INFO [Quests] Running server scheduler: FoliaServerScheduler
04.03 12:52:51 [Server] INFO [Quests] Initialising storage provider 'yaml'
04.03 12:52:51 [Server] INFO [Quests] Your server is running version 1.20
04.03 12:52:51 [Server] ERROR [Quests] Could not set color for the initialized boss bar implementation, using default instead!
04.03 12:52:51 [Server] INFO java.lang.IllegalStateException: color section is missing
04.03 12:52:51 [Server] INFO at com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.loadConfig(BossBar_Bukkit.java:96) ~[Quests-3.15-b636bef.jar:?]
04.03 12:52:51 [Server] INFO at com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.<init>(BossBar_Bukkit.java:37) ~[Quests-3.15-b636bef.jar:?]
04.03 12:52:51 [Server] INFO at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.setBossBarHandle(BukkitQuestsPlugin.java:680) ~[Quests-3.15-b636bef.jar:?]
04.03 12:52:51 [Server] INFO at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onEnable(BukkitQuestsPlugin.java:308) ~[Quests-3.15-b636bef.jar:?]
04.03 12:52:51 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
04.03 12:52:51 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-318]
04.03 12:52:51 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-318]
04.03 12:52:51 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
04.03 12:52:51 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-318]
04.03 12:52:51 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-318]
04.03 12:52:51 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-318]
04.03 12:52:51 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-318]
04.03 12:52:51 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-318]
04.03 12:52:51 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
04.03 12:52:51 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
04.03 12:52:51 [Server] INFO at java.lang.Thread.run(Thread.java:840) ~[?:?]
04.03 12:52:51 [Server] ERROR [Quests] Could not set style for the initialized boss bar implementation, using default instead!
04.03 12:52:51 [Server] INFO java.lang.IllegalStateException: style section is missing
04.03 12:52:51 [Server] INFO at com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.loadConfig(BossBar_Bukkit.java:96) ~[Quests-3.15-b636bef.jar:?]
04.03 12:52:51 [Server] INFO at com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.<init>(BossBar_Bukkit.java:40) ~[Quests-3.15-b636bef.jar:?]
04.03 12:52:51 [Server] INFO at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.setBossBarHandle(BukkitQuestsPlugin.java:680) ~[Quests-3.15-b636bef.jar:?]
04.03 12:52:51 [Server] INFO at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onEnable(BukkitQuestsPlugin.java:308) ~[Quests-3.15-b636bef.jar:?]
04.03 12:52:51 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
04.03 12:52:51 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-318]
04.03 12:52:51 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-318]
04.03 12:52:51 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
04.03 12:52:51 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-318]
04.03 12:52:51 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-318]
04.03 12:52:51 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-318]
04.03 12:52:51 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-318]
04.03 12:52:51 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-318]
04.03 12:52:51 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
04.03 12:52:51 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
04.03 12:52:51 [Server] INFO at java.lang.Thread.run(Thread.java:840) ~[?:?]
04.03 12:52:51 [Server] INFO [Quests] Metrics started. This can be disabled at /plugins/bStats/config.yml.

### Steps to Reproduce

Console Errors

### Environment

- Minecraft version: 1.20.2 
- Server software: Spigot Paper
- Quests version: 3.15

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
Update your config

**Comment by vxkShelby** [comment]
what do you mean how to update config

**Comment by Krakenied** [comment]
https://github.com/LMBishop/Quests/blob/master/bukkit/src/main/resources/resources/bukkit/config.yml

Add missing options and sections to your config

**Comment by vxkShelby** [comment]
i will try

**Comment by Krakenied** [comment]
You can use https://diffchecker.com to make it easier

**Comment by vxkShelby** [comment]
now its okay ... tnx
