### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by daniel-skopek** [LMBishop/Quests#635]
### Description of Bug

https://pastebin.com/raw/X2M8jkLh

### Steps to Reproduce

Unfortunately, I don't know.

### Environment

- Minecraft version: 1.20.1
- Server software: UniverseSpigot
- Quests version: v3.15-b636bef

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
Is your ZNPCsPlus up to date?

**Comment by Krakenied** [comment]
Try with latest build https://ci.pyr.lol/job/ZNPCsPlus/
