### ISSUE TITLE
Updating Error

### ISSUE THREAD

**Issue by KhrysAK47** [LMBishop/Quests#659]
### Description of Bug

Updated from older version to newer, and got this error on startup: https://pastebin.com/Y8WJN5pP

### Steps to Reproduce

Update from older version to newest

### Environment

- Minecraft version: 1.20.4
- Server software: Paper
- Quests version: v3.15

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
Update your config
https://github.com/LMBishop/Quests/blob/5fdb2756968534403e1797a7851342f60eeaa349/bukkit/src/main/resources/resources/bukkit/config.yml#L43-L53
