### ISSUE TITLE
Random console error

### ISSUE THREAD

**Issue by DarkyG2** [LMBishop/Quests#664]
### Description of Bug

Getting this console error when doing quests: https://pastebin.com/wjwdLGzW

### Steps to Reproduce

1. Be on 1.20.4 folia
2. have a quests where you need to mine something that has a coreprotect hook
3. do the quest
4. error

### Environment

- Minecraft version: 1.20.4
- Server software: Folia
- Quests version: 3.15-2869ab1

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

I would love to use the other hook that could replace coreprotect but it doesn't work under folia :(

**Comment by Krakenied** [comment]
It's a CoreProtect issue
https://github.com/PlayPro/CoreProtect/issues/481

**Comment by Krakenied** [comment]
Tracked on https://github.com/LMBishop/Quests/issues/707
