### ISSUE TITLE
'null' cooldown.

### ISSUE THREAD

**Issue by KhrysAK47** [LMBishop/Quests#669]
### Description of Bug

Cooldown of quests sometimes shows 'null' instead of a number or 0.

### Steps to Reproduce

I am uncertain about this, as it happens randomly.

### Environment

- Minecraft version: 1.20.4
- Server software: Paper 1.20.4
- Quests version: v3.15

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by KhrysAK47** [comment]
Here is the data file for a player with broken cooldown or the null problem:

https://pastebin.com/gKePWAEP

**Comment by Krakenied** [comment]
Where is `null` shown

**Comment by KhrysAK47** [comment]
As the placeholderapi result of when it was completed or the cooldown.

**Comment by Krakenied** [comment]
Which placeholder especially

**Comment by KhrysAK47** [comment]
%quests_quest:Quest1_cooldown% for example.
