### ISSUE TITLE
Console errors spam

### ISSUE THREAD

**Issue by car1ot** [LMBishop/Quests#67]
I'm using 1.15 paper mc.
Errors connected with events.
https://i.imgur.com/nM0ZxNN.png

**Comment by Exillium313** [comment]
Having a same/similar issue, posting here because I believe its the same, my pastebin might have more info needed to resolve?

https://pastebin.com/zMRYtW7H

**Comment by nicuch** [comment]
As I said on #70 (and the reason is there too), can you also please provide a list of the plugins you're using?

**Comment by nicuch** [comment]
Please try this version: https://github.com/nicuch/Quests-1/releases/tag/2.8-Alpha
You can see the changes here: https://github.com/nicuch/Quests-1/commit/8430035d2f9f8876981bda0e4fc57ae870ddc29d
Please report if any errors shows up.

**Comment by Exillium313** [comment]
Will upload this later and report back, however it sometimes takes days between getting the error.

**Comment by nicuch** [comment]
> Will upload this later and report back, however it sometimes takes days between getting the error.

I think now it will not throw an error, as I delayed for 1 tick the removal of qPlayer
