### ISSUE TITLE
Add MoneyPouch 1.20.6 support

### ISSUE THREAD

**Issue by Raidware** [LMBishop/Quests#676]
### Description of Feature

in order to work with mc 1.20.6 u need update plugin. i tried to writr everywhere.

### Alternative Solutions

<version>1.20.6-R0.1-SNAPSHOT</version>

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

**Comment by Krakenied** [comment]
not related to Quests project
