### ISSUE TITLE
1.8 - 1.13 ID support

### ISSUE THREAD

**Issue by CryLegende** [LMBishop/Quests#68]
**Description of Feature**
The plugin only needs IDs 1.8 - 1.13 to make it compatible with these versions, why not do it ? It's really easy to do ^^
Many servers are still in 1.12 or 1.8, it's sad for them not to be able to use your plugin just for that :(
IDs 1.8 - 1.13 still work except those with data (like STONE:2)

My server is in 1.12 and I would really like to update your plugin to the latest version to get the placeholders because it is a very useful feature :)

Thank you for your help ^^

**Comment by nicuch** [comment]
You can allways use the old (1.12.2) legacy ids from here: https://helpch.at/docs/1.12.2/index.html?org/bukkit/Material.html
The "data" is already an option, but I'm not really sure it works or not.

**Comment by CryLegende** [comment]
The problem is that the data is not working

**Comment by nicuch** [comment]
I've just look at the data... aparently someone (mhm LMBishop) just ignored the data.
`int data = 0;`

**Comment by CryLegende** [comment]
So the plugin is not 1.12 compatible just for that? :'(

**Comment by nicuch** [comment]
> So the plugin is not 1.12 compatible just for that? :'(

I'll see what can I do 😋

**Comment by CryLegende** [comment]
Thank you so much <3

**Comment by nicuch** [comment]
You can download the Alpha 2.8 from here:
https://github.com/nicuch/Quests-1/releases/tag/2.8-Alpha
Please keep in mind, that this one also contains mysql support (that currently doesn't do anything).
You can see the changes here: https://github.com/nicuch/Quests-1/commit/c166c516b35b27873a9ef39f41729738ca26ce4d
PS: you have to add `data: id` where the type is. Please report any issues.

**Comment by CryLegende** [comment]
It works fine for quests but not in config.yml ^^'

**Comment by nicuch** [comment]
> It works fine for quests but not in config.yml ^^'

Okay, I'll see again what I can do. :)

**Comment by nicuch** [comment]
Please try this version (again): https://github.com/nicuch/Quests-1/releases/tag/2.8-Alpha
You can see the changes here: https://github.com/nicuch/Quests-1/commit/8430035d2f9f8876981bda0e4fc57ae870ddc29d
Please report if any errors shows up.

**Comment by CryLegende** [comment]
It seems to work fine, thank you for your help ! ^^
