### ISSUE TITLE
With Default Config Taking Error on Startup

### ISSUE THREAD

**Issue by zikehalil3535** [LMBishop/Quests#681]
### Description of Bug

![Screenshot_1](https://github.com/LMBishop/Quests/assets/88826436/08a50fd6-85b3-40df-bd12-71d97ad70f42)

### Steps to Reproduce

I get error with default config on startup.

### Environment

- Minecraft version: 1.20.6
- Server software: PURPUR
- Quests version: Latest

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
Use latest dev build

**Comment by ShadowwwWalkerr** [comment]
I have the same problem. Can someone help me? :(

**Comment by ShadowwwWalkerr** [comment]
> Use latest dev build

give us a link with the latest dev build ?
