### ISSUE TITLE
- & _ is not allowed in latest devbuild, the support was been added in last release

### ISSUE THREAD

**Issue by itsme-to** [LMBishop/Quests#683]
### Description of Bug

In the latest devbuild, you can't use anymore `_` & `-` inside quest id.
It's maybe related to that commit, https://github.com/LMBishop/Quests/commit/aea66501e1019162bb670aa0f97761f637bae847

The support of `-` and `_` was added on this one
https://github.com/LMBishop/Quests/commit/a184e76053aa55df4fb5f156fa6c5c0ecb8f811d

### Steps to Reproduce

Use the latest devbuild and try to create a quest with `_` or `-` in the name

### Environment

- Minecraft version: 1.19.4
- Server software: Paper
- Quests version: Devbuild from github

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by itsme-to** [comment]
@svaningelgem if you want to make this really nice feature back again <3

**Comment by Krakenied** [comment]
`_` can't be supported because it wont work with placeholders

**Comment by svaningelgem** [comment]
> `_` can't be supported because it wont work with placeholders

Is it possible to get a bit of insight on how this placeholders work together with `_`? So I can maybe think of another way around it (if at all possible)?

**Comment by itsme-to** [comment]
![CleanShot 2024-06-27 at 15 41 36](https://github.com/LMBishop/Quests/assets/43671109/52b7c84f-4c6c-4a45-9da9-974ed93d27e9)

Yeah don't working fine currently

**Comment by Krakenied** [comment]
placeholder API hook uses `_` delimiter for splitting

**Comment by Krakenied** [comment]
maybe `-` can be supported safely, i need to check that though

**Comment by itsme-to** [comment]
> maybe `-` can be supported safely, i need to check that though

Yes, without too much trouble, and it's still much simpler visually.

![CleanShot 2024-06-28 at 12 41 36@2x](https://github.com/LMBishop/Quests/assets/43671109/a39659d8-ecbf-4213-ac6a-bd75f8f0e710)
![CleanShot 2024-06-28 at 12 41 40@2x](https://github.com/LMBishop/Quests/assets/43671109/bfbb3558-606d-4814-adea-1e4fd5c37edd)
It's way better

**Comment by itsme-to** [comment]
In the latest release, Papi placeholders work well with `-`, so it's really just the check that's causing issues in the latest dev build.

![CleanShot 2024-06-28 at 12 44 39](https://github.com/LMBishop/Quests/assets/43671109/956abc90-3311-4fb8-b6bf-d1cb47aa185c)

**Comment by Krakenied** [comment]
Ill try implementing it in a more proper way

**Comment by Krakenied** [comment]
Currently I will give you a temporary fix, however it still needs to be fixed in a more proper way so we can allow `_` usage as well lol
[artifacts.zip](https://github.com/user-attachments/files/16045247/artifacts.zip)

**Comment by itsme-to** [comment]
Great it's work fine, can you add it to the dev build ? So my client can use it as well ?

**Comment by itsme-to** [comment]
Oh great, I didn't see it

**Comment by t4ba** [comment]
possible to add _  back ?

**Comment by Krakenied** [comment]
> possible to add _ back ?

But there is no way to make it work properly with placeholders
