### ISSUE TITLE
Any plans regarding 1.21

### ISSUE THREAD

**Issue by mihiblu** [LMBishop/Quests#684]
### Description of Feature

I wanted to ask if the update for 1.21 is being prepared or will it take some time before it is available?

### Alternative Solutions

Startup error: https://mclo.gs/58mF8bg 
Then disable

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

**Comment by Krakenied** [comment]
It's already supported in dev builds (for example https://github.com/LMBishop/Quests/actions/runs/9657566122)

**Comment by mihiblu** [comment]
> It's been supported for at least 2 months - dev builds can be downloaded from the actions tab (for example https://github.com/LMBishop/Quests/actions/runs/9657566122), just LMBishop is kinda inactive and haven't released a new version yet.

Ok, thanks a lot! It works fine from what I tested your last build.
