### ISSUE TITLE
Please add 1.20.6 support

### ISSUE THREAD

**Issue by Storm772** [LMBishop/Quests#686]
### Description of Feature

Please make it so the plugin works on 1.20.6!!!

### Reason for Addition

I have a server on 1.20.6 and want to use this plugin.

### Alternative Solutions

I tryed no other solutions

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

**Comment by Krakenied** [comment]
It's been supported for at least 2 months - dev builds can be downloaded from actions tab
