### ISSUE TITLE
Keep quest GUI open when accepting quests

### ISSUE THREAD

**Issue by FourNineRugz** [LMBishop/Quests#687]
### Description of Feature

Keep quest GUI open when accepting quests

### Reason for Addition

It is very inconvenient to have to keep opening the menu

### Alternative Solutions

None

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

**Comment by Krakenied** [comment]
There is an option. Also make sure you config is up to date. https://github.com/LMBishop/Quests/blob/master/bukkit/src/main/resources/resources/bukkit/config.yml
```yml
  # Close the UI automatically when a quest is accepted
  gui-close-after-accept: true
```
