### ISSUE TITLE
Sweet berries bug

### ISSUE THREAD

**Issue by VentureStudios** [LMBishop/Quests#689]
### Description of Bug

Hey I found a bug, if you put sweetberrier it also counts the beets, pumpkins, melons etc....

### Steps to Reproduce

Start the quest that says to farm sweet berries and grow melons, pumpkins or beets and you'll see that it counts those too.

### Environment

- Minecraft version: 1.20.4
- Server software: 1.20.4
- Quests version: dev build #806

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
(answered you on the Discord) - close the issue if it works properly
