### ISSUE TITLE
Error smithing task type if no specify items

### ISSUE THREAD

**Issue by leogianfagna** [LMBishop/Quests#694]
### Description of Bug

We can see in the wiki that the "item" is not necessary:
![image](https://github.com/user-attachments/assets/c587dab0-0416-4f2f-a755-b463ae406cc7)
![image](https://github.com/user-attachments/assets/dc6ef680-eec0-4abf-94c4-ba06ef887362)

But if you create a quest without specifying the item, it won't work:
![image](https://github.com/user-attachments/assets/1714fa3c-8aba-4356-ba34-947ea4068493)
![image](https://github.com/user-attachments/assets/aeee835a-99fa-4ab8-a7e5-39047281209e)

### Steps to Reproduce

Try to run this quest:
```YML
  objetivo-1:
    type: "smithing"
    amount: 70
    mode: "trim"
    exact-match: false
```

I even tried to insert `item: NETHERITE_HELMET` with `exact-match: false` but only count the helmets.

### Environment

- Minecraft version: 1.20.4
- Server software: Purpur
- Quests version: 3.15-b636bef

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
Try with latest build from my PR (https://github.com/LMBishop/Quests/actions/runs/9919569114) - probably also fixed on master 5 months ago

**Comment by Krakenied** [comment]
And if you use Java 17 then update it to 21 (it should be compatible with most stuff including 1.20.4 server) or use the downgraded-17 Quests jar with `--add-opens=java.base/java.text=ALL-UNNAMED` added to your startup script directly after `java`

**Comment by leogianfagna** [comment]
Worked with dev build. I'm not used to using dev builds, but i will use it. Is java 21 required?

**Comment by Krakenied** [comment]
Java 21 is required for the non-downgraded Quests JAR (as it's compiled with 1.21 API support), however you can use the downgraded version (with 17 in filename) - it requires you to start the server with the --add-modules I mentioned above though

**Comment by Krakenied** [comment]
However 1.20.4 and most plugins are compatible with Java 21 so I would consider just upgrading it as an easier solution

**Comment by leogianfagna** [comment]
thanks for the great support
