### ISSUE TITLE
1.21 Update Request

### ISSUE THREAD

**Issue by AccioAce** [LMBishop/Quests#697]
### Description of Bug

Hello there,

I would like to report that latest quest version 3.15 doesn't work for 1.21

### Steps to Reproduce

Needing update to 1.21

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
It's been supported for at least 2 months - dev builds can be downloaded from the actions tab (for example https://github.com/LMBishop/Quests/actions/runs/9919569114), just LMBishop is kinda inactive and haven't released a new version yet.

**Comment by AccioAce** [comment]
> It's been supported for at least 2 months - dev builds can be downloaded from the actions tab (for example https://github.com/LMBishop/Quests/actions/runs/9919569114), just LMBishop is kinda inactive and haven't released a new version yet.

Ah I see. Is this SRC of the latest version? I don't seem to see the jar beside the JDK file.

**Comment by Krakenied** [comment]
This is the latest build from this PR https://github.com/LMBishop/Quests/pull/671

**Comment by AccioAce** [comment]
Thanks!
