### ISSUE TITLE
Progress bar not working for some quest types.

### ISSUE THREAD

**Issue by srthd** [LMBishop/Quests#7]
The progress bar for the inventory quest type does not update.
![image](https://user-images.githubusercontent.com/38537845/39257214-e7eb4642-48a8-11e8-9191-af326107a737.png)

**Comment by fatpigsarefat** [comment]
There's not much I can show without making the Inventory task type horribly inefficient, this is why the default config shows whether it's complete or not.

**Comment by fatpigsarefat** [comment]
Maybe, when I get the time to.

**Comment by SzlugPL** [comment]
How do you change to make progress count? 
 wheat:
    type: "inventory"
    item: WHEAT
    amount: 32
display:
  name: "&cFarmer (1)"
  lore-normal:
    - "&7Aby ukonczyc misje musisz:"
    - "&7 - Zebrac 32 przeniscy."
    - ""
    - "&7Nagroda:"
    - "&7 - 30 diamonds."
    - "&7 - 10$"
  lore-started:
    - ""
    - "&7Twoj obecny postep:"
    - "&7 - {wheat:progress}/32
