### ISSUE TITLE
Quests are allowing any block to be placed/mined, rather than a specific block

### ISSUE THREAD

**Issue by SirPorkus** [LMBishop/Quests#704]
### Description of Bug

Quests allow any block to be mined/placed, regardless of if I have defined a certain block in the config. For example, in one quest (Place 128 Cherry Planks), placing a Block of Amethyst is counting towards the overall process. Same with a mine andesite quest, any block counts towards the progress.

### Steps to Reproduce

1. Create a blockplace quest
2. Define in the Quest config: 'blockplacecertain' and 'cherry_planks' as well as an amount.
3. Restart the server and load the Quest.
4. Start the quest, place Amethyst Blocks, and check if it counts to the progress

### Environment

- Minecraft version: 1.20.4
- Server software: git-Paper-497 (MC: 1.20.4)
- Quests version: 3.15-b636bef

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
Show your quest file

**Comment by SirPorkus** [comment]
> Show your quest file
Here we go:
https://paste.helpch.at/pifecofopu.yaml

**Comment by Krakenied** [comment]
Take a look at the docs - in this task type you need to specify `block` and not the `item`

**Comment by SirPorkus** [comment]
Ty!
