### ISSUE TITLE
1.20.4 / 3.15 - MythicMobs kill tasks do NOT work

### ISSUE THREAD

**Issue by Kainzo** [LMBishop/Quests#705]
### Description of Bug

MythicMobs kill tasks do NOT work

### Steps to Reproduce

Add in the wiki provided kill task for mythicmobs and set the mob ID

### Environment

- Minecraft version: 1.20.4
- Server software: paper
- Quests version: 3.15

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Kainzo** [comment]
Apologies,
The progress does not increase, I can kill the WIT_WARRIOR mob I have created and it never updates. 

I'm assuming when MythicMobs updated to the new API 5.5+? that this has caused some issues. 

It's possible that I am using the wrong type, but I didnt think so.

**Comment by Krakenied** [comment]
Show please your quest tasks section

**Comment by Krakenied** [comment]
`I'm assuming when MythicMobs updated to the new API 5.5+? that this has caused some issues.`

There were no API changes and it works correctly on both 5.2 and 5.7.1 (just tested).

You can try using debugger `/q a debug quest <the quest id> self` and killing the mobs (some debug info will appear on your chat)

**Comment by Kainzo** [comment]
I will try this, appreciate ya!
