### ISSUE TITLE
Unable to set value console spam bug

### ISSUE THREAD

**Issue by moonies44** [LMBishop/Quests#706]
### Description of Bug

Hello! My issue is regarding a spamming error in my console 

**java.lang.IllegalStateException: Unable to set value of field private final net.minecraft.network.chat.numbers.NumberFormat net.minecraft.network.protocol.game.PacketPlayOutScoreboardObjective.g**

I have no idea which this could indicate.

### Steps to Reproduce

No idea, sorry - it seems to just randomly happen, possibly when they login when their file is loaded?

### Environment

- Minecraft version: 1.20.4 paper
- Server software: paper
- Quests version: Quests version 3.15-b636bef

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

please see console logs here from my paste
https://mclo.gs/iTCNoRn

**Comment by Krakenied** [comment]
Its scoreboard issue

**Comment by moonies44** [comment]
> Its scoreboard issue

Thank you for your reply, what should i do on my end to resolve this? I use the plugin animatedscoreboard to show a menu on the side of the screen when in the server, is it that?

**Comment by Krakenied** [comment]
Not sure what exactly is causing that - it can be also caused by wrong ProtocolLib version. AnimatedScoreboard shouldn't cause issues - I use it on my server and it works

**Comment by moonies44** [comment]
> Not sure what exactly is causing that - it can be also caused by wrong ProtocolLib version. AnimatedScoreboard shouldn't cause issues - I use it on my server and it works. Maybe it's your ASb config?

what in the config should i be looking for that triggers this error?

**Comment by Krakenied** [comment]
It's not a config issue - probably your ProtocolLib version is wrong

**Comment by moonies44** [comment]
> It's not a config issue - probably your ProtocolLib version is incompatible with your server version. It's just a plugin sending invalid scoreboard number format. Thus I can't be sure about the exact cause.

i definitely a valid version my server is 1.20.4, and im using

Use the [latest release](https://github.com/dmulloy2/ProtocolLib/releases/tag/5.2.0) for 1.8 through 1.20.4 so that can't be the cause either

**Comment by Krakenied** [comment]
Wait but, I missed that one, there is also Oraxen in the log:

<html>
<body>

java.lang.IllegalStateException: Unable to set value of field private final net.minecraft.network.chat.numbers.NumberFormat net.minecraft.network.protocol.game.PacketPlayOutScoreboardObjective.g
--
227 | at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.set(DefaultFieldAccessor.java:44)
228 | at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:361)
229 | at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:324)
230 | at oraxen-1.178.0.jar//io.th0rgal.oraxen.font.packets.ScoreboardPacketListener.onPacketSending(ScoreboardPacketListener.java:22)


</body>
</html>
