### ISSUE TITLE
add the ability to specify crop age to farming tasks 

### ISSUE THREAD

**Issue by Foxshot21** [LMBishop/Quests#711]
### Description of Feature

add the ability to specify crop age to farming tasks 

### Reason for Addition

currently creating a quest if a player farms a seed they just planted it counts towards the quest completed because it is not checking if crop is of the age 7 

### Alternative Solutions

tasks:
  harvest:
    type: "farming"
    amount: 500
    block: "POTATOES"
      #add this section
      age: 7
      
      this ability would allow it to check if the crop is of the age specified 

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

### Other

currently running plugin on 1.21 with no other issues as of now

**Comment by Krakenied** [comment]
But it's checking the age
