### ISSUE TITLE
PlayerExpChangeEvent bug console spam

### ISSUE THREAD

**Issue by FourNineRugz** [LMBishop/Quests#72]
**Description of Error**
Quests seems to have a problem with a PlayerExpChangeEvent.

**To Reproduce**
Not sure, but appears to be related to experience gain with Quests.

**Server (please complete the following information):**
 - Minecraft Version: 1.15.1
 - Mod Name: Paper Spigot

**Plugin (please complete the following information):**
 - Version: 2.8

**Comment by nicuch** [comment]
Can you also post the console spam?
