### ISSUE TITLE
blockshearing with bee nest doesn't work anymore

### ISSUE THREAD

**Issue by leogianfagna** [LMBishop/Quests#729]
### Description of Bug

I always used the code below in 1.20 servers but now I updated to 1.21 and also the quests plugin and this quest isn't working anymore.

I made another test with no plugins (just quests) and is not working as well.

### Steps to Reproduce

```yml
tasks:
  objetivo-1:
    type: "blockshearing"
    amount: 25
    block: BEE_NEST
```

Use `/setblock ~ ~ ~ minecraft:bee_nest[honey_level=5]` for testing

### Environment

- Minecraft version: 1.21.1
- Server software: Purpur 
- Quests version: 3.15.2-b216e2b

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

I'm on latest of spigot version but not the dev.

**Comment by Krakenied** [comment]
Unable to reproduce

https://github.com/user-attachments/assets/0cdd9504-7701-4583-b9fb-703b46f3fa72
```
This server is running Paper version 1.21.1-110-master@6d7a438 (2024-09-28T22:14:12Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
```
```
3.15.2-3d75d13
```
