### ISSUE TITLE
not work latests version for 1.20.4

### ISSUE THREAD

**Issue by kurkinsnetwork** [LMBishop/Quests#730]
### Description of Bug

https://prnt.sc/rdeYOE_GOLkW

### Steps to Reproduce

not work

### Environment

- Minecraft version: 1.20.4
- Server software: purpur
- Quests version: Quests-3.15.2-b216e2b

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
Update your Java to 21

**Comment by Krakenied** [comment]
Alternatively you can use the Quests variant downgraded to Java 17 - but it doesn't make any sense as 1.20.4 server software fully supports Java 21.
