### ISSUE TITLE
How do I add stuff in quotes in rewards option?

### ISSUE THREAD

**Issue by Jufkenzi** [LMBishop/Quests#74]
Ideally I would type this command:
...
rewards: 
- "/give {player} minecraft:diamond_pickaxe{Enchantments:[{id:"minecraft:efficiency",lvl:6},{id:"minecraft:fortune",lvl:3},{id:"minecraft:unbreaking",lvl:3},{id:"minecraft:mending",lvl:1}]} 1"
...

But this doesn't work.
Probably because of quotes inside quotes which simply won't work and I understand that.
How do I do this properly? I also tried putting backslashes in front of quotes after the first one and before last one.

Any help would be appreciated.
Everything else works perfectly tho. :)

**Comment by nicuch** [comment]
escaping should be done like this
"When you're using double quotes, they look like \"this\""

"/give {player} minecraft:diamond_pickaxe{Enchantments:[{id:\"minecraft:efficiency\",lvl:6},{id:\"minecraft:fortune\",lvl:3},{id:\"minecraft:unbreaking\",lvl:3},{id:\"minecraft:mending\",lvl:1}]} 1"

**Comment by Jufkenzi** [comment]
ok thanks for help will try now

**Comment by Jufkenzi** [comment]
Yes it works.
And / should not be used at the start,
I already tried your method before but it didn't work because of / at the start.
Works fine without /.
Ty for help
