### ISSUE TITLE
Block Tracking does not work

### ISSUE THREAD

**Issue by Mithranduil** [LMBishop/Quests#742]
### Description of Bug

Block Tracking of Blocks does not work

### Steps to Reproduce

Place an Block to ground, use the Krakend BlockTracker or from https://github.com/Flo0/PlayerBlockTracker, use an quest for that block and break it, it counts for the quest.

### Environment

- Minecraft version: 1.21.1.
- Server software: PurPur- 1.21.1.
- Quests version: 3.15.2.-b216e3b

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
Show your task config

**Comment by Mithranduil** [comment]
my what?

**Comment by Krakenied** [comment]
tasks section from your quest file

**Comment by Mithranduil** [comment]
tasks:
  farm1:
    type: "blockbreakcertain"
    amount: 640
    block: ANDESITE

**Comment by Krakenied** [comment]
You need to add the block tracker option
https://quests.leonardobishop.com/task-types/blockbreak-(task-type).html
