### ISSUE TITLE
No se instala el pluguin 

### ISSUE THREAD

**Issue by SrMaruchans** [LMBishop/Quests#748]
### Description of Bug

Agregue el pluguin a la carpeta /pluguin de mi host e inicie, pero luego reviso y el pluguin no lo lee, al momento de escribir el comando /pluguins me lo marca en rojo, ya revise y si tengo los requerimientos y dependencias en forma, el pluguin crea la carpeta de Quest pero no lo corre. Qué podría ser?

![IMG_0812](https://github.com/user-attachments/assets/89911618-91e5-4b61-8c97-36acd2bc839e)

### Steps to Reproduce

Instale el pluguin en la carpeta /pluguin de mi server y ejecute el inicio.

### Environment

- Minecraft version:
- Server software:
- Quests version:

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

Tengo la version de Minecraft 1.21.3 y Java 21

**Comment by Krakenied** [comment]
Please add missing environment details and attach server startup log
