### ISSUE TITLE
[Suggestion] Add "Table_Prefix" in config

### ISSUE THREAD

**Issue by NoltoxGit** [LMBishop/Quests#749]
### Description of Feature

Hello,
Is it possible to add "`Table_Prefix: quests_`" in the database config please? :)

### Reason for Addition

If I can give my table a personalized name, I'll be able to find it better in my database!

### Alternative Solutions

Any

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this request is unique and a similar issue is not currently open

**Comment by Krakenied** [comment]
It's already supported
https://github.com/LMBishop/Quests/blob/6e5353755f4a394a2d1db6c08f102d9fe166c5fb/bukkit/src/main/java/com/leonardobishop/quests/bukkit/storage/MySqlStorageProvider.java#L130
