### ISSUE TITLE
blockbreak quests are not counting blocks when using AutoSmelt

### ISSUE THREAD

**Issue by AlFr3on111** [LMBishop/Quests#750]
### Description of Bug

when you try to do a mining quest using AutoSmelt plugin it will not count the blocks that you break it

AutoSmelt plugin is a plugin that make players mine ores and get the items smelted from ore to ingot
plugin: https://www.spigotmc.org/resources/auto-smelt.71576/

### Steps to Reproduce

start mining quest like mining iron for example (blockbreak event) and enable autosmelt, try to break the iron ore and you will see that the quest plugin is not counting it when the autosmelt is enabled

### Environment

- Minecraft version: 1.21.1
- Server software: purpur
- Quests version: 3.15.2

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

autosmelt plugin is open source plugin, may that help on fixing the issue idk

**Comment by Krakenied** [comment]
It's autosmelt issue - for some reason it cancels BlockBreakEvent making other plugins assume that the block hasn't been broken. It may lead to many other issues too. Probably, just for example, CoreProtect won't log these block breaks properly.
