### ISSUE TITLE
Prevent players from placing blocks before completing a quest to make it easier to do

### ISSUE THREAD

**Issue by FourNineRugz** [LMBishop/Quests#78]
**Description of Feature**
Prevent players from placing blocks before completing a quest to make it easier to do

**Additional Information**
Simply having the feature to subtract blocks so players can't silktouch them to complete quests isn't enough in my opinion. I think if possible, it should detect if ores are naturally generated for players.

**Comment by Disorbs** [comment]
have you tried using the reverse of block placed option to prevent this?

    tasks:
      mining:
        type: "blockbreakcertain"
        amount: 50
        block: POTATO
        reverse-if-placed: true
        use-similar-blocks: false
