### ISSUE TITLE
Condition for Quests

### ISSUE THREAD

**Issue by TimHarrio** [LMBishop/Quests#82]
**Description of Feature**
Add conditions to complete a quest (example: being in the mining world to do mining quests or a placeholder equals a value)

**Alternative Methods**
I use DeluxeMenu to add conditions but it doesn't work quite well

**Additional Information**
Do not answer me to put in task "being in the mining world" because we can accept the quest in the mining world and then complete it in another world so it does not work quite well.

**Comment by LMBishop** [comment]
Most tasks can have world constraints now https://github.com/LMBishop/Quests/wiki/Task-Configuration-Layout
