### ISSUE TITLE
More Placeholders

### ISSUE THREAD

**Issue by TimHarrio** [LMBishop/Quests#83]
**Description of Feature**
Add placeholders for:
- The number of quests in progress
- The number of quests completed
- The number of quests completed in a category
- The total number of quests
- The total number of quests in a category

**Additional Information**
If you have ideas of placeholders to add say them below 👇👇👇

**Comment by maxlehot1234** [comment]
+1

**Comment by maxlehot1234** [comment]
I need this to build a TOP quests of the month using external plugins like Leaderheads that use placeholders from other plugins to create fully customize TOP GUI ;)

Thanks in advance @LMBishop
