### ISSUE TITLE
Inventory task progress

### ISSUE THREAD

**Issue by gazdyy** [LMBishop/Quests#86]
**Description of Error**
"inventory" tasks do not show progress

**Screenshots**
![image](https://user-images.githubusercontent.com/60019769/79511621-f6322d80-803f-11ea-8d2a-2876794f061f.png)

**Config:**
tasks:
  gathering:
    type: "inventory"
    item: GOLD_NUGGET
    amount: 64
    remove-items-when-complete: false
display:
  name: "&fSběrací úkol: #9"
  lore-normal:
    - "&fcollect 64 gold nuggets"
    - "&f"
    - "&fprogress: &f{gathering:progress}/64 gold nuggets."
  type: "GOLD_NUGGET"
rewards:
  - "cmi money give {player} 250"
options:
  category: "gathering"
  requires:
  - ""
  repeatable: false
  cooldown:
    enabled: true
    time: 2880
  sort-order: 29

**Server:**
 - Minecraft Version: 1.15.2
 - Mod Name: Paper

**Plugin:**
 - Version: 2.9.1

**Comment by LMBishop** [comment]
Duplicate, see #7

**Comment by gazdyy** [comment]
Please fix! :(
