### ISSUE TITLE
Blockbreakcertain quests don't work 

### ISSUE THREAD

**Issue by Tikifirst** [LMBishop/Quests#93]
**Description of Error**
Hi,

With the latest version of Quests, the blockbreakcertain quests don't work, even if the player break the block, this don't make the progress to increase, so I have to use Quests v2.4 ^^

**To Reproduce**
Pick a blockbreakcertain quest, try to break the specified block and watch the progress with /q

**Server (please complete the following information):**
 - Minecraft Version: 1.8
 - Mod Name: Paper Spigot 1.8

**Plugin (please complete the following information):**
 - Version: Quests 2.9.3
**Stacktrace**
none stacktrace found in latest.logs :/

**Comment by LMBishop** [comment]
Ensure you are using 1.8 block names and not the provided 1.13 block names in the default config
