### ISSUE TITLE
Prevent blockplacingcertain block if a player has accepted a blockbreakingcertain quest

### ISSUE THREAD

**Issue by Tikifirst** [LMBishop/Quests#95]
**Description of Feature**

Hi,

If a player has accepted a quest like "Mine x100 diamonds", he just can take a silktouch pickaxe, mine some diamonds ore, replace them, mine them again, mine them again, place them, mine them again, ... and he has completed a quest !

**Alternative Methods**

Prevent players placing specific block when he has accepted a blockbreakcertain task quest. (configurable in config.yml)

**Comment by Tikifirst** [comment]
Or prevent making any progress if player is holding a silktouch tool for blockbreakcertain task quest

**Comment by LMBishop** [comment]
something similar can be achieved, see [reverse-if-broken](https://github.com/LMBishop/Quests/wiki/Task-Configuration-Layout#blockplacecertain)
