### ISSUE TITLE
progress not work. How to fix?

### ISSUE THREAD

**Issue by SzlugPL** [LMBishop/Quests#97]
tasks:
  beef:
    type: "inventory"
    item: WHEAT
    amount: 32
display:
  name: "&cFarmer (1)"
  lore-normal:
    - "&7Aby ukonczyc misje musisz:"
    - "&7 - Zebrac 32 przeniscy."
    - ""
    - "&7Nagroda:"
    - "&7 - 30 diamonds."
    - "&7 - 10$"
  lore-started:
    - ""
    - "&7Twoj obecny postep:"
    - "&7 - {beef:progress}/32 zebranych przenicy"
  type: 'WHEAT'
  remove-items-when-complete: true
rewards:
  - "give {player} diamond 30"
  - "eco give {player} 10"
options:
  category: "startowe"
  repeatable: true
  cooldown:
    enabled: false
    time: 10
  sort-order: 3

**Comment by LMBishop** [comment]
see #7
